### ISSUE TITLE
Display language override

### ISSUE THREAD

**Issue by 9vult** [jellyfin/jellyfin-media-player#100]
Currently, the display language defaults to the system language. It'd be nice if there was a way to override the display language to whatever language we want.

**Comment by iwalton3** [comment]
You can change the language under Settings > Display.
![image](https://user-images.githubusercontent.com/8078788/127779195-5db21b94-0759-4caf-aba2-bd314e3de3b4.png)
![image](https://user-images.githubusercontent.com/8078788/127779205-bceb7737-06bd-4663-ad0b-ca74cb038921.png)
There is a client settings menu though that currently is not translated. There is a plan for future Jellyfin web client versions to support translating extensions to the web player, but it hasn't happened yet.
