### ISSUE TITLE
Missing dependency at LinuxMint?

### ISSUE THREAD

**Issue by EvilOlaf** [jellyfin/jellyfin-media-player#103]
**Describe the bug**
When trying to install jellyfin media player on Linux Mint 20.1 Ulyssa it cannot be started due to missing dependency on installation

**To Reproduce**
- Get Linux Mint 20.1 Ulyssa Cinnamon 
- Install via `dpkg -i` the .deb for focal
- Fix dependencies via `apt install -f`
- Try to start via desktop (simply nothing will happen) or via jellyfinmediaplayer command (it will blame you `jellyfinmediaplayer: error while loading shared libraries: libQt5Xml.so.5: cannot open shared object file: No such file or directory`)
- 
**Expected behavior**
Since installing `libqt5xml5` package fixes this I suggest to add it as dependency to the jellyfin package.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint amd64
 - Version: 20.1 Ulyssa Cinnamon
 - Installation Method: dpkg

**Additional context**
I do not know if other desktop variant (a.k.a. MATE) is affected as well, I assume it is.
Let me know if I missed something.

Thank for reading :)

Cheers
Werner

**Comment by gringofe** [comment]
Having a similar problem on Mint 19.3 (Tricia):

`jellyfinmediaplayer: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.11' not found (required by jellyfinmediaplayer)`

**Comment by n-peugnet** [comment]
> Having a similar problem on Mint 19.3 (Tricia):
> 
> `jellyfinmediaplayer: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version 'Qt_5.11' not found (required by jellyfinmediaplayer)`

Linux mint 19.3 (Tricia) is based on Ubuntu 18.04 (bionic) for which jellyfin-media-player isn't built. You probably installed the package built for focal or groovy but these are not compatible.

One solution would be to update you Linux mint system to the latest release.

**Comment by mmoreaux** [comment]
This also happens with `jellyfin-media-player_1.6.0-1_amd64-bullseye.deb` on Debian 11/Bullseye. It's definitely a missing dependency for _that_ build.

**Comment by rshxyz** [comment]
Saw the same issue on ubuntu 20.04 LTS (Focal) and fixed it by installing libqt5xml5

**Comment by iwalton3** [comment]
I believe this was handled and I never closed it. Let me know if that's not the case.
