### ISSUE TITLE
"Playlist" shortcuts don't work in media player from home screen, shuffle button doesn't work in playlist page

### ISSUE THREAD

**Issue by Swizzler121** [jellyfin/jellyfin-media-player#104]
**Describe the bug**
When on the home screen, if you press the "playlist" button it switches to the screen with just a loading animation that never completes. If you instead click on music then the playlists button at the top it works fine. Also, if you go to the playlist, then click shuffle or play, it also just shows an infinite load. If I select a song from the playlist, then click shuffle it works fine. I've tested this in the browser interface and it works fine, issue only occurs in the media player. I've also tested on 2 machines on 2 networks and the issue remains the same 

**To Reproduce**
1. Go to home screen
2. Click on playlists
3. Hangs with a loading animation

**Another Step to Reproduce**
1. Click on Music
2. Click on the "playlists" option at the top of music
3. Click on a playlist
4. Click the shuffle button
5. Hangs with a loading animation

**Expected behavior**
the Playlist button on the home screen to bring you to your playlists, and the shuffle button on the playlist screen to shuffle and play your playlist

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Version 1.6.0
 - Installation Method: windows installer

**Comment by rgigger** [comment]
This happened to me as well

**Comment by sevenrats** [comment]
Hey, thanks for your report! If you still experience this issue you will want to open a bug report at github.com/jellyfin/jellyfin-web
