### ISSUE TITLE
Provide chocolatey installation method

### ISSUE THREAD

**Issue by a-rekkusu** [jellyfin/jellyfin-media-player#106]
Hi there,

I'd like to see support for [chocolatey installation ](https://community.chocolatey.org/) on Windows. It is a project that aims to bring CLI-based installation and software management known from Linux to Windows. 

You would only have to run something like
`choco install jellyfin-media-player -y`
in the Terminal or a PowerShell and be done with it.

What do you think?
Thanks for the work on this project, it is the best Jellyfin Client for PCs imho.

**Comment by SaifAqqad** [comment]
I've made a PR (microsoft/winget-pkgs#18597) to add it to winget
when it's merged, you can just `winget install Jellyfin.JellyfinMediaPlayer `

**Comment by dkanada** [comment]
@SaifAqqad will that need manual updates for every release?

**Comment by SaifAqqad** [comment]
Yes, someone needs to update the manifest file for every new release

**Comment by MohandL3G** [comment]
Yea, Please, I would love to this on choco.

**Comment by ageekhere** [comment]
Just updated to 1.6.1 via winget, all went well though it did force a pc restart without any warning.

**Comment by allthesebugsv2** [comment]
Would you mind updating the winget version to 1.7.0? Thanks!

**Comment by sevenrats** [comment]
this is another example of "we dont have the resources to maintain every single package manager in existence"  we aren't even in ubuntu repos, for example.  if you are somebody who is confident in chocolatey, pretty much the only conceivable way forward is for you to take ownership over JMP chocolatey support and PR everything in.  for the time being our resources are limited to reviewing.
