### ISSUE TITLE
Add a exit button to the interface when  "fullscreen": true

### ISSUE THREAD

**Issue by ageekhere** [jellyfin/jellyfin-media-player#108]
**Is your feature request related to a problem? Please describe.**
Currently you have to use keyboard shortcuts(F11) in order to exit full screen mode (difficult when using a wireless pc remote)   

**Describe the solution you'd like**
Add a exit program button on the top right of the interface.

**Describe alternatives you've considered**
An alternative could be that there is always an exit button even when not in fullscreen mode.

**Additional context**
For use with a media center using a wireless pc remove using jellyfin in fullscreen mode and wanting to exit Jellyfin without exiting fullscreen mode or creating a key bind.

**Comment by iainsaxonhome** [comment]
Second this request :) .

I'm trying to set up a similar system using Flex Launcher as the "main menu" for the HTPC so an exit button would be handy.

It looks like there should be a long press for the ESC key to do this however I haven't been able to get it to work on the Flatpak version of the JMP:
https://github.com/jellyfin/jellyfin-media-player/blob/193cacf817dd1c0ac289cb49f61a81c77c2c9fbb/resources/inputmaps/keyboard.json#L14

**Comment by iwalton3** [comment]
There is an exit button in the application under user settings.
