### ISSUE TITLE
fullscreen setting not saved on exit

### ISSUE THREAD

**Issue by ageekhere** [jellyfin/jellyfin-media-player#118]
If you enabled fullscreen and press f11 and exit Jellyfin, when you reopen Jellyfin it would not be in fullscreen mode.

**Comment by BocuD** [comment]
I actually have a similar issue right now with a slightly different effect.. my client is stuck in fullscreen mode and i haven't been able to get it out yet; and resetting settings hasn't done anything so far (same for relaunching / rebooting whatever)

**Comment by mekemahmud** [comment]
I found a simple solution for both your problems (if you're a windows user). Just search for "jellyfinmediaplayer.conf" file in C drive and open the file in notepad when you find the file. Find the "main": section in the  file, then change the values as you need:
for fullscreen when you open jellyfin, change the value for ""forceAlwaysFS" to true, 
for exiting from full screen mode , change the value of "fullscreen": to false.
Then just save the file by Ctrl+S and close the file.
Thanks.
![Capture](https://user-images.githubusercontent.com/89276060/130285837-9912ba97-da54-4688-ae13-7f1e637f2c05.JPG)

**Comment by BocuD** [comment]
For future reference:
The actual path for the above mentioned file is `C:\Users\%USER%\AppData\Local\JellyfinMediaPlayer`

**Comment by ageekhere** [comment]
Hmm in local why are there two folders
Jellyfin Media Player
JellyfinMediaPlayer

Was the location changed at one point?

**Comment by iwalton3** [comment]
Yes the one with spaces is the new one. It was an unintentional side effect of another fix that set the application name.
