### ISSUE TITLE
TV Mode - Menu doesn't scroll with active selection

### ISSUE THREAD

**Issue by dephcon** [jellyfin/jellyfin-media-player#123]
Just would out about TV Display mode on the webapp today and it works pretty great.  I enabled TV Mode in JMP and it doesn't quite function right.  When using down_arrow to scroll down in my home screen (or libraries for that matter), the focus doesn't follow the active cursor and scroll down.

In the web app, once you scroll down to something that's not entirely on the screen (3rd row usually), the active row snaps to the center of the screen.  This does not happen in JMP.

This is the last piece that will finally allow me to stop using Plex Media Center on my HTPC.  Thanks for your dev efforts!

**Comment by iwalton3** [comment]
Try restarting the application. The setting doesn't fully take effect when you change it.

**Comment by dephcon** [comment]
well now I feel dumb, thank you!
