### ISSUE TITLE
Channel names / icons disappear when scrolling in live tv guide

### ISSUE THREAD

**Issue by PilotBob42** [jellyfin/jellyfin-media-player#126]
**Describe the bug**
Channel names / icons disappear in the live TV guide when scrolling up and down repetitively.

**To Reproduce**
1. Go to "Live TV" and then "Guide". You will see the guide populated as expected with program data, channel names and likely icons for each network presented.
2. Scroll down some number of channels and then back up to see the previous channels. While the program data is still present, the channel names / icons are now blank when they were previously populated.
3. Scrolling back down will reveal the same missing name / icon for the channels below that were previously visible.
4. The effect can continue to occur at any place in the list where one may scroll up and down (or down and up) successively. Eventually, all channel info on the left side can be made to disappear in this way.
5. Switching to the "Programs" tab and the back to "Guide" resets the channel icons, but it can then be lost again in the same manner.

**Screenshots**
Right after entering "Guide" and before any scrolling. Everything as expected.
![image](https://user-images.githubusercontent.com/42297855/127896446-ec0f3446-a5cb-4bbe-8079-de6bf98e79b3.png)

Scrolling down and then back up. What happened to NBC and MyTV?
![image](https://user-images.githubusercontent.com/42297855/127896596-13f19fe0-a8f2-4196-9e65-cf609e15c350.png)

Scrolling back down again. Channel names / icons that were present a moment ago are now missing too.
![image](https://user-images.githubusercontent.com/42297855/127896693-63352928-a228-4a75-9639-afc5b65efb64.png)

**Desktop (please complete the following information):**
I installed Jellyfin Media Player v1.6.1 on a Linux Mint 20.2 system using the downloadable deb package for "focal" (upon which Mint 20 is based). TV source is an HDHomeRun Prime and guide data is supplied by SchedulesDirect.

System:    Host: Bobs-Linux Kernel: 5.11.0-25-generic x86_64 bits: 64 Desktop: Cinnamon 5.0.5 Distro: Linux Mint 20.2 Uma
Machine:   Type: Desktop Mobo: Micro-Star model: A320M-A PRO (MS-7C51) v: 1.0
           UEFI: American Megatrends v: 1.40 date: 12/08/2020
CPU:       Topology: 6-Core model: AMD Ryzen 5 3600X bits: 64 type: MT MCP L2 cache: 3072 KiB
           Speed: 2199 MHz min/max: 2200/3800 MHz Core speeds (MHz): 1: 2199 2: 2029 3: 2199 4: 2199 5: 2200 6: 2200 7: 2199
           8: 2201 9: 2200 10: 2199 11: 2244 12: 2200
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Navi 14 [Radeon RX 5500/5500M / Pro 5500M] driver: amdgpu v: kernel
           Display: x11 server: X.Org 1.20.9 driver: amdgpu,ati unloaded: fbdev,modesetting,radeon,vesa tty: N/A
           OpenGL: renderer: Radeon RX 5500 (NAVI14 DRM 3.40.0 5.11.0-25-generic LLVM 12.0.0) v: 4.6 Mesa 21.2.0-rc3
Audio:     Device-1: Advanced Micro Devices [AMD/ATI] Navi 10 HDMI Audio driver: snd_hda_intel
           Device-2: Advanced Micro Devices [AMD] Starship/Matisse HD Audio driver: snd_hda_intel
           Sound Server: ALSA v: k5.11.0-25-generic
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169
           IF: enp37s0 state: up speed: 1000 Mbps duplex

**Comment by iwalton3** [comment]
Does this happen in the web client too or just Jellyfin Media Player?

**Comment by PilotBob42** [comment]
@iwalton3 The web client works as expected. This only happens in Jellyfin Media Player.

**Comment by iwalton3** [comment]
If someone has live TV set up and wants to debug this with devtools, it would be greatly appreciated.

**Comment by PilotBob42** [comment]
It's been forever since I did any real coding, not sure I would be much help. But I would like to see this get fixed. Perhaps a way to debug would be to make a mock tuner just so that the guide could be set up and the bug reproduced? It's not necessary to actually play anything for the problem to be seen, just scrolling up and down in the guide. If a Schedules Direct subscription is the impeding issue, I would gladly offer my account for debugging purposes.

**Comment by TheFeelTrain** [comment]
I'm not able to reproduce this. No matter how much I scroll up and down the icons are still there.

I am on Plasma with the propriety NVIDIA drivers so maybe it has something to do with Cinnamon or mesa?

**Comment by PilotBob42** [comment]
Came back to try this again with v1.7.0 pr4 and the problem still persists. My system is similar to what it was before, but it's a fresh install and nearly every component has been updated. Now Linux Mint 20.3 Una with Cinnamon 5.2.7, Mesa 22.2, and kernel 5.15. New motherboard, new CPU, new graphics card, same issue as before. Haven't found any sort of similar issues with any other apps from Ubuntu or Debian.

Could it be Cinnamon, Mesa, or the AMDGPU driver? Does anyone else have a similar set up with an HDHomeRun tuner that could try it out?

> System:    Kernel: 5.15.0-33-generic x86_64 bits: 64 Desktop: Cinnamon 5.2.7 Distro: Linux Mint 20.3 Una 
> Machine:   Type: Desktop Mobo: ASRock model: B550M-HDV serial: <filter> UEFI: American Megatrends LLC.
> v: P2.10 date: 02/24/2022 
> CPU:       Topology: 12-Core model: AMD Ryzen 9 5900 bits: 64 type: MCP L2 cache: 6144 KiB 
> 
> Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] driver: amdgpu v: kernel 
> Display: x11 server: X.Org 1.20.13 driver: amdgpu resolution: 2560x1440_60.00~60Hz 
> OpenGL: renderer: AMD Radeon RX 6600 (navi23 LLVM 14.0.0 DRM 3.42 5.15.0-33-generic) 
> v: 4.6 Mesa 22.2.0-devel (git-cbcdcc4 2022-06-11 focal-oibaf-ppa) 
> 
> Audio:     Device-1: Advanced Micro Devices [AMD/ATI] driver: snd_hda_intel 
> Device-2: Advanced Micro Devices [AMD] Starship/Matisse HD Audio driver: snd_hda_intel 
> Device-3: Logitech type: USB driver: snd-usb-audio,uvcvideo 
> Sound Server: ALSA v: k5.15.0-33-generic 
> 
> Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 
> Sensors:   System Temperatures: cpu: 41.0 C mobo: N/A gpu: amdgpu temp: 36 C 
>            Fan Speeds (RPM): fan-1: 1260 fan-2: 1788 fan-3: 0 fan-4: 0 fan-5: 0 gpu: amdgpu fan: 1013 
> Info:      Processes: 431 Uptime: 3d 13h 30m Memory: 31.28 GiB used: 5.22 GiB (16.7%) Shell: bash inxi: 3.0.38

**Comment by PilotBob42** [comment]
@iwalton3 I've built from source and the problem remains. If you can guide me to the info you would need collected, I will do my best to get it to you.

**Comment by mekwall** [comment]
The whole Live TV section is in dire need of some love in the https://github.com/jellyfin/jellyfin-web project. It performs horribly and is nearly unusable on WebOS so I imagine a rewrite to React would help a lot and most likely solve this issue as well.

**Comment by PilotBob42** [comment]
An update on this issue, I'm now on Linux Mint 21 and Jellyfin client version 1.7.1 and the issue has been resolved. It's likely the result of one of the many updates Linux Mint received with it's most recent major version update, but I have no idea which.

```
System:
  Kernel: 5.18.19-051819-generic arch: x86_64 bits: 64 compiler: gcc
    v: 11.3.0 Console: pty pts/1 Distro: Linux Mint 21 Vanessa base: Ubuntu
    22.04 jammy
Machine:
  Type: Desktop Mobo: ASRock model: B550M-HDV serial: N/A UEFI: American
    Megatrends LLC. v: L2.11 date: 04/25/2022
CPU:
  Info: 12-core model: AMD Ryzen 9 5900 bits: 64 type: MCP arch: Zen 3 rev: 2
    cache: L1: 768 KiB L2: 6 MiB L3: 64 MiB
  Speed (MHz): avg: 2200 min/max: 2200/4787 boost: enabled cores: 1: 2200
    2: 2200 3: 2200 4: 2200 5: 2200 6: 2200 7: 2200 8: 2200 9: 2200 10: 2200
    11: 2200 12: 2200 bogomips: 71866
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Navi 23 [Radeon RX 6600/6600 XT/6600M] vendor: ASRock
    driver: amdgpu v: kernel arch: RDNA-2 bus-ID: 08:00.0
  Device-2: Logitech Logitech Webcam C925e type: USB
    driver: snd-usb-audio,uvcvideo bus-ID: 1-4.1:3
  Device-3: Realtek RTL2832U DVB-T type: USB driver: N/A bus-ID: 3-3.4:3
  Display: x11 server: X.Org v: 1.21.1.3 with: Xwayland v: 22.1.1 driver:
    X: loaded: amdgpu gpu: amdgpu resolution: 2560x1440
  OpenGL: renderer: NAVI23 (navi23 LLVM 14.0.0 DRM 3.46
    5.18.19-051819-generic) v: 4.6 Mesa 22.2.1 direct render: Yes
```
