### ISSUE TITLE
Server-provided custom CSS local import not working

### ISSUE THREAD

**Issue by jmqm** [jellyfin/jellyfin-media-player#131]
**Describe the bug**
Server-provided custom CSS that has local imports are not being retrieved properly. Instead of getting the CSS files from the server, it gets it locally (presumably).

**To Reproduce**
1. Dashboard -> General -> Custom CSS
2. Add a local import like `@import "./custom_style.css";`
3. Restart JMP

**Expected behavior**
Import CSS files local to the server, not the client.

**Screenshots**
Jellyfin Web (Chrome)
![jfweb](https://user-images.githubusercontent.com/68612932/128985603-63f2a519-7817-4bdb-b9f8-0816ceff7cf3.jpg)

Jellyfin Media Player
![jmp](https://user-images.githubusercontent.com/68612932/128985622-a75ae23e-44d4-42d6-ae47-528d3747db05.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Jellyfin 10.7.6, Jellyfin Media Player 1.6.1
 - Installation Method: Windows x64

**Additional context**
From my testing, the issue can be resolved if I add the custom CSS to my JMP's web-client folder. From my limited understanding, jellyfin-web is local, it doesn't send GET requests to my server and that's what causes my issue.

**Comment by iwalton3** [comment]
JMP doesn’t know where your web server is for custom css because it runs a local copy of the web client. Use the full, absolute path to the css file on your server. (The alternative is I parse the css and make it absolute, which is not ideal…)

**Comment by jmqm** [comment]
I could make it absolute using my DDNS, but internet outages are becoming more frequent for me so having them local is more ideal (no custom DNS available on my router). Using local paths doesn't work because I have external access as well.

Due to my circumstances, I suppose it's either what you mentioned earlier, parsing CSS and changing the paths, or I write two import statements each, one using absolute, one using local.

Another solution could be making a GET request to parse the server-provided custom CSS, if jellyfin-web has that function. Is there an API call for that?

**Comment by iwalton3** [comment]
Jellyfin does not have anything that parses and fixes the css. It seems using two imports is likely your best bet.
