### ISSUE TITLE
How to make input.conf work on Jellyfin as it works in MPV?

### ISSUE THREAD

**Issue by rubensgpl** [jellyfin/jellyfin-media-player#136]

**Comment by iwalton3** [comment]
See this: https://github.com/jellyfin/jellyfin-mpv-shim/releases/tag/v2.0.0

**Comment by rubensgpl** [comment]
It doesn't open Jellyfin, I was using 2.0.1 neither is working for me.

**Comment by acedogblast** [comment]
Would really be great as I would like to add in shaders such as Anime4K into the video.

**Comment by sevenrats** [comment]
closing as blocked per izzie's comment.
@acedogblast you can add shaders with mpv.conf. check out the docs
