### ISSUE TITLE
C++ 2015-2019 problem | v1.6.1

### ISSUE THREAD

**Issue by KAURkulaator** [jellyfin/jellyfin-media-player#137]
**Describe the bug**
"Media Error: no audio or video data played" on bottom left.

**To Reproduce**
1. Open any Movie / TV show (it starts playing fine at first).
2. Change the video quality setting or exit and reopen the movie.

**Expected behavior**
The movie to play.

**Screenshots**
![image](https://user-images.githubusercontent.com/89666207/131193531-8754741a-f928-4db7-a619-526d09aa4e2d.png)

**Desktop (please complete the following information):**
 - Windows 10 Pro
 - 21H1 (19043.1165)
 - Windows Installer x64

**Additional context**
The problem is with the C++ 2015-2019 version, you need to update it :)
Once I update it form 14.29.30040 (this is installed by the Media Player x64 installer) to 14.29.0.30133 then it started working great.
![image](https://user-images.githubusercontent.com/89666207/131193689-a8c1bec1-cfc5-427f-9036-4eb8dfd04aa5.png)

**Comment by iwalton3** [comment]
Closing as stale. Please re-open if this issue is still applicable.
