### ISSUE TITLE
Cant connect server after login

### ISSUE THREAD

**Issue by okan35** [jellyfin/jellyfin-media-player#138]
A log of issue
pastebin.com/KHCgMa31

**Describe the bug**
After adding new server and successful login, cant connect server.

**To Reproduce**
Basically add a server and login, you won't be able to go to your home screen
**Expected behavior**
It should successfully show home screen after login.

**Desktop (please complete the following information):**

Windows 10
player version 1.6.1
Windows installer

**Comment by sevenrats** [comment]
Its not clear whether these logs show a borked database or a temporary bug in the code but either way i would not expect this issue to persist, and the lack of corroborating reports in the meantime leads me to attribute this to one-off data corruption. please open a new report if this issue still persists in a supported version of JMP.
