### ISSUE TITLE
New settings styling cuts off subtitle settings

### ISSUE THREAD

**Issue by tydog98** [jellyfin/jellyfin-media-player#142]
**Describe the bug**
The size setting for subtitles is cut off

**To Reproduce**
Open latest git version of the program
Open settings
Scroll down to subtitles

**Expected behavior**
Size setting should not be cut off

**Screenshots**
![unknown](https://user-images.githubusercontent.com/45440255/132630639-476fba73-6c1c-4931-b8de-23aca38759b0.png)

**Desktop (please complete the following information):**
Arch Linux Gnome Wayland

**Comment by TheFeelTrain** [comment]
This was my bad, it turns out Ultrachrome adds the bottom margin it needs.
