### ISSUE TITLE
Jellyfin media player blocks access to audio stream for other applications

### ISSUE THREAD

**Issue by Norde** [jellyfin/jellyfin-media-player#148]
Hello,

First of all, thank you for all this work around Jellyfin and the associated applications.

I have a very annoying problem:
When I start an audio playback with Jellyfin Media Player, no other application (not even the system applications) has access to the audio output (Jellyfin Media Player got the exclusive access). So I can't play several audio streams simultaneously.

It returns to normal when I stop the playback.

Any suggestions ?

System : Windows 10
Jellyfin Media Player: 2.6.1

**Comment by iwalton3** [comment]
Did you enable exclusive output or pass through in the audio configuration?

**Comment by Norde** [comment]
Not at all, only normalize option (whose deactivation does not affect my problem).
I already tried an clean install of Jelllyfin Media Player without success.

What kind of Windows or Jellyfin log could help me with this?
