### ISSUE TITLE
Buttons are not visible and replaced by boxes

### ISSUE THREAD

**Issue by metronidazole** [jellyfin/jellyfin-media-player#15]
I'm using arch linux and have the following issue:

https://i.imgur.com/pH5VtdD.png

I have the segoe UI font installed so not sure why it is still not working.

**Comment by iwalton3** [comment]
This is (was?) a problem with the AUR package.

**Comment by AdmiralAnimE** [comment]
Also happens on Windows 8.1. And zooming on the page with control+ is not remembered on next start.

**Comment by metronidazole** [comment]
> This is (was?) a problem with the AUR package.

What is specifically wrong with the package? I don't see any obvious dependency issue.

**Comment by iwalton3** [comment]
I don't know but at some point it only occured when people were using the AUR package. It's probably fixed by now.

**Comment by metronidazole** [comment]
> I don't know but at some point it only occured when people were using the AUR package. It's probably fixed by now.

I tried rebuilding the package but it still has the issue. Admittedly, the flakpak version seems to work fine.

**Comment by JamesTX10** [comment]
I just installed this today on windows 7 and I have the box replaced icons. How can I resolve this?

**Comment by iwalton3** [comment]
Someone who has this problem please provide me more information by using the web debugger: https://github.com/jellyfin/jellyfin-media-player#web-debugger

Please consider upgrading to a supported version of Windows as it is a security risk.

**Comment by AdmiralAnimE** [comment]
Is this what you want?
![asd](https://user-images.githubusercontent.com/6396538/116650959-df305600-a98a-11eb-8719-65e3b03a517d.jpg)

**Comment by iwalton3** [comment]
Yes so the question is if the font is able to load and is anything odd in the web inspector is happening. Something that wouldn't show up in the log.

**Comment by wc7086** [comment]
> This is (was?) a problem with the AUR package.

The AUR package still has this problem, is this caused by a lack of dependencies?

**Comment by wc7086** [comment]
@iwalton3 
It seems that if the Linux version also uses the Segoe UI fonts, it would violate the EULA of the Segoe UI fonts?

Is it possible to replace the Segoe UI fonts on linux with other solutions?

**Comment by iwalton3** [comment]
The only place I see that font being referenced is the windows installer. I don't actually bundle it. https://github.com/jellyfin/jellyfin-media-player/search?q=segoe&type=

**Comment by wc7086** [comment]
> The only place I see that font being referenced is the windows installer. I don't actually bundle it. https://github.com/jellyfin/jellyfin-media-player/search?q=segoe&type=

I noticed this too, I'm not a front-end developer, so when I encountered this problem I subconsciously thought it might be a Windows proprietary font being used in some place I didn't know about and I didn't have the relevant font installed causing the problem.

**Comment by wc7086** [comment]
What error do you think could be causing this? I might be able to try to solve this problem.
@iwalton3

**Comment by metronidazole** [comment]
> @metronidazole What is replaced is the material icon, please revise the content of the question.

Let me know what you want it changed to and I can do so.

**Comment by wc7086** [comment]
Add the screenshot below and make it clear that what is being replaced with the box is the button's material icon.

![image](https://user-images.githubusercontent.com/74053663/171229995-ff640214-de88-423e-bf67-b7ae814372b9.png)

**Comment by jerry-ch-issue** [comment]
win8.1, same problem, search it a lot, cant fix it.

**Comment by jerry-ch-issue** [comment]
> win8.1, same problem, search it a lot, cant fix it.

I finally fix it after changing css.

As the link below says.
[https://jellyfin.org/docs/general/clients/css-customization.html#change-icon-pack](url)

I filled in "Custom CSS code" with 

@import url("https://cdn.jsdelivr.net/gh/prayag17/Jellyfin-Icons/Font%20Awesome/solid.css");

Notice that the sample links in the web missing " after (

**Comment by iwalton3** [comment]
Closing as stale. If someone still has this issue, please re-open.

**Comment by OwlDaddy** [comment]
Greetings...
It appears this problem still exists.  I am using Windows 8.1 and the problem is just as described by OP.  If the post by jerry-ch-issue above is some kind of fix, it eludes me.
I am using the latest version JellyfinMediaPlayer-1.11.1-windows-x64.exe
Hoping to get some help, thank you

**Comment by wc7086** [comment]
> If the post by jerry-ch-issue above is some kind of fix, it eludes me. 

The problem was caused by a failure to load CSS, which was obtained from the Internet.
