### ISSUE TITLE
Support Wayland using the "--platform" command line parameter

### ISSUE THREAD

**Issue by major-mayer** [jellyfin/jellyfin-media-player#159]
**Is your feature request related to a problem? Please describe.**
I would like to use Jellyfin Media Player with native Wayland support without the need to specify environment variables.
This can be a bit tricky inside .desktop files. Most other QT-based applications allow this too.

**Describe the solution you'd like**
Start Jellyfin with Wayland support by doing this:
```zsh
~ >>> jellyfinmediaplayer --platform wayland                                   
jellyfinmediaplayer: Unknown option 'platform'.
```
This should not lead to an error but instead do the same like:
```zsh
QT_QPA_PLATFORM=wayland jellyfinmediaplayer
```

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by major-mayer** [comment]
Anything new about this? 
The reason i am asking is that i don't get Jellyfin running using native Wayland mode from a .desktop file.
It looks like this:
```ini
[Desktop Entry]
Version=1.1
Type=Application
Name=Jellyfin Media Player
Comment=Desktop client for Jellyfin
Icon=com.github.iwalton3.jellyfin-media-player
Exec=env QT_QPA_PLATFORM=wayland jellyfinmediaplayer %c %i
Actions=DesktopF;DesktopW;TVF;TVW;
Categories=AudioVideo;Player;TV;Video;

[Desktop Action DesktopF]
Name=Desktop [Fullscreen]
Exec=jellyfinmediaplayer --fullscreen --desktop

[Desktop Action DesktopW]
Name=Desktop [Windowed]
Exec=jellyfinmediaplayer --windowed --desktop

[Desktop Action TVF]
Name=TV [Fullscreen]
Exec=jellyfinmediaplayer --fullscreen --tv

[Desktop Action TVW]
Name=TV [Windowed]
Exec=jellyfinmediaplayer --windowed --tv
```

When i try to start Jellyfin simply nothing happens.
The command that i use works from the terminal tho... Anyone got an idea?

**Comment by iwalton3** [comment]
I have released this in this pre-release: https://github.com/jellyfin/jellyfin-media-player/releases/tag/v1.7.0-pre3

**Comment by major-mayer** [comment]
Wonderful, thank you very much :heart: :+1: 
As soon as this is release officially i will test it (I need to wait until the AUR package gets updated).
