### ISSUE TITLE
api-ms-win-core-winrt-string-l1-1-0.dll missing

### ISSUE THREAD

**Issue by Mattia98** [jellyfin/jellyfin-media-player#162]
After fresh installation JellyfinMediaPlayer complains about api-ms-win-core-winrt-string-l1-1-0.dll  being missing.
The Universal C Runtime is installed, but it does not ship the aforementioned dll file. It seems maybe Jellyfin does not load the correct dll file? The UCR does ship with api-ms-win-core-string-l1-1-0.dll and api-ms-win-crt-string-l1-1-0.dll but not api-ms-win-core-winrt-string-l1-1-0.dll. Could there be an error in the compilation where the wrong dll is linked?

Installer: JellyfinMediaPlayer-1.6.1-windows-x64.exe
OS: Windows 7 SP1 with (KB3118401)

**Comment by SongShawn** [comment]
Me too

**Comment by iwalton3** [comment]
The software requires Windows 10 due to some media integrations

**Comment by 1273294133** [comment]
me too

**Comment by goodryb** [comment]
Are there any plans to support Windows7 ?

**Comment by iwalton3** [comment]
If someone else fixes it and it’s not an obtrusive fix, then yes. I personally have no plans to work on this as I don’t have any Windows 7 VMs or computers anymore and it is end of life.
