### ISSUE TITLE
"Fallback font" not working.

### ISSUE THREAD

**Issue by leoleoasd** [jellyfin/jellyfin-media-player#163]
Four considerations:
 - Please do not open bug reports to ask questions. Use the Discussions feature instead.
 - Please make sure the issue only pertains to Jellyfin Media Player. If it also occurs in the web client, send the issue to jellyfin-web instead.
 - Please make sure that your issue is not being caused by errors in custom CSS or note that you are using custom CSS.
     - Notably, there have been instances of custom CSS breaking TV mode.
     - You can disable custom CSS under Display in the user settings.
 - Please provide logs. You can drag the log file into the issue to attach it.
     - Windows: `%LOCALAPPDATA%\JellyfinMediaPlayer\logs`
     - Linux: `~/.local/share/jellyfinmediaplayer/logs/`
     - Linux (Flatpak): `~/.var/app/com.github.iwalton3.jellyfin-media-player/data/jellyfinmediaplayer/logs/`
     - macOS: `~/Library/Logs/Jellyfin Media Player/`

**Describe the bug**
Chinese characters in ASS subtitles are displayed as squares. While using web client, providing a WOFF font using "Fallback font" fixes this, but not working on jellyfin-media-player.

**To Reproduce**
My ass subtitle: https://paste.ubuntu.com/p/CWmxKzqMw7/

**Expected behavior**
Screenshot on jellyfin web client:
![image](https://user-images.githubusercontent.com/37735580/139863391-a817b654-8094-4636-a2be-d9636dbc25b3.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/37735580/139863281-149927e6-f85d-4bf8-8e16-a7242cdef15d.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.5.2
 - Version: latest
 - Installation Method: dmg file

**Comment by leoleoasd** [comment]
Setting font through custom css doesn't work either
```css
@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+SC&display=swap');
.htmlvideoplayer::cue {
    font-family: 'Noto Sans SC', sans-serif;
}
```

above css works for srt subtitles on web client, but not on jellyfin media player.

**Comment by iwalton3** [comment]
MPV controls subtitle rendering. Maybe look into an MPV config?

**Comment by leoleoasd** [comment]
> MPV controls subtitle rendering. Maybe look into an MPV config?

Where do i put a `fonts.conf`? Same as `mpv.conf` mentioned in [here](https://github.com/jellyfin/jellyfin-media-player/blob/master/README.md#config-file-location)?

**Comment by leoleoasd** [comment]
Tried putting` fonts.conf` in `~/.config/mpv`, `~/.mpv`, `~/Library/Application Support/Jellyfin Media Player`, doesn't work. 
Srt subtitles seem to use `sans-serif` font. My `fonts.conf` (https://github.com/RobertYim/dotfiles/blob/master/DotFiles/.mpv/fonts.conf) should map it to `PingFang SC` which is a system CJK font provided by macOS. Don't know this issue is caused by incorrect `fonts.conf` or wrong path.

Setting fonts in ASS subtitles works (can use system font).

**Comment by iwalton3** [comment]
Does sub-font in mpv.conf work? https://askubuntu.com/questions/1330776/how-to-change-font-style-and-size-of-subtitles-in-celluloid

**Comment by leoleoasd** [comment]
> Does sub-font in mpv.conf work? https://askubuntu.com/questions/1330776/how-to-change-font-style-and-size-of-subtitles-in-celluloid

It works!
![image](https://user-images.githubusercontent.com/37735580/140006413-5c6fd08d-eabb-4bfb-aca4-b17e18555070.png)
![image](https://user-images.githubusercontent.com/37735580/140006492-8fc656f6-a356-49d2-b7c1-a967068d295c.png)
