### ISSUE TITLE
Adjust volume level with scroll wheel

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin-media-player#167]
**Is your feature request related to a problem? Please describe.**
MPV and VLC among other players offer support (if not default) for an option to enable altering the volume level using the scroll wheel (up and down). This feature is extremely convenient. It is less work, does not require precision with the mouse pointer as it can be executed by hovering anywhere over the player, and allow for more granular control (especially if, like with MPV, you can customize the volume level per stroke i.e. up = 2% volume increase). I would be very pleased to see this feature in Jellyfin Media Player.

**Comment by iwalton3** [comment]
This needs to be implemented in jellyfin-web

**Comment by Rybeusz100** [comment]
I'd also love to be able to scroll the timeline using the horizontal scroll wheel. Also a feature that VLC has by default

**Comment by sevenrats** [comment]
while the JMP project leaders do not mind feature requests for JMP in the bug tracker, as you feature request needs to be implemented in JF web, your feature request needs to be opened at features.jellyfin.org. Thank you!
