### ISSUE TITLE
Shortcut to change aspect ratio from default to zoom (Or anything). Or even better, a UI option to change while playing video.

### ISSUE THREAD

**Issue by Marctraider** [jellyfin/jellyfin-media-player#170]
Hi there! 

I'm running jellyfin media player on a ultrawide 3440x1440 screen.

It is a pretty common problem that some movies with a certain aspect ratio, and black bars encoded in the video, ultrawide has a problem of having black bars on each side of the screen (Both horizontal and vertical).

The aspect ratio fixes this sort of, by changing aspect ratio in client to zoom. But it would be better if there was an advanced menu in the player where you can do this on the fly when already watching the video rather than having to go through all the loops to change it (And obviously dont forget to change it back for videos that DONT have black bars encoded in them.

Unless there is a better solution? (Other players and hook them up to the jellyfin server, but in this case i might lose 'syncplay' feature?)

**Comment by nvllsvm** [comment]
Ideally, the Jellyfin server would expose video crop elements to the client (ex. [Matroska crop elements](https://www.matroska.org/technical/elements.html#PixelCropBottom)). I would then expect any client to respect these when direct streaming or for the server to crop when transcoding.

**Comment by Marctraider** [comment]
Actually you are right, I also see another problem now which didn't got obvious to me until now. Subtitles are now also half off-screen. :-(

**Comment by Ashyni** [comment]
Hello,  i also have an utlra wide display.
@Marctraider takes a look at https://github.com/Ashyni/mpv-scripts, it's a dynamic crop script for mpv.

I personally use it with Jellyfin mpv shim, but it also works with Jellyfin Media Player.

Create `mpv.conf` in `%localappdata%/JellyfinMediaPlayer` and add `script=C:\<any path you choosed>\dynamic-crop.lua` (assuming you are on Windows).

**Comment by Marctraider** [comment]
Thank you @Ashyni I will try your solution!

**Comment by iwalton3** [comment]
This will be in the next version.
