### ISSUE TITLE
Jellyfin Media Player flatpak fails to launch with Intel integrated graphics

### ISSUE THREAD

**Issue by SethFalco** [jellyfin/jellyfin-media-player#179]
**Describe the bug**
When I attempt to launch Jellyfin Media Player, it immediately exits.

**To Reproduce**
1. Install Jellyfin Media Player via Flatpak. ([Flathub](https://flathub.org/apps/details/com.github.iwalton3.jellyfin-media-player))
2. Execute `flatpak run com.github.iwalton3.jellyfin-media-player`
3. See error

**Expected behavior**
Jellyfin Media Player should open as normal and allow me to browse my library.

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 
 - Version: 11
 - Installation Method: Flatpak

**Additional context**
Output in terminal:
```
seth@seth-pc-tux:~$ flatpak run com.github.iwalton3.jellyfin-media-player 
QSocketNotifier: Can only be used with threads started with QThread
libpng warning: iCCP: known incorrect sRGB profile
Logging to /home/seth/.var/app/com.github.iwalton3.jellyfin-media-player/data/jellyfinmediaplayer/logs/jellyfinmediaplayer.log
[2:34:1222/154948.305366:ERROR:address_tracker_linux.cc(214)] Could not bind NETLINK socket: Address already in use (98)
Cannot load libcuda.so.1
```

The issue seems to be related to using Intel integrated graphics, or at least Intel® Iris® Xe Graphics on modern Intel CPUs. There are no reports with other Intel GPUs yet.

Logs:  
https://gist.github.com/SethFalco/9cfc321d9a7c04552acdaed83aff40ab

**Comment by MayeulC** [comment]
From your log:

> No space left on device

This could be a harmless warning, but do you have space left on your disks?

**Comment by SethFalco** [comment]
> This could be a harmless warning, but do you have space left on your disks?

Yup, I had 30~% free at the time that occurred. (304.9 GB / 981.3 GB available)

**Comment by bmreading** [comment]
This is also occurring for me on Fedora Linux 35 with the Flatpak from Flathub.

**Comment by dsychin** [comment]
Same here on Fedora 35

**Comment by SethFalco** [comment]
Now that I think about it, isn't `libcuda` an NVIDIA thing?
I'm on Intel integrated graphics (Intel® Iris® Xe Graphics), could that be related?

**Comment by dsychin** [comment]
Seems like it probably is. I am on Intel Core i7-1165G7 with Intel Iris Xe Graphics.

**Comment by SethFalco** [comment]
I think it's a fair assumption now, so I may rename the issue to:
"Jellyfin Media Player flatpak fails to launch with Intel integrated graphics"

I'll see if anyone else wants to confirm their specs first.

@bmreading May we know what GPU you have?

**Comment by bmreading** [comment]
> @bmreading May we know what GPU you have?

Sure. I'm on an Intel Core i5-1130G7 with integrated Intel Iris Xe graphics. This is part of a ThinkPad Nano X1 with Fedora 35.

**Comment by MayeulC** [comment]
FWIW, works for me on:
- Archlinux with an AMD R9 Fury, Mesa 21.3.5 (running under sway/wayland)
- Archlinux with Intel i5-7440HQ integrated HD Graphics 630 Mesa 21.3.5 (running under sway/wayland)
- Debian Buster with AMD Radeon Pro WX2100 mesa 20.3.5 (from backports) (running directly with xinit/Xorg)

The `libcuda` warning happens here as well, without any noticeable side effect.

**Comment by SethFalco** [comment]
Hmm, could be that I fixated too much on the log. 🤔 

Just seemed like a pretty solid lead since the 3 of us with the problem all have Intel Iris Xe Graphics.

**Comment by MayeulC** [comment]
It might help if others posted their logs as well. Nothing out of the ordinary from yours. `[ ERROR ] ComponentManager.cpp @ 45 - Failed to init component: display `  and `[ WARN  ] Log.cpp @ 35 - "QObject::connect(SettingsSection, Unknown): invalid nullptr parameter"` happens for me as well. Same errors for `lavrresample` and `LIRC`. My runtime version is the same as yours on my debian system.

One thing I could suggest -- try removing the  `~/.var/app/com.github.iwalton3.jellyfin-media-player` directory?

Was the flatpak installed as `--user`?

**Comment by SethFalco** [comment]
I tried deleting the directory, but hasn't made a difference.

And I installed it using:
```sh
flatpak install flathub com.github.iwalton3.jellyfin-media-player
```

**Comment by dsychin** [comment]
Here are my logs. 

Strangely enough if I keep trying to launch it, once in a while it does manage to launch.

I have added the log where it launched successfully as  the file named `success` in this gist.

https://gist.github.com/dsychin/34a367085660e98030c6b9435687ccfa

**Comment by dogtopus** [comment]
Same issue here. Flatpak version on Intel Xe graphics. There's nothing useful in the log nor on stderr. I did get a coredump but there's no symbol so no readable debug info either.

**Comment by dogtopus** [comment]
> It looks like if you update your flatpak packages, the issue is fixed now actually? Can anyone else try and report their findings?
> 
> The core issue might've been in a dependency / shared package maybe, not sure. But things are good for me so far.

Yup just tried it. Works for me now.

**Comment by dsychin** [comment]
It's working for me as well.

**Comment by SethFalco** [comment]
I'm going to close this.

I can confirm the fix appears to be here:
https://github.com/flathub/com.github.iwalton3.jellyfin-media-player/commit/381bd4a9c48d23c8aea964d7432958268404be45

I checked out the commit before (https://github.com/flathub/com.github.iwalton3.jellyfin-media-player/commit/abd1d1f8b67435fc2b9470bfa01252b9c5d4b6b7) which has the issue.

Then the latest commit which disables Wayland support resolves the issue. (Which is funny because I'm on Wayland.)
