### ISSUE TITLE
播放部分视频没有人声只有伴音，需要调整声道为stereo

### ISSUE THREAD

**Issue by bg4vrg** [jellyfin/jellyfin-media-player#181]
![image](https://user-images.githubusercontent.com/19301725/147195233-3775d83d-d265-4ca3-bd9d-a7b8a91a31d4.png)

无需重启程序，直接生效

**Comment by iwalton3** [comment]
I don’t maintain “Terminus Media Player”. Please report this to the developers of that forked application.
