### ISSUE TITLE
Syncplay visual bug :  HTML code of names when users leave\join syncplay is visible

### ISSUE THREAD

**Issue by Semelovich** [jellyfin/jellyfin-media-player#184]
Jellyfin version: 10.7.7
 
Theme: default, Dark

Jellyfin Media Player Version (windows): 1.6.1

When users join or leave SyncPlay  you get the message `"<b>User's name </ b>` has left the group"

Screenshot is attached.

![jellyfin media p;ayer bug](https://user-images.githubusercontent.com/53060549/147787849-84abb1b0-2672-47e8-abaa-bc590513e901.jpg)

**Comment by thornbill** [comment]
This is fixed in Jellyfin 10.8. There was a security issue that was fixed in 10.7.5 iirc that caused this, but because we do not backport translation changes in bugfix releases, this issue was not fixed at the same time.
