### ISSUE TITLE
Tried to use a self-signed SSL cert unsuccessfully. Removed it, but the client still has it cached and fails to connect.

### ISSUE THREAD

**Issue by mikfar** [jellyfin/jellyfin-media-player#188]
**Describe the bug**
I added a self-signed SSL cert for Jellyfin to my reverse proxy just for connecting locally (I have jelly.local on my local DNS). 
This ended up not working with the Android app and the desktop client, so I removed it. 

I noticed neither the Jellyfin Android app nor the this desktop player would connect anymore, even after removing the cert from the reverse proxy. Clearing the cache on the Android app fixed the issue. However, desktop client logs indicate that it's still trying to establish a https connection for some reason. I think it's possible the cert is still cached somewhere and I can't find how to remove it. I looked in ~/.local/share/jellyfinmediaplayer and couldn't find anything. 

I'm 99% certain this is a problem with the application because it was very similar on the Android app. 

**To Reproduce**
1. Add a self signed SSL cert to your reverse proxy. 
2. Remove it. 
3. The application still has this cert cached(?) and tries to establish an SSL connection., which will fail every time. 

**Expected behavior**
It should connect successfully over http now that the cert is removed from the reverse proxy and no longer causing issues on other applications. 

**Desktop (please complete the following information):**
 - Manjaro 
 - Media player 1.6.1-1
 - From AUR

**Comment by iwalton3** [comment]
Try looking in `~/.local/share/Jellyfin Media Player`

**Comment by mikfar** [comment]
> Try looking in `~/.local/share/Jellyfin Media Player`

So, I had no clue what I was looking at, but I went and completely removed both of the Jellyfin directories in ~/.local/share and reinstalled the application. The issue still persists, so the cert must be cached elsewhere.

**Comment by whiteowl3** [comment]
"Server's certificate does not match the URL.-200""
Has nothing to do with your local ca file.  The Server's certificate is signed for a CN other than it's url.

**Comment by mikfar** [comment]
Quote silly of me, but unsurprisingly, the culprit was in `~/.cache/Jellyfin Media Player`. I removed the directory and now it connects. 

I will let the maintainers decide if this cert caching should be considered a bug or worth fixing, but hopefully this helps anyone who encounters the same issue.
