### ISSUE TITLE
Include support for AV1 video codec

### ISSUE THREAD

**Issue by Extarys** [jellyfin/jellyfin-media-player#192]
**Is your feature request related to a problem? Please describe.**
AV1 video files only have audio - tested on linux with latest flatpak
`Jellyfin Media Player   com.github.iwalton3.jellyfin-media-player       1.6.1   stable  system`

AV1 video codec is more and more popular. Having a simple way to watch them on desktop is a must.

**Describe the solution you'd like**
Include a MPV version that supports AV1 video codec.

**Describe alternatives you've considered**
Not using the client. Desktop VLC and MPV app can play the file directly. Browsing on the NAS and opening such files manually works, but sadly it means Jellyfin won't track the progress.

**Additional context**
I believe I made a similar comment on the original repo a while back, (or was it on the matrix server :thinking: ) I believe it's a simple package missing in the flatpak file, but I'm not sure.

**Comment by iwalton3** [comment]
I think the latest version has this

**Comment by Extarys** [comment]
Thanks for the reminder, yes it's been working for a while now. Closing.
