### ISSUE TITLE
(v1.7.0-pre3) PS4 and WiiU controllers not working

### ISSUE THREAD

**Issue by HEPOSHEIKKI** [jellyfin/jellyfin-media-player#206]
**Describe the bug**
Controllers do not work

**To Reproduce**
1. Go to the dashboard
2. Click on 'controls'
3. Enable gamepad
4. Restart
5. Try using controller

**Expected behavior**
Controllers should work

**Logs:** 
[jellyfinmediaplayer5.log](https://github.com/jellyfin/jellyfin-media-player/files/7918019/jellyfinmediaplayer5.log)

**Desktop (please complete the following information):**
 - OS: Kubuntu 21.10 x86_64 
 - Kernel: 5.13.0-27-generic 
 - Installation Method: Debian package

**Comment by iwalton3** [comment]
You need to switch the client into TV display mode and then restart it for controllers to work. I don’t know if these specific controller types are supported though.

**Comment by HEPOSHEIKKI** [comment]
> You need to switch the client into TV display mode and then restart it for controllers to work. I don’t know if these specific controller types are supported though.

Fixed, thank you! Both controllers work now.
