### ISSUE TITLE
How could I make JMP to redirect to the base of my Organizr domain and not to the Jellyfin subpath ?

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [jellyfin/jellyfin-media-player#207]
Hi,

First, I need to say that I know nothing about Qt developpement or how JMP is made, so I'm just asking for info now.

I have an Organizr set up on the root of my domain, and my Jellyfin server is set on a /jellyfin subpath using Nginx as reverse proxy. JMP works perfectly when I enter [mydomain]/jellyfin. But on my server, I also have an Ombi server for requests. Atm, my users need to go to a web browser to access my full Organizr and request things on Ombi. But **I would like to know if it would be possible to make JMP redirect to my base domain instead of the Jellyfin subpath, so that my users can also make requests on Ombi from within JMP, without the need to go to a web browser, and still getting MPV playback working on Jellyfin**

Maybe what I'm asking is too complicated, but I don't know enough on the subject. Does anyone have infos on this ?

Thanks in advance for any answer, have a great day.

**Comment by iwalton3** [comment]
Multiple people have asked for this, but this just isn’t how the application is implemented. JMP has a built in web client which connects to one or more Jellyfin servers and also manages the list of servers. At no time does it ever load the web site associated with any Jellyfin server and the QT component doesn’t keep track of servers.
