### ISSUE TITLE
Spacebar doesn't play/pause the media

### ISSUE THREAD

**Issue by PadreToio** [jellyfin/jellyfin-media-player#21]
Sometimes when I press the spacebar when watching a video, especially after going fullscreen, it doesn't pause/resume, instead, I must use the mouse (double click) to pause/unpause.

Is there a fix?

**Comment by iwalton3** [comment]
This is a jellyfin-web problem.

**Comment by Darkwolf1515** [comment]
Works for me just fine

**Comment by jpmvferreira** [comment]
Space bar also doesn't seem to work for me, but using k does, so it doesn't really matter to me. 
This is valid with and without fullscreen.

I'm running Manjaro with i3 and jellyfin-media-player from the AUR.
