### ISSUE TITLE
Shared network folder support

### ISSUE THREAD

**Issue by mijofa** [jellyfin/jellyfin-media-player#210]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to have a local cache for some media. So I could, for example, have the system running jellyfin-media-player download the next episode of my shows overnight or once a week then I can watch them in jellyfin-media-player when ready, during peak internet traffic time.

**Describe the solution you'd like**
The best way I can think of to solve this is for jellyfin-media-player to support playing direct media from the "shared network folder" when available. Then I can mount that network folder with unionfs/aufs or something on the slower network and store the local cache in that.

**Describe alternatives you've considered**
I was thinking of doing a caching HTTP proxy and somehow precaching the media automatically, but it would have to be a rather intelligent caching proxy to handle caching with the authentication keys and such.

I can't think of any alternatives that wouldn't require some code/feature changes in jellyfin-media-player.
The caching feature could certainly be written directly into jellyfin-media-player, but I think it would make more sense (and simplify things) to just implement the more straight forward network folder support and let the caching stuff be handled externally.

**Comment by iwalton3** [comment]
This feature is available in Kodi and MPV Shim. It is fairly infamous for causing problems, so I would rather not add it unless someone else contributes an implementation.

**Comment by mijofa** [comment]
Fair enough, disappointing but not surprising.
Sad that the "shared network folder" isn't actually implemented in any clients, I think it's a great way to offload some of that handling to load-balancers and such, but is understandably complex.

Think I contributed some patches for this feature in MPV shim, so I might see about taking a look around in the code on this one, but family recently got a Google TV (with all it's built-in ads/etc 🙄) so am getting far less use out of this myself.

**Comment by iwalton3** [comment]
Yeah which as I said I am not opposed to merging the code if contributed. I just don't have such a file server set up and don't want to work out all the edge cases myself.
