### ISSUE TITLE
error playback failed with TV m3u file

### ISSUE THREAD

**Issue by emmerich38** [jellyfin/jellyfin-media-player#211]
Dear,
I use the Jellyfin media player for my movies without any issues even for HD movies;
I  added a TV m3u list from my internet provider (http://mafreebox.freebox.fr/freeboxtv/playlist.m3u).
Unfortunatly I have this message "playback failed" (picture joined).
On web browser I can see only low flow tv.
Thanks in advance for your help to see tv on jellyfin media player.
Best regards
Sébastien
![erreur_player](https://user-images.githubusercontent.com/98527542/151354546-c76d1ebc-5962-4a98-a9f8-44352165f3e9.JPG)

**Comment by emmerich38** [comment]
I also try "transcode" without succed

**Comment by sevenrats** [comment]
Hey there, thanks for your report. If you still require support, please stop by one of Jellyfin's chat support spaces and we will help you out.
