### ISSUE TITLE
Wiki: How to install on Linux

### ISSUE THREAD

**Issue by michael9dk** [jellyfin/jellyfin-media-player#212]
For linux newbies it would be nice to see how to install the deb package and its dependencies.
Here's my contribution to the wiki.

### How to install on Linux (Works with Ubuntu and Debian)

**Download the package.**
`wget "https://github.com/jellyfin/jellyfin-media-player/releases/download/v1.6.1/jellyfin-media-player_1.6.1-1_amd64-$(grep VERSION_CODENAME /etc/os-release | cut -d= -f2).deb" -O jmp.deb`
You can also download the package from [https://github.com/jellyfin/jellyfin-media-player/releases](https://github.com/jellyfin/jellyfin-media-player/releases).

**Install the package. (Includes dependencies)**
`sudo apt install ./jmp.deb`

**Delete the installation package.**
`rm jmp.deb`
 
### Other Options
 - [Flatpak](https://flathub.org/apps/details/com.github.iwalton3.jellyfin-media-player) - Works on all distributions 
 - [Arch Linux AUR](https://aur.archlinux.org/packages/jellyfin-media-player/) (Community Maintained)
 - [OpenSUSE](https://build.opensuse.org/package/show/home:playablepliable/jellyfin-media-player) (Community Maintained)
 - [Gentoo](https://packages.gentoo.org/packages/media-video/jellyfin-media-player) (Community Maintained)
 - [NixOS](https://search.nixos.org/packages?channel=21.11&show=jellyfin-media-player&from=0&size=50&sort=relevance&type=packages&query=jellyfin-media-player) (Community Maintained)

**Comment by iwalton3** [comment]
Added to Wiki here: https://github.com/jellyfin/jellyfin-media-player/wiki/Installing-on-Linux
