### ISSUE TITLE
Alllow connections to jellyfin host with custom CA signing

### ISSUE THREAD

**Issue by lbrunkho** [jellyfin/jellyfin-media-player#218]
I have a local jellyfin instance that uses my own CA cert for for SSL signing. Ive added my root cert to my systems trust and it appears that the jellyfin desktop client does not look for custom ca certs. Ive even tried making https optional in my reverse proxy as to allow http as a work-around for a similar issue with the android tv client but it appears that this client still tries to upgrade the connection to https and then errors out. 

It would be nice for either this client to look in the system trust for custom CA root certs or allow a place for me to add my own CA cert directly into the client. At least throw an error message so people know what the problem is and give them an option to continue anyways. 

Here is a snippet of the log with the relevant errors that are causing this issue. 
`2022-02-27 17:52:07 [ INFO  ] JS: begin connectToServer 
2022-02-27 17:52:07 [ INFO  ] JS: tryReconnect: https://HOSTNAME
2022-02-27 17:52:07 [ INFO  ] JS: getTryConnectPromise https://HOSTNAME
2022-02-27 17:52:07 [ INFO  ] JS: ConnectionManager requesting url: https://HOSTNAME/system/info/public 
2022-02-27 17:52:07 [ INFO  ] JS: fetchWithTimeout: timeoutMs: 20000, url: https://HOSTNAME/system/info/public 
[89731:89763:0227/175207.571551:ERROR:cert_verify_proc_nss.cc(977)] CERT_PKIXVerifyCert for HOSTNAME failed err=-8179
2022-02-27 17:52:07 [ DEBUG ] Log.cpp @ 29 - "qrc:/ui/webview.qml:218:onCertificateError: https://HOSTNAME/system/info/public :Server's certificate is not trusted.-202" 
2022-02-27 17:52:07 [ INFO  ] JS: fetchWithTimeout: timed out connecting to url: https://HOSTNAME/system/info/public 
2022-02-27 17:52:07 [ INFO  ] JS: ConnectionManager request failed to url: https://HOSTNAME/system/info/public 
2022-02-27 17:52:07 [ INFO  ] JS: Reconnect failed to https://HOSTNAME
2022-02-27 17:52:07 [ INFO  ] JS: connectToAddress https://HOSTNAME failed 
2022-02-27 17:52:07 [ DEBUG ] Log.cpp @ 29 - "qrc:/ui/webview.qml:178:onLoadingChanged: WebEngineLoadRequest starting: file:///usr/share/jellyfinmediaplayer/web-client/desktop/index.html#!/dialog?dlg=dlg1646013127579" 
`

For some additional information, the web version works just fine with the same URL and importing the CA cert in the browser works. Ive also got other desktop clients for different services that use ssl with the same signing CA and they look in the system trust and find this cert without error so I don't think this is a CA cert installation issue. 

Also the error message when this happens is not very informative that its a ssl verify issue... 
![image](https://user-images.githubusercontent.com/24943712/155912468-49124bdd-fc65-4f48-9c75-f7c110d1c8b1.png)

**Comment by tkafka** [comment]
+1, I have the same issue. Other apps usually have a checkbox on the URL screen to allow self-signed cartificates, I believe this would solve my problem.

**Comment by iwalton3** [comment]
There is a config file option to allow any certificate but it completely eliminates anti-mitm protection.

**Comment by viral32111** [comment]
> There is a config file option to allow any certificate

What's that option? I've tried setting `ignoreSSLErrors` to `true` in `%LOCALAPPDATA%/JellyfinMediaPlayer/jellyfinmediaplayer.conf` but the same error persists.

**Comment by 5cat** [comment]
> > There is a config file option to allow any certificate
> 
> What's that option? I've tried setting `ignoreSSLErrors` to `true` in `%LOCALAPPDATA%/JellyfinMediaPlayer/jellyfinmediaplayer.conf` but the same error persists.

for me on linux changing `ignoreSSLErrors` in `~/.local/share/jellyfinmediaplayer/jellyfinmediaplayer.conf` from `false` to `true` worked. The errors still appear in the logs but they are ignored.
I'm not sure what is on windows but the file is not the `toml` one but the `json` format one. since on linux there is also another file on `'~/.config/jellyfin/Jellyfin Media Player.conf'` that is in toml.

**Comment by viral32111** [comment]
Yeah I know about the two separate files, and the one at the path I posted is the JSON one.

I tried doing the same on a Linux install using your path, but nothing changed, the error still shows.

**Comment by AnonymousWebHacker** [comment]
> There is a config file option to allow any certificate but it completely eliminates anti-mitm protection.

since they have self-signed certificates that use ip:port :)

**Comment by viral32111** [comment]
I switched to an RSA certificate and this no longer happens for me. Guess it just doesn't like self-signed EC certificates?

**Comment by lbrunkho** [comment]
FYI, I'm able to connect to the Jellyfin server now by adding the ignoreSSLErrors = true in the config file but I'm still running into issue #301 on flatpak installed instances of JMP. 
The only way I'm able to currently get JMP to run with my system store ca certificate at all is to install it with system package manager (or build it) and to the workaround as mentioned above.

**Comment by lbrunkho** [comment]
I believe this issue is now resolved. JMP now looks for and accepts custom certificate authorities stored in the system cert store for both the natively and flatpak installed versions. 

Thanks all for getting this sorted! 

Closing...
