### ISSUE TITLE
Private, editable playlists and improved usability

### ISSUE THREAD

**Issue by Joshuasony** [jellyfin/jellyfin-media-player#220]
**Is your feature request related to a problem? Please describe.**
If there are multiple users connecting to the same server, they all share the playlists. After I found that out, I tried to rename a playlist, but couldn't. So editable playlists would be nice. Furthermore adding elements to playlists is cumbersome, because after adding something, I jump to the top of the screen and need to re-orientate where I was. 

**Describe the solution you'd like**
I would love to be able to:
- choose if a playlist is private or public (see youtube)
- edit the name of the playlist
- stay where I was after adding an element to the playlist

**Comment by iwalton3** [comment]
This feature request would fall under the jellyfin-web application and should not be posted here. (This client just embeds the web application interface.)

Please log the feature request over at: https://features.jellyfin.org/
