### ISSUE TITLE
[Automatic certificate creation]

### ISSUE THREAD

**Issue by Stratos-Crimson** [jellyfin/jellyfin-media-player#223]
Setting up an encrypted connection inside your home network is difficult without a domain name and if your ISP blocks all of your ports.

Automatic creation of a certificate like cockpit as an option

Creating a self signed certificate is quite difficult for someone who doesn't know much about the internet.

**Comment by thornbill** [comment]
This is not a request specific to the Jellyfin Media Player app so this is not the right place for it. Additionally Jellyfin as a project does not have interest in providing such functionality currently. It is virtually impossible for a project such as ours to generate _trusted_ certificates as the process to acquire a signing certificate is rather stringent.
