### ISSUE TITLE
Cannot connect over HTTPS

### ISSUE THREAD

**Issue by rigrig** [jellyfin/jellyfin-media-player#230]
**Describe the bug**
Jellyfin Media Player fails to connect to my server over HTTPS, displays
> Connection Failure
> We're unable to connect to the selected server right now. Please ensure it is running and try again.

* Connecting with a browser works fine
* Connecting over HTTP directly to the (internal) IP works fine
* The server is using a Let's Encrypt certificate  (i.e. not self-signed)

**To Reproduce**
1. Launch jellyfinmediaplayer
2. See "No servers have been found using the automatic server discovery."
3. Click on "Add server"
4. Host: "https://jellyfin.tubul.net"
5. Click on "Connect"
6. See error:
> Connection Failure
> We're unable to connect to the selected server right now. Please ensure it is running and try again.

**Expected behavior**
A succesfull connection

**Screenshot**
![image](https://user-images.githubusercontent.com/2941436/160573511-7a62a4c4-66a2-4425-8612-b51c1e5caedc.png)

**Desktop:**
 - OS: Linux Mint 20.3 Una
 - Version: v1.7.0 Prerelease 4 
 - Installation Method: jellyfin-media-player_1.7.0-pre4_amd64-focal.deb from GitHub release page

**Additional context**
Console log:
```
$ jellyfinmediaplayer
qt5ct: using qt5ct plugin
libpng warning: iCCP: known incorrect sRGB profile
Logging to /home/richard/.local/share/jellyfinmediaplayer/logs/jellyfinmediaplayer.log
[190423:190453:0329/104801.917515:ERROR:ssl_client_socket_impl.cc(1050)] handshake failed; returned -1, SSL error code 1, net_error -113
```
[jellyfinmediaplayer.log](https://github.com/jellyfin/jellyfin-media-player/files/8369730/jellyfinmediaplayer.log)

**Comment by jfml** [comment]
Not sure if this helps anyone but I had the same error message and it turns out I can sign in when using the baseurl (? that's what it's apparantly called, saw it in the Jellyfin for Kodi instuctions), so eg:

http://ip:port/jellyfin

instead of only IP and port

**Comment by AnonymousWebHacker** [comment]
It could be an nginx configuration problem when redirecting desktop clients , no error from Client Dektop

**Comment by jfml** [comment]
Adding to this since I seem to do it wrong time and time again:

When trying to figure out the right URL the player wants to have try not adding a trailing slash at the end, so

http://ip:port/jellyfin

instead of 

http://ip:port/jellyfin/

**Comment by AnonymousWebHacker** [comment]
@jfml You still have an nginx configuration problem, and it's not a problem with the jjellyfin client.

#  (jellyfin.example.org/jellyfin)
You are using this configuration https://jellyfin.org/docs/general/networking/nginx#nginx-with-subpath-exampleorgjellyfin

#  (jellyfin.example.org)
maybe you want this https://jellyfin.org/docs/general/networking/nginx#nginx-from-a-subdomain-jellyfinexampleorg

**Comment by jfml** [comment]
sure, maybe? not sure what nginx is, just know that it works for me without trailing slash …

**Comment by agittins** [comment]
Just ran into this with the windows client, running JF on a docker container behind Caddy. External web and android clients work fine, but the windows jellyfin client (v1.9.1 x64) gave the above error until trying without the trailing slash. I'm not sub-pathed, so it was just akin to `https://myurl.example.com:4433/` - removing the trailing slash allowed it to connect.

Caddyfile (equiv):
```
myurl.example.com {
    reverse_proxy jellyfin:8096
}
```

If the client only works with non-trailing-slash URLs then perhaps it could normalise the user input to accommodate that - or would that cause issues I'm unaware of?

Also I noticed after "fixing" the URL, if the wrong password is entered during login it gave the same error (I don't have concrete proof of this, I may have mis-read it at the time as I was remote-debugging, but I'm sure I remember the error being the same). It would seem the UI could offer a bit more diagnostic info, perhaps?

**Comment by stijnvankampen** [comment]
I have the same problem. Entering the URL with trailing slash doesn't work. 
https://jellyfin.domain.com/ doesn't work
https://jellyfin.domain.com does work

If you copy the URL from you browser it adds a traling slash, so I've some users of my Jellyfin server who reported that the client wasn't working properly. Running 1.9.1 x64 on Windows.

This problem doesn't seem to exist on the Android client.

**Comment by nothing2obvi** [comment]
I have the same problem. I can connect to the iOS apps just fine using https://jellyfin.mydomain.com but not on Jellyfin Media Player.

**Comment by nothing2obvi** [comment]
I have the same issue. I can connect on the iOS apps and the Android TV app, but not on Jellyfin Media Player.
