### ISSUE TITLE
Please provide armhf and arm64 builds (for Raspberry Pi)

### ISSUE THREAD

**Issue by stefansundin** [jellyfin/jellyfin-media-player#234]
**Is your feature request related to a problem? Please describe.**
I want to play media on my Raspberry Pi. Not only host a server, but also play the media on the TV that the Pi is connected to.

**Describe the solution you'd like**
Please provide armhf and arm64 `.deb` files in the release section, which work on Raspbian bullseye.

**Describe alternatives you've considered**
I followed the instructions in the README regarding building from source. It took a while but it worked. It is a bit laggy so maybe it didn't build with proper hardware decoding or something, but there were no errors in the build process as far as I could see.

**Additional context**
Even better would be to add jellyfin-media-player to the official Jellyfin apt repository (https://repo.jellyfin.org/). The packages that are there installed fine on my 64-bit Raspbian install.

**Comment by iwalton3** [comment]
Duplicates https://github.com/jellyfin/jellyfin-media-player/issues/71 and https://github.com/jellyfin/jellyfin-media-player/issues/171
