### ISSUE TITLE
[Issue]: Jellyfin Media Player saying "Google Cast not Supported"

### ISSUE THREAD

**Issue by Crazypersonalph** [jellyfin/jellyfin-media-player#238]
### Please describe your bug

The Windows x64 Jellyfin Media Player is saying, "Google Cast not Supported" when my ChromeCast is on. I do not have HTTPS enabled, as I do not have a custom domain. Browser casting doesn't work either.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Arch Linux (Server), Windows (Client)
- Virtualization:
- Clients: Browser, Jellyfin Media Player
- Browser: Brave (Chromium)
- FFmpeg Version: Latest Stable as of 20/04/2022
- Playback Method: I don't really know, either Transcode or Direct Play.
- Hardware Acceleration: x264
- Plugins:
- Reverse Proxy: I tried using nginx, didn't work
- Base URL: none
- Networking: Device on local network
- Storage: Local 1TB HDD.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thornbill** [comment]
This is not a bug. The message indicates that something about your current setup prevents Google Cast from being supported. This could be the app or browser you are using or a lack of https on your server. The message was added to let you know why your Cast devices are not showing up in the list.

In this particular case, Jellyfin Media Player does not support Google Cast.

Google Cast is only currently supported in the Android app (when installed from the Play Store or sideloading the proprietary build) and in Chrome (and possibly some other Chromium based browsers).

When accessing via a web browser, Google Cast also requires that your server is being accessed via a secure context (localhost or https with a valid SSL certificate from a **trusted authority**).

**Comment by coreybruce** [comment]
Will Google Cast be added for support in Jellyfin Media Player?

**Comment by DairyWeb3638077** [comment]
> 

Read the above message

**Comment by DairyWeb3638077** [comment]
> Will Google Cast be added for support in Jellyfin Media Player?

Read the above or below message

> This is not a bug. The message indicates that something about your current setup prevents Google Cast from being supported. This could be the app or browser you are using or a lack of https on your server. The message was added to let you know why your Cast devices are not showing up in the list.
> 
> In this particular case, Jellyfin Media Player does not support Google Cast.
> 
> Google Cast is only currently supported in the Android app (when installed from the Play Store or sideloading the proprietary build) and in Chrome (and possibly some other Chromium based browsers).
> 
> When accessing via a web browser, Google Cast also requires that your server is being accessed via a secure context (localhost or https with a valid SSL certificate from a trusted authority).

**Comment by Tequenikality** [comment]
> This is not a bug. The message indicates that something about your current setup prevents Google Cast from being supported. This could be the app or browser you are using or a lack of https on your server. The message was added to let you know why your Cast devices are not showing up in the list.
> 
> In this particular case, Jellyfin Media Player does not support Google Cast.
> 
> Google Cast is only currently supported in the Android app (when installed from the Play Store or sideloading the proprietary build) and in Chrome (and possibly some other Chromium based browsers).
> 
> When accessing via a web browser, Google Cast also requires that your server is being accessed via a secure context (localhost or https with a valid SSL certificate from a **trusted authority**).

How can you have a signed and trusted certificate for a local IP address? As far as I know, it's impossible. Based on what you're saying, it sound like Cast is only supported if you use a proxy, which I can confirm **is not** true, because I have that and Casting stops immediately - "playback stopped at 0ms". So are you saying Cast just doesn't work?

**Comment by avibrazil** [comment]
Μy Jellyfin server is accessible from the internet with HTTPS on port 443 (proxy to internal 8096) and a valid Let’s Encrypt certificate. Only IPv6 though, no IPv4; but this shouldn’t be a problem. Google DNS (8.8.8.8) is able to find my host name.

Even so, Jellyfin iOS app, Jellyfin server accessed over Safari or Google Chrome from my iPhone, say Chromecast not supported and my Chromecast device doesn’t appear on the list.

This is Jellyfin server 10.8.10 on Fedora Linux installed from its official RPMs.

How to fix?

thank you

**Comment by coreybruce** [comment]
> Μy Jellyfin server is accessible from the internet with HTTPS on port 443 (proxy to internal 8096) and a valid Let’s Encrypt certificate. Only IPv6 though, no IPv4; but this shouldn’t be a problem. Google DNS (8.8.8.8) is able to find my host name.
> 
> Even so, Jellyfin iOS app, Jellyfin server accessed over Safari or Google Chrome from my iPhone, say Chromecast not supported and my Chromecast device doesn’t appear on the list.
> 
> This is Jellyfin server 10.8.10 on Fedora Linux installed from its official RPMs.
> 
> How to fix?
> 
> thank you

This isn't related to this issue, please make a new issue post.
