### ISSUE TITLE
Jellyfin client to Smart TV Hisense with Vidaa OS 

### ISSUE THREAD

**Issue by AnonymousWebHacker** [jellyfin/jellyfin-media-player#250]
There are many customers who have smart TVs, which are not Android, and have Vidaa OS. How could the app be installed on that system?

## Related Issues
https://github.com/jellyfin/jellyfin-web/issues/1482
https://features.jellyfin.org/posts/1615/jellyfin-client-vidaa-os

I did a search on the internet, and I realized that Vidaa Os users are installing third-party applications.
It is not really installing the app, it seems that they are a web app, that the index is added and a name is given.

Maybe it will serve to create an APP for these devices

A video of how to do it
https://www.youtube.com/watch?v=4aIXCWD4pEA

### link related from other web apps
https://3751860294-2897431816.staging.foxxum.com/
https://3751860294-7655678632-dev.staging.foxxum.com/
https://srafapptest.staging.foxxum.com/
https://apptest.staging.foxxum.com/
http://6007903062.staging.foxxum.com/#fxm

**Comment by mwesten** [comment]
Would also really like a jellyfin app for VidaaOS.

**Comment by AnonymousWebHacker** [comment]
> Would also really like a jellyfin app for VidaaOS.

At the moment I haven't found the app for the TV, but the web client works. :)
Go to the browser, and in the address bar, put hisense: / debug and you will get a box to add a web app. you only need to add the ip or address of the server and its port

**Comment by Kalytis** [comment]
Highly seconded, a Vidaa app would be amazing.

Also I'm not exactly positive about relying on my TV's web browser for UX haha

**Comment by AlienSK1** [comment]
The only problem with this solution is that the result web app installed has not any icon that can be used to find it onto the main menu. If someone has the same problem tell me how he solved it.

**Comment by iwalton3** [comment]
This is not applicable to the Jellyfin Media Player application, which is a specific client for Windows, Linux, and macOS.

You may want to post this to https://features.jellyfin.org/

**Comment by AnonymousWebHacker** [comment]
Si fueras mas curioso, te dieras cuenta que te da la opcion de darla la ruta del icono. Pudiera ser ejemplo 127.0.0.1:8096/web/src/logo.png


>  El único problema con esta solución es que la aplicación web resultante instalada no tiene ningún ícono que pueda usarse para encontrarla en el menú principal. Si alguien tiene el mismo problema que me diga como lo soluciono.

**Comment by AlienSK1** [comment]
> Si fueras mas curioso, te dieras cuenta que te da la opcion de darla la ruta del icono. Pudiera ser ejemplo 127.0.0.1:8096/web/src/logo.png

Yeah, i noticed that you can assign a path for the icon, but the problem is that i don't know where is located the icon.

**Comment by AnonymousWebHacker** [comment]
> > Si fueras mas curioso, te dieras cuenta que te da la opcion de darla la ruta del icono. Pudiera ser ejemplo 127.0.0.1:8096/web/src/logo.png
> 
> Yeah, i noticed that you can assign a path for the icon, but the problem is that i don't know where is located the icon.

If you are using linux , you can look in `/usr/share/jellyfin/web/` or `/usr/share/jellyfin/web/assets/`

Via web, you can reach those logos and png, it would be for example `http://127.0.0.1:8096/web/assets/img/banner-light.png`

**Comment by Jowey2k** [comment]
> > Would also really like a jellyfin app for VidaaOS.
> 
> At the moment I haven't found the app for the TV, but the web client works. :) Go to the browser, and in the address bar, put hisense: / debug and you will get a box to add a web app. you only need to add the ip or address of the server and its port

I found something which I'm yet to test at https://www.avforums.com/threads/vidaa-apps.2295402/

They mention getting the "HiSense RemoteNow app" to help type URLs etc, then creating an "app" icon using the debug.

1. open on TV stock browser
2. in the address bar, type hisense://debug
3*. on the page type the name of the application and its URL
4. find the application icon in Google. copy and paste the url of the icon
5. Click the INSTALL button
6. can use the app

**Comment by Kalytis** [comment]
For people wanting to support this idea on Jellyfin Features Request : https://features.jellyfin.org/posts/1615/jellyfin-client-vidaa-os

**Comment by lourensdev** [comment]
@AnonymousWebHacker I tried giving it a shot and contacted VIDAA. In their response they mentioned that to get access to the developer documentation and access to the portal you need to sign a contract and pay an annual fee $1000. Which is probably unlikely to happen for an open source project, unless they have some sort of financial backing or a generous donor. I'd be willing to get the app going if we can get access.

It's also worth noting that when I messaged them they mentioned having been contacted before by someone but then never heard back from them again.

**Comment by Kalytis** [comment]
Thanks for contacting them!

> to get access to the developer documentation and access to the portal you need to sign a contract and pay an annual fee $1000

That would imply running a yearly campaign just for that... could be hard for Jellyfin yeah. (let aside philosophical issues about paying to join an app store)

> It's also worth noting that when I messaged them they mentioned having been contacted before by someone but then never heard back from them again.

no shit if they were asked to pay 1k to join the app store haha

**Comment by lourensdev** [comment]
Good news! There might be some hope. I asked if there was another solution we could pursue since Jellyfin is an open source app, they just got back to me with a DDA (Developer Distribution Agreement) which means there will be no costs. I'm going to read through the agreement and see. @joshuaboniface they mentioned you by name as the previous person they were in contact with. Let me know if you are happy for me to pursue or if you would like to talk about it before anything gets signed

**Comment by Kalytis** [comment]
Law graduate & PhD candidate in digital law here, let me know if there's anything I can do to help :wave: Good luck and thanks !

**Comment by thornbill** [comment]
Someone from Vidaa actually reached out to us. We (Josh) voiced concerns about licensing and their NDA and afaik we never heard anything after that.

**Comment by lourensdev** [comment]
@thornbill That is rather concerning. Here is [the agreement](https://drive.google.com/file/d/1XNkkFSL7w_-_c7sl-QH4LqZ8M8ICekFR/view?usp=sharing) they sent me if you guys want to give it a read. cc @Kalytis

**Comment by Kalytis** [comment]
I don't see anything outrageous in the agreement. It's Jellyfin's arbitration to make whether to join or not Vidaa.

**Comment by msimic** [comment]
Any new info regarding this?
Hisense is becoming a major TV brand, and Jellyfin is pretty much a no go in them. Manual fiddling with the browser to access the web client is not an option for most users.

**Comment by Kalytis** [comment]
I'd take part of a crowdfunding to pay for their licence, so that Jellyfin could publish their app.

**Comment by thornbill** [comment]
This request has nothing to do with Jellyfin Media Player. It would require an entirely new client to be written (likely similar to webOS and Tizen). Any further discussion should happen in the feature request here: https://features.jellyfin.org/posts/1615/jellyfin-client-vidaa-os

**Comment by Hussain82** [comment]
> > > Would also really like a jellyfin app for VidaaOS.
> > 
> > 
> > At the moment I haven't found the app for the TV, but the web client works. :) Go to the browser, and in the address bar, put hisense: / debug and you will get a box to add a web app. you only need to add the ip or address of the server and its port
> 
> I found something which I'm yet to test at https://www.avforums.com/threads/vidaa-apps.2295402/
> 
> They mention getting the "HiSense RemoteNow app" to help type URLs etc, then creating an "app" icon using the debug.
> 
> Maybe your Jellyfin browser URL might work in there?
> 
> 1. open on TV stock browser
> 2. in the address bar, type hisense://debug
>    3*. on the page type the name of the application and its URL
> 3. find the application icon in Google. copy and paste the url of the icon
> 4. Click the INSTALL button
> 5. can use the app

--
I installed app by this method by I cannot press sign-in
![17114785740103642502160128247261](https://github.com/jellyfin/jellyfin-media-player/assets/8213902/1d382f0a-a2eb-425f-97a4-6f421743358f)
 Any one had same problem?

**Comment by AnonymousWebHacker** [comment]
Be careful, if you update to the latest 2 versions of jellyfin-server and jellyfin-web, it will no longer be possible to access it on Hisense TV. I hope that soon someone will deign to make an app

**Comment by Kalytis** [comment]
@lourensdev said that he was working on it : https://features.jellyfin.org/posts/1615/jellyfin-client-vidaa-os

**Comment by mcmcelro** [comment]
> Good news! There might be some hope. I asked if there was another solution we could pursue since Jellyfin is an open source app, they just got back to me with a DDA (Developer Distribution Agreement) which means there will be no costs. I'm going to read through the agreement and see. @joshuaboniface they mentioned you by name as the previous person they were in contact with. Let me know if you are happy for me to pursue or if you would like to talk about it before anything gets signed

Am I correct in assuming that you've presented yourself as some sort of representative for Jellyfin? That's probably not ideal, legally speaking.

**Comment by abdulmueid** [comment]
Hey everyone,

I have a Hisense Vidaa TV and would like to share some updates:

1. Current stable jellyfin-web 10.9.11 navigates properly using a remote when installed with hisense://debug. I have posted a full write-up about installation [here](https://thecodeninja.net/2024/09/jellyfin-on-hisense-vidaa/)
2. HEVC playback is coming in 10.10 ([PR Merged](https://github.com/jellyfin/jellyfin-web/pull/6135))
3. HDR10 / Dolby Vision support is coming too [(PR Opened)](https://github.com/jellyfin/jellyfin-web/pull/6229)

Some notes:
1. Hisense browser / installed webapp does not like MKV and fMP4-HLS containers.
2. HEVC in MKV container is glitchy and fails to play with fMP4 container (disable fMP4 in Settings -> Playback -> Prefer fMP4-HLS).
3. Jellyfin correctly remuxes HEVC SDR/HDR/DV with MPEG-TS container (the PRs above make it work).

**Comment by SoCuul** [comment]
> Hey everyone,
> 
> 
> 
> I have a Hisense Vidaa TV and would like to share some updates:
> 
> 
> 
> 1. Current stable jellyfin-web 10.9.11 navigates properly using a remote when installed with hisense://debug. I have posted a full write-up about installation [here](https://thecodeninja.net/2024/09/jellyfin-on-hisense-vidaa/)
> 
> 2. HEVC playback is coming in 10.10 ([PR Merged](https://github.com/jellyfin/jellyfin-web/pull/6135))
> 
> 3. HDR10 / Dolby Vision support is coming too ([PR Opened](https://github.com/jellyfin/jellyfin-web/pull/6229))
> 
> 
> 
> Some notes:
> 
> 1. Hisense browser / installed webapp does not like MKV and fMP4-HLS containers.
> 
> 2. HEVC in MKV container is glitchy and fails to play with fMP4 container (disable fMP4 in Settings -> Playback -> Prefer fMP4-HLS).
> 
> 3. Jellyfin correctly remuxes HEVC SDR/HDR/DV with MPEG-TS container (the PRs above make it work).

Which version of Vidaa is installed on your TV?

**Comment by abdulmueid** [comment]
> Which version of Vidaa is installed on your TV?

Vidaa U4.4
Firmware version M0822
TV model is 55U7QF

**Comment by Crissov** [comment]
People stranded here looking for a solution should probably watch [lourensdev/jellyfin-vidaa](https://github.com/lourensdev/jellyfin-vidaa) for updates. (In the meantime, hacks like [VidaaEdge](https://vidaa.flummi.ch/documentation/hosted) might work for you.)

**Comment by simonbuehler** [comment]
Hi guys,

after a deep dive into the Vidaa system internals, I can now share my minimal findings - and honestly, there are some surprisingly wide-open doors in this whole setup ... 

but it boils down to this - you can add jellyfinn as a browser app using this method:

```js
// Jellyfin App Installer for VIDAA OS
// ------------------------------------------------------------
// HOW TO USE:
// 1. Replace all <YOUR_JELLYFIN_SERVER> placeholders with your actual server URL.
//    Example: http://192.168.x.x:8096
// 2. This script MUST be hosted on vidaahub.com (for example via Pi-hole or local DNS override).
//    The required HiUtils_* JavaScript functions are only available in the browser
//    context when the page is served from vidaahub.com.
// ------------------------------------------------------------

(function() {
    // Try to read the existing app list from system storage
    const current = HiUtils_createRequest('fileRead', {
        path: 'websdk/Appinfo.json',
        mode: 6
    });

    // Parse JSON if it exists, otherwise create an empty structure
    const apps = current.ret ? JSON.parse(current.msg) : { AppInfo: [] };

    // Define the Jellyfin app entry
    const jellyfin = {
        Id: "jellyfin-web",
        AppName: "Jellyfin",
        Title: "Jellyfin",
        URL: "http://<YOUR_JELLYFIN_SERVER>/web",
        StartCommand: "http://<YOUR_JELLYFIN_SERVER>/web",
        IconURL: "http://<YOUR_JELLYFIN_SERVER>/web/favicon.ico",
        Icon_96: "http://<YOUR_JELLYFIN_SERVER>/web/favicon.ico",
        Image: "http://<YOUR_JELLYFIN_SERVER>/web/touchicon.png",
        Thumb: "http://<YOUR_JELLYFIN_SERVER>/web/touchicon.png",
        Type: "Browser",
        InstallTime: new Date().toISOString().split('T')[0],
        RunTimes: 0,
        StoreType: "custom",
        PreInstall: false
    };

    // Update existing entry or add a new one
    const index = apps.AppInfo.findIndex(a => a.Id === jellyfin.Id);
    if (index >= 0) {
        apps.AppInfo[index] = jellyfin;
    } else {
        apps.AppInfo.push(jellyfin);
    }

    // Write the updated list back to the system file
    return HiUtils_createRequest('fileWrite', {
        path: 'websdk/Appinfo.json',
        mode: 6,
        writedata: JSON.stringify(apps)
    });
})();
```
Restart TV (clear cache for apps is probably the fastest way), enjoy!

**Comment by CelianGdfrd** [comment]
Been using this way for the better part of a year now. Works kinda well. In my experience, clearing cache removes custom apps. Plus, I think browser apps can't go over 1080p in resolution -- shame, when Jellyfin allows for 4k media.

**Comment by SoCuul** [comment]
> Hi guys,
> 
> after a deep dive into the Vidaa system internals, I can now share my minimal findings - and honestly, there are some surprisingly wide-open doors in this whole setup ... 
> 
> but it boils down to this - you can add jellyfinn as a browser app using this method:
> 
> ```js
> // Jellyfin App Installer for VIDAA OS
> // ------------------------------------------------------------
> // HOW TO USE:
> // 1. Replace all <YOUR_JELLYFIN_SERVER> placeholders with your actual server URL.
> //    Example: http://192.168.x.x:8096
> // 2. This script MUST be hosted on vidaahub.com (for example via Pi-hole or local DNS override).
> //    The required HiUtils_* JavaScript functions are only available in the browser
> //    context when the page is served from vidaahub.com.
> // ------------------------------------------------------------
> 
> (function() {
>     // Try to read the existing app list from system storage
>     const current = HiUtils_createRequest('fileRead', {
>         path: 'websdk/Appinfo.json',
>         mode: 6
>     });
> 
>     // Parse JSON if it exists, otherwise create an empty structure
>     const apps = current.ret ? JSON.parse(current.msg) : { AppInfo: [] };
> 
>     // Define the Jellyfin app entry
>     const jellyfin = {
>         Id: "jellyfin-web",
>         AppName: "Jellyfin",
>         Title: "Jellyfin",
>         URL: "http://<YOUR_JELLYFIN_SERVER>/web",
>         StartCommand: "http://<YOUR_JELLYFIN_SERVER>/web",
>         IconURL: "http://<YOUR_JELLYFIN_SERVER>/web/favicon.ico",
>         Icon_96: "http://<YOUR_JELLYFIN_SERVER>/web/favicon.ico",
>         Image: "http://<YOUR_JELLYFIN_SERVER>/web/touchicon.png",
>         Thumb: "http://<YOUR_JELLYFIN_SERVER>/web/touchicon.png",
>         Type: "Browser",
>         InstallTime: new Date().toISOString().split('T')[0],
>         RunTimes: 0,
>         StoreType: "custom",
>         PreInstall: false
>     };
> 
>     // Update existing entry or add a new one
>     const index = apps.AppInfo.findIndex(a => a.Id === jellyfin.Id);
>     if (index >= 0) {
>         apps.AppInfo[index] = jellyfin;
>     } else {
>         apps.AppInfo.push(jellyfin);
>     }
> 
>     // Write the updated list back to the system file
>     return HiUtils_createRequest('fileWrite', {
>         path: 'websdk/Appinfo.json',
>         mode: 6,
>         writedata: JSON.stringify(apps)
>     });
> })();
> ```
> Restart TV (clear cache for apps is probably the fastest way), enjoy!

Does the TV not care about the TLS certificate being completely messed up with the DNS hijacking?

**Comment by simonbuehler** [comment]
> Does the TV not care about the TLS certificate being completely messed up with the DNS hijacking?

the idea is to have your own express/whatever server running on your dev machine with a self-signed certificate, so there is just a "want to continue" popup in the tv browser app

**Comment by simonbuehler** [comment]
> Been using this way for the better part of a year now. Works kinda well. In my experience, clearing cache removes custom apps. Plus, I think browser apps can't go over 1080p in resolution -- shame, when Jellyfin allows for 4k media.

If I read the code correctly, it's even worse: scaled by 1.5 so only 720 effective 😞 
check https://browsersize.com/ in your tv browser app

**Comment by agorgl** [comment]
@simonbuehler
I've used the new method you found in https://github.com/PhasedGapple/HiZ-Store/issues/1#issuecomment-3441402418 and is integrated in the latest [vidaa-edge](https://github.com/weinzii/vidaa-edge) in a friend's TV and it seems to work almost fine.

So far my problems are only the following 2:
- The resolution in the installed PWA seems to be really low (either 720p or 1080p) in relation to the max supported resolution by the TV (4k). Seeing screenshots from the old `Hisense_installApp` method, the `hisense://debug` panel had a drop down that you could choose either 720 or 1080 as a resolution, so I believe this could be configurable by some hidden api as well. Launching the TV browser and going to the Jellyfin page, the resolution is higher than the PWA (but still blurry) so I *think* that the PWA installs with 720p resolution and the default TV browser tab resolution is 1080p
- The 'back' button in the remote does not work at all in the PWA but it does work when using jellyfin from the browser (but the rest of the navigation is painful there)

Can you maybe dump your `Appinfo.json` to check if it has fields related to the resolution / back button policy in other apps (netflix?) in order to configure them too in vidaa-edge?

Related: https://github.com/weinzii/vidaa-edge/issues/26, https://github.com/weinzii/vidaa-edge/issues/25

**Comment by agorgl** [comment]
@simonbuehler 
Also, given that the Hisense `Appinfo.json` might be 'inspired' by the LG webOS `appinfo.json`, could you try blindly testing/writing some extra attributes like `"resolution": "1920x1080"` (taken from: https://github.com/webOS-TV-app-samples/Resolution/blob/main/appinfo.json#L9)  and `"disableBackHistoryAPI": false` (taken from: https://github.com/webOS-TV-app-samples/MediaPlayback/blob/main/appinfo.json#L9), (maybe with different capitalization too?) to a sample Jellyfin app entry to see if that affects anything of the above?

(I would try it myself but I don't have access to my friend's house :))
