### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by aivit** [jellyfin/jellyfin-media-player#252]
**Describe the bug**
Bruh, weird scrolling. Can't even explain. The app is just... slow
See video
https://youtu.be/xNoUQKnYwxs

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version v1.7.0 Prerelease 4
 - Installation Method dmg

**Comment by sevenrats** [comment]
If you still experience this issue on a supported version of JMP, please make sure your report is specific, actionable, and includes your architecture.

**Comment by lukaslindnermusic** [comment]
I had the same issue. Solution: Add custom css in your admin dashboard under General -> Custom CSS Code (or on a per client basis: Your profile icon on the top right -> Display -> Custom CSS code).

Add the following code:
body{ overscroll-behavior: none; }

You're welcome :)

**Comment by lukaslindnermusic** [comment]
And while you're there, you can also add this (if you use the dark theme):

#nowPlayingPage .remoteControlContent.padded-left.padded-right.padded-bottom.hideVideoButtons .nowPlayingInfoContainer {
    position: sticky;
    top: 0px;
    background-color: #101010;
    border-top: 65px solid #101010;
    margin-top: -65px;
    z-index: 10;
}


this ensures that audio controls in the now playing view stay on top if you scroll down the queue :) 

Best, Lukas :)
