### ISSUE TITLE
feature request: closed caption shortcut

### ISSUE THREAD

**Issue by jp8311** [jellyfin/jellyfin-media-player#253]
I'm struggling to find documentation around the Shortcut/keyboard mapping that jellyfin uses. Searches in the forums shows largely a shared system with YouTube shortcuts, and I've inferred that you have implemented further media control support on top of that.

Using these I've made a semi functional remote, but I would love to know if more support for the otherwise abled could be implemented.

Currently to turn on subtitles you must navigate to the button which brings up a fullscreen splashscreen. While much nicer than kodi's cycle through and hope you don't go past your language, they have implemented a hot key support for both cycling closed captions and turning them on and off.

I have already accessed the option in the menu for default closed caption behaviour, but on some media (especially older media, but often foreign language media and Netflix releases) the captions are not labelled as standard and require navigating the menu.

I have no idea if this feature request is possible, but it is sorely missed from kodi in my family currently.

You may be aware, but shortcut support is really important for the vision impaired also, as it enables them to use remotes with braille buttons and map voice control assistants that otherwise require hacky solutions. I want to mention this so I can thank you for your current efforts in prioritising short cut support.

**Comment by sevenrats** [comment]
Hi! Because the feature you are requesting needs to be implemented in jellyfin-web (the ui component inside JMP) you need to open this feature request at features.jellyfin.org
As is, it can't be implemented here.  Thank you!
