### ISSUE TITLE
Display speed changes on the screen when using short cuts [ < or > + shift  ] 

### ISSUE THREAD

**Issue by YoungOnef** [jellyfin/jellyfin-media-player#257]
**Is your feature request related to a problem? Please describe.**
Not being able to see what playback speed is 

**Describe the solution you'd like**
It should contain a playback option in the player and display speed changed on the screen when using [ < or > + shift  ] short cuts 

**Describe alternatives you've considered**
I have no alternative to this feature or improvement

**Comment by sevenrats** [comment]
Hi! Thanks for your feature request. Because you are requesting a change to jellyfin-web, the ui component inside JMP, this feature request needs to be opened at features.jellyfin.org
Thanks!
