### ISSUE TITLE
v1.7.0 crashes on startup (macOS)

### ISSUE THREAD

**Issue by nvllsvm** [jellyfin/jellyfin-media-player#259]
**Describe the bug**
-  v1.7.0 crashes on startup (macOS). 
- v1.7.0 prerelease 4 does not crash.

**To Reproduce**
- Install v1.7.0
- Attempt to start.
- Crash. 

**Error Report**
[report.log](https://github.com/jellyfin/jellyfin-media-player/files/8884476/report.log)

**Screenshots**
![Screen Shot 2022-06-11 at 1 42 09 PM](https://user-images.githubusercontent.com/6550543/173199331-15afe452-8b81-422b-8451-fbbbf25f085e.png)

**Comment by iwalton3** [comment]
Update it sounds like my CI build works: https://github.com/jellyfin/jellyfin-media-player/discussions/258#discussioncomment-2929729

**Comment by iwalton3** [comment]
Update here is the signed and fixed version: https://github.com/jellyfin/jellyfin-media-player/releases/download/v1.7.0/JellyfinMediaPlayer-1.7.0-macos.dmg
