### ISSUE TITLE
I can't exit fullscreen

### ISSUE THREAD

**Issue by buzzard10** [jellyfin/jellyfin-media-player#260]
**Describe the bug**
I don't know why but after i open Jellyfin media player app in windows 11, i have app in FULLSCREEN and i can't exit with escape or F11. I'm not talking about fullscreen when playing movie. The whole app is in fullscreen from the beginning, even when i'm looking on list of movies.

**To Reproduce**
I don't know how to reproduce this issue. I just launched application and it was in fullscreen. It worked yesterday without issues.

**Expected behavior**
It should be a standard applicaiton in window with frames 

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11
 - Installation Method windows installer

**Comment by buzzard10** [comment]
I found this - it's related FOR SURE: https://www.plageroyale.com/p/jellyfin/comments/ugjod0/jellyfin_media_player_on_pc_is_stuck_in_fullscreen/

**Comment by DexLuther** [comment]
The github link for convenience instead of 3rd party site: [Stuck in full screen #94](https://github.com/jellyfin/jellyfin-media-player/issues/94)

**Comment by buzzard10** [comment]
There is a problem after computer shutdown while watching movie in fullscreen

**Comment by iwalton3** [comment]
duplicates https://github.com/jellyfin/jellyfin-media-player/issues/94
