### ISSUE TITLE
Can't launch Windows x64 installer

### ISSUE THREAD

**Issue by midcorestudios** [jellyfin/jellyfin-media-player#264]
**Describe the bug**

Unable to open Windows x64 installer

**To Reproduce**

1.  Double click to run
2.  Right click and install as admin

*Expected behavior**
I had expected to see the installer.  When I double click nothing happens.  There are no installer processes running, and no logs are generated.  I have downloaded it several times to make sure it wasn't a failed download package

 - OS: Windows 10

**Comment by midcorestudios** [comment]
I am experiencing the same issue with the 1.7.1 installer as well, however i can still run the 1.6.1 installer

**Comment by iwalton3** [comment]
I wonder if the newer CI broke something. Are you missing a Windows 10 feature update or something?

The x64 installer definitely installs inside my Windows 10 VM.

**Comment by midcorestudios** [comment]
I thought I had everything up to date...let me run the updates again and i'll follow up

**Comment by midcorestudios** [comment]
Ok, got it working.  Turns out I had to log in as a local admin, it doesn't seem to like being installed on a network login
