### ISSUE TITLE
SyncPlay not working

### ISSUE THREAD

**Issue by ThomasPGH** [jellyfin/jellyfin-media-player#269]
First I thought this is a new bug in Jellyfin 10.8.0 but then I realised that I started to use the Jellyfin Media Player (Windows 10) around the same time when I upgraded Jellyfin itself.

SyncPlay does not work in the media player for Windows 10. After clicking on the SyncPlay button and joining a group the player is not usable anymore. There's no "Not responding" title bar but no click or button works. The only way to get out of this is to close the player and start it again.

**Comment by ThomasPGH** [comment]
When a new group is created with the Jellyfin Media Player and a browser joins, the content does not play in the browser. However, the browser is still usable, as opposed to when the group is started in the browser and the media player joins.

**Comment by iwalton3** [comment]
I just did a test and it is working for me. I will need more information to troubleshoot this.

**Comment by ThomasPGH** [comment]
Thanks. This was helpful because it made me realise that it's got to be something here then. I restarted the Jellyfin server and it is working again now (no non-responding Jellyfin Media Player anymore).

However, SynchPlay still seems to be doing its own thing because it sometimes works and sometimes doesn't. It even starts playing random stuff when started. I'll try to investigate more and hope I can find a reproducible pattern.

**Comment by iwalton3** [comment]
SyncPlay is very brittle. I would love for it to improve but the code is extremely prone to strange edge cases that are a total pain to test unfortunately.

**Comment by ThomasPGH** [comment]
I think I found the pattern. It's the external network, in my case via a reverse proxy.

Apart from starting seemingly random content SynchPlay works on the internal network. It does not work from the outside, and it is irrelevant which client is used. I couldn't see this earlier because only inside a browser is the server's address easily seen.

So, this most likely is a Jellyfin issue that affects all clients (I tested with Firefox, Jellyfin on Windows, and iPhone client).

**Comment by iwalton3** [comment]
Is your reverse proxy forwarding websocket connections correctly? A good way to test is to try casting to a client connected through the reverse proxy.

**Comment by ThomasPGH** [comment]
Thanks again. I can cast from outside clients to internal ones but not the other way round.

**Comment by iwalton3** [comment]
Yup, that sounds like a broken websocket connection to me!

**Comment by ThomasPGH** [comment]
It's only these two lines in the Apache config that are relevant for the websocket, isn't it?

    ProxyPass "/socket" "ws://SERVER_IP_ADDRESS:8096/socket"
    ProxyPassReverse "/socket" "ws://SERVER_IP_ADDRESS:8096/socket"

They are in the config and look correct to me when I campare them to these:

    ProxyPass "/" "http://SERVER_IP_ADDRESS:8096/"
    ProxyPassReverse "/" "http://SERVER_IP_ADDRESS:8096/"

**Comment by ThomasPGH** [comment]
ProxyPass "/socket" "ws://SERVER_IP_ADDRESS:8096/socket"
ProxyPassReverse "/socket" "ws://SERVER_IP_ADDRESS:8096/socket"

Yes, according to the Apache documentation this is definitely wrong for https servers.

**Comment by ThomasPGH** [comment]
By playing around a bit I managed to get the Jellyfin server again in the state mentioned at the top were Jellyfin Media Player doesn't respond anymore. A server restart fixed it again. I'll try to get the configuration right first before I carry on trying. :)

**Comment by ThomasPGH** [comment]
I solved it:
ProxyPass "/socket" "wss://...

Additionally, proxy_wstunnel wasn't installed.

Thanks for the help!
