### ISSUE TITLE
[1.7.0] Playing the wrong audio track when external subtitles are loaded in multi audio mkv.

### ISSUE THREAD

**Issue by gummykage** [jellyfin/jellyfin-media-player#271]
**Describe the bug**
Movie file with:
Video Track
Audio Track
Audio Track - Commentary
SRT Subtitle track
External Subtitle track

When the folder contains the external subtitle track file, the audio tracks are confused, First listed track with name plays the 2nd audio track, the Second listed Audio track plays the first Audio track. As a result the movie plays the commentary even though it displays its playing the default primary audio track.

This problem only appears in the Jellyfin Media Player, when playing through a web browser such as chrome this issue does not happen.

**To Reproduce**
1.) Place movie with video, audio, audio, and embeded subtitle.
2.) Play movie, try audio 1 - works, try commentary audio 2, works properly.
3.) Add External Subtitle to folder,
4.) Refresh all metadata.
5.) Observe the new subtitle track is now loaded.
6.) Select external subtitle track, and primary audio track.

Wrong audio track 2 will play... You can manually swap it, this a cosmetic issue as you can work around by trying the other track. But its annoying because if you select the external subtitle track the wrong audio track may play be default.

**Expected behavior**
Audio track listed is played properly.

**Screenshots**

**Desktop (please complete the following information):**
 - Installation Method [e.g. windows installer]

**Additional context**

**Comment by iwalton3** [comment]
I have reproduced this issue and will hotfix asap to get it working again. (This happened because the semantics around subtitles changed in the latest Jellyfin server, to fix strm file support of all things...)

**Comment by iwalton3** [comment]
Fix is in master, and this will be fixed in the next hotfix.

**Comment by iwalton3** [comment]
This is fixed in v1.7.1.

**Comment by gummykage** [comment]
@iwalton3 Wanted to say a huge thank you, I had actually started remuxing some of my movies with ffmpeg and running a nightly build of the server to see if the problem was somewhere else. It was quite irritating. Thank you for pushing this so quickly! I turned to JFmp and promoted it to everyone after realizing some movies just have issues playing in chrome and freeze no matter what i tried. I hope I can contribute to this awesome project in the near future.

**Comment by mikewesten** [comment]
There's still issues with this feature in v1.12.0 (Flatpak release on linux if that matters)
In my case there's no subtitles, just an .mp4  container with an AC3 audio stream, and one external AC3 audio which the selector picks up and lists 2nd in the list with the appropriate " - External" tag.
However playback is not behaving as expected 100% of the time.
Selecting the 2nd track before hitting play works as expected, but switching between tracks during playback does not.
Playback has to be exited and re-initiated before the audio selection made during the previous playback will be played back.
