### ISSUE TITLE
installing 1.7.1 results in jellyfin-media-player 1.7.0 being installed

### ISSUE THREAD

**Issue by foss-** [jellyfin/jellyfin-media-player#273]
**Describe the bug**
Installing [JellyfinMediaPlayer-1.7.1-macos.dmg](https://github.com/jellyfin/jellyfin-media-player/releases/download/v1.7.1/JellyfinMediaPlayer-1.7.1-macos.dmg) on macOS 12.4 results in Jellyfin Media Player 1.7.0 being installed.

Once that is opened, users see a dialog offering the 1.7.1 update.

![jf](https://user-images.githubusercontent.com/5708172/175879762-b4b2f9fb-c7e3-4a7d-938b-124a3c13458e.png)

**To Reproduce**
1. Go to https://github.com/jellyfin/jellyfin-media-player/releases/tag/v1.7.1
2. Download and install [JellyfinMediaPlayer-1.7.1-macos.dmg](https://github.com/jellyfin/jellyfin-media-player/releases/download/v1.7.1/JellyfinMediaPlayer-1.7.1-macos.dmg)

**Expected behavior**
1.7.1 installed

**Desktop (please complete the following information):**
 - macOS 12.4
 - jellyfin media player 1.7.0 (or 1.7.1 with wrong version tag?)

**Comment by millallo** [comment]
me too. Also both buttons don't work, nothing happens clicking on them

**Comment by iwalton3** [comment]
Try closing and re-opening the application a few times. If that fixes the problem it suggests it may be a caching issue and I need to pursue a fix that way.

**Comment by suschizu** [comment]
I can confirm the issue … @iwalton3  I think the developer who build the Mac version just forgot to update the info.plist

it still contains:

```
	<key>CFBundleIdentifier</key>
	<string>tv.jellyfin.player</string>
[…]
	<key>CFBundleShortVersionString</key>
	<string>1.7.0</string>
[…]
	<key>CFBundleVersion</key>
	<string>1.7.0</string>
```

**Comment by anthonylavado** [comment]
Hi all, sorry for the issue. There was a caching problem when I uploaded the signed build.

Can you re-download it and try again?

**Comment by suschizu** [comment]
fixed thanks!
