### ISSUE TITLE
Option to remember library filters

### ISSUE THREAD

**Issue by Jerrk** [jellyfin/jellyfin-media-player#274]
**Is your feature request related to a problem? Please describe.**
I almost always will only want to see my "unplayed" movies/series when i go through my library. To do this i have to always manually go through the filters and tick in "unplayed" every single time i navigate away from the library.

**Describe the solution you'd like**
I would like an option to remember the filters for each library, could be a toggle in dashboard -> libraries -> manage library - :ballot_box_with_check:  "Remember filters" 

**Describe alternatives you've considered**
could make use of the [dead space in the bar](https://i.imgur.com/6KzqoyY.png) to show what filters are currently in use with an X to clear everything. This might be more of an extension of the solution if it is still made optional.

**Additional context**
The libraries do remember the "sort" and "select view" options so i don't think its too big of a stretch to remember the filters as well.

**Comment by iwalton3** [comment]
This should be logged as a Jellyfin web enhancement. I only handle bugs specific to the wrapper/playback engine here.
