### ISSUE TITLE
New version 1.7.1 is ungodly slow

### ISSUE THREAD

**Issue by BartAgterbosch** [jellyfin/jellyfin-media-player#275]
Running Windows 10 x64 currently, 16gb ram, ryzen 5 5600x, rtx 3060 ti.

It basically takes up 40% of an rtx 3060 ti now just displaying the startpage.
It then takes about 10 to 15 minutes just to load the images on the startpage.
And when trying to start a video it takes about 5 minutes just to start the player (if it will even start at all).
I was using version 1.7.0 up until just now and everything was running smooth as butter, but now on 1.7.1 it is borderline unusable.
Someone else that is using the same server has updated their client to 1.7.1 yesterday also is experiencing the same issues, also running win 10, but with a lower end gpu.

It can hardly be a network bottleneck since I'm running on the local lan, and the connection from my pc to the server is a 1gbit line..

**To Reproduce**
1. Update to 1.7.1
2. Just browse around the ui.
3. Try to play a movie

**Expected behavior**
To not hog 50% of the gpu, and/or not be so extremely sluggish, and if need be it being one or the other

**Comment by sevenrats** [comment]
It's important that all users upgrade to the latest security release. Please open a new issue if you experience this on a current version of JMP.
