### ISSUE TITLE
Support for DVBSUB subtitles

### ISSUE THREAD

**Issue by jluttine** [jellyfin/jellyfin-media-player#277]
**Is your feature request related to a problem? Please describe.**

MPV seems to support DVBSUB subtitles. There are no problems streaming a video over SSH and watching it with MPV and seeing DVBSUB subtitles correctly.

However, with Jellyfin and Jellyfin Media Player, DVBSUB subtitles trigger transcoding. The client says "SubtitleCodecNotSupported". Transcoding doesn't happen if I disable subtitles.

**Describe the solution you'd like**

I would like Jellyfin Media Player to not trigger transcoding because of DVBSUB subtitles but be able to directly play the video. MPV supports DVBSUB subtitles.

**Describe alternatives you've considered**

No ideas.

**Additional context**

No other context in mind.

**Comment by iwalton3** [comment]
As of right now if you embed the subtitles into the MKV file it won’t need to transcode. Jellyfin only recently gained the ability to serve DVD subtitles as external subtitles properly but I would need to do some tests to make sure other things are not affected.

**Comment by jluttine** [comment]
Thanks, not sure what you mean by "embedding into MKV". They are contained in the MKV file, yes, or does embedding mean something more specific? Also, DVD subtitles might be a different thing than DVBSUB. Not sure though, I'm not really familiar with this stuff..

**Comment by iwalton3** [comment]
Do you have external SUB/IDX files? Or just an MKV?

**Comment by jluttine** [comment]
Just MKV.

**Comment by jluttine** [comment]
Ffmpeg gives this info about the file:

```
  Stream #0:0(eng): Video: h264 (Main), yuv420p(tv, bt709, bottom first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn, 50 tbc (default)
  Stream #0:1(eng): Audio: ac3, 48000 Hz, stereo, fltp (default)
  Stream #0:2(fin): Subtitle: dvb_subtitle (default)
  Stream #0:3(dut): Audio: ac3, 48000 Hz, stereo, fltp (default)
  Stream #0:4(swe): Subtitle: dvb_subtitle (default)
```

**Comment by iwalton3** [comment]
If you can find this file in your installation, try tacking on this line:

https://github.com/jellyfin/jellyfin-media-player/blob/983125b76aa87e7e7d0b8a0e43fdadbc0b1531b3/native/nativeshell.js#L86

            {'Format': 'dvbsub', 'Method': 'Embed'},
