### ISSUE TITLE
Display dims while playing video

### ISSUE THREAD

**Issue by herrwusel** [jellyfin/jellyfin-media-player#285]
**Describe the bug**
Whenever I watch a video after some time my display goes to sleep/dims and ultimately locks. When I play videos in eg. firefox the display is kept from going to sleep.  Im using DPMS with the following settings:
```
xset s 180 300
xss-lock -l -n dim-screen.sh -- lockerutil.sh &
```

**To Reproduce**
Start video.

**Expected behavior**
Jellyfin-media-player suspends screen energy savings while playing videos

**Desktop (please complete the following information):**
 - OS: Arch
 - Installation Method: AUR version

**Additional context**
Im using X11 with dwm.

**Comment by rickylinden** [comment]
Same here both on Artix Linux with qtile and Linux Mint Cinnamon, both of them X11. Doesn't happen in Firefox or when watching a film with just mpv.

**Comment by herrwusel** [comment]
I tested a bit further. DBUS doesn't seem to receive the inhibit signal. I checked by running `dbus-monitor --system "interface='org.freedesktop.ScreenSaver'"`. 


@rickylinden a simple fix is to use the X11 screen management by altering cmake command (e.g. in PKGBUILD):
 `cmake -DCMAKE_INSTALL_PREFIX='/usr/' -DCMAKE_BUILD_TYPE='Debug' -DLINUX_X11POWER=ON -DQTROOT=./qt -DCMAKE_SKIP_RPATH=1 ..`

**Comment by dataprolet** [comment]
> @rickylinden a simple fix is to use the X11 screen management by altering cmake command (e.g. in PKGBUILD):
cmake -DCMAKE_INSTALL_PREFIX='/usr/' -DCMAKE_BUILD_TYPE='Debug' -DLINUX_X11POWER=ON -DQTROOT=./qt -DCMAKE_SKIP_RPATH=1 ..

Those options are in the latest PKGBUILD, but the issue remains, see #345.

**Comment by herrwusel** [comment]
I copied the jellyfin-media-player-git PKGBUILD and adding `-DLINUX_X11POWER=ON` fixed it for me.

**Comment by dataprolet** [comment]
What is `X11/XDG screensaver management`? Is it using DPMS? Because it's disabled on my system. Or is it using XScreensaver? Because that's not installed on my system.

**Comment by herrwusel** [comment]
To answer your first question: cmake is just telling you that x11 features (xdg-screensaver) is used instead of DBus.

As for DPMS: it is enabled on my system. Maybe give it a try.

**Comment by dataprolet** [comment]
Enabling DPMS solves the issue. Now I just need to figure out why it's turned off by default and why it's turning off by itself after turning it on manually.

**Comment by herrwusel** [comment]
I think I can close my issue, since my system does not have a program installed that provides `org.freedesktop.ScreenSaver`. Nothing jellyfin-media-player can do here I guess. Using the X11 power management solves the problem for me.

**Comment by p0358** [comment]
Hm, on my system with X11, KDE and DPMS enabled it does not work. I used AUR with `jellyfin-media-player` though, maybe I should give `jellyfin-media-player-git` a try...

I'm not sure the issue should be closed. It clearly does not (always) work out of the box, while other programs like Firefox do just work. Not sure if I should open separate duplicate issue...

I also wonder if it works on the Flatpak version
