### ISSUE TITLE
When media is paused monitor does not go to sleep

### ISSUE THREAD

**Issue by ThomasPGH** [jellyfin/jellyfin-media-player#290]
Not sure if this behaviour is intentional or slipped in accidentally.
Noticed and tested on Windows 10.

When a movie is played or paused in Jellyfin Media Player the monitor does not switch off. It only switches off when the playback is stopped.
When a movie is played in a browser the monitor does also not switch off, as intended. However, when the pause button is pressed in a browser the monitor switches off after the time set in the system's power options.

**Comment by ThomasPGH** [comment]
Sorry, just saw this. :)
https://github.com/jellyfin/jellyfin-media-player/pull/276

**Comment by iwalton3** [comment]
Looks like this can be closed.
