### ISSUE TITLE
Cannot play BDMV or VIDEO_TS folders

### ISSUE THREAD

**Issue by guiltlab** [jellyfin/jellyfin-media-player#293]
**Describe the bug**
I cannot play any movie in full Bluray or full DVD folder format in Jellyfin Media Player. When I click one, I get the error:
"Playback failed with error "loading failed". Retry with transcode? (Note this may hang the player.)"
Retrying with transcoding works for BDMV (slow/laggy probably due to my machine not being good enough for this) but not for VIDEO_TS. Either way, I would like to direct play, not transcode. Not sure if this is a bug or if the feature is just not in the software yet?

**To Reproduce**
1. Try to open title in full BD (BDMV folder) or full DVD (VIDEO_TS folder) format

**Expected behavior**
The movie plays without the need for transcoding.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version: Jellyfin Media Player 1.7.1
 - Installation Method: Windows installer

Thanks in advance :)

**Comment by iwalton3** [comment]
I don't think this is a feature I can feasibly offer. You would probably need to use Kodi in direct paths mode to support this, and even then I am unsure if it would work.

**Comment by ukanuk** [comment]
Same issue here with some of my BDMV folders. I have other BDMV folders with slightly different behavior; Jellyfin interprets each M2TS file in the BDMV/STREAM subfolder as a separate "special feature". Those direct play without issue. But of course, with Jellyfin ignoring the MPLS playlist files, I cannot watch the M2TS videos in any of the originally-intended orders.

**Comment by bassstorm** [comment]
Bot direct play and transcode don't work for me as well. What a miss...

**Comment by Shadowghost** [comment]
Fixed in server by https://github.com/jellyfin/jellyfin/pull/9254

Since this will not be backported to 10.8 you'll need to wait for 10.9 to have proper playback.

**Comment by sevenrats** [comment]
closing as fixed and pending release.
