### ISSUE TITLE
Scrolling title text

### ISSUE THREAD

**Issue by rickysarraf** [jellyfin/jellyfin-media-player#294]
**Is your feature request related to a problem? Please describe.**

It would be nice to have the file title to scroll when it is of a large size. Right now, to determine the full title, one has to hover over it and then a tooltip displays the full title. I haven't yet checked how this behaves on a TV setup, where I won't have a mouse.

**Describe the solution you'd like**
Would be nice to have an option that says, "Scroll Title"

**Describe alternatives you've considered**
The alternative is to  `hover your mouse over the title and see it in a tooltip`.

**Comment by iwalton3** [comment]
This is a web client request. Please post it to http://features.jellyfin.org/
