### ISSUE TITLE
Jellyfin Media player will not launch Windows 11

### ISSUE THREAD

**Issue by HrdCreCasual** [jellyfin/jellyfin-media-player#297]
**Describe the bug**
When attempting to open the program it gives a brief glimpse of the screen, then crashes without loading any content.

**To Reproduce**
1. Go to 'Jellyfin Media Player shortcut'
2. Click on 'Jellyfin Media Player'
3. See error '....'

**Expected behavior**
Expect for the interface to open and be able to use for media playback.

**Screenshots**
![Screenshot (5)](https://user-images.githubusercontent.com/111446143/185175882-909d3aa0-9130-4d50-98da-3a9cc8c320fa.png)
![Screenshot (6)](https://user-images.githubusercontent.com/111446143/185175910-731e86ec-ed19-42e7-899c-c98dcbe2d18c.png)
![Screenshot (7)](https://user-images.githubusercontent.com/111446143/185175926-94c9bfca-de08-492d-a26f-039139d02d6a.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 21H2
 - Installation Method Windows Installer

**Additional context**
Log from Event Viewer
Faulting application name: JellyfinMediaPlayer.exe, version: 0.0.0.0, time stamp: 0x62b907a8
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00000259fa7b6380
Faulting process id: 0x31a0
Faulting application start time: 0x01d8b24a2dad7ac1
Faulting application path: C:\Program Files\Jellyfin\Jellyfin Media Player\JellyfinMediaPlayer.exe
Faulting module path: unknown
Report Id: 17b74624-b27a-41a4-806d-2670d43f7ef0
Faulting package full name: 
Faulting package-relative application ID: 

Fault bucket 1548741698640503353, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: JellyfinMediaPlayer.exe
P2: 0.0.0.0
P3: 62b907a8
P4: StackHash_fd6c
P5: 0.0.0.0
P6: 00000000
P7: PCH_9B_FROM_ntdll+0x00000000000A4B84
P8: c0000005
P9: 0000000000000008
P10:

**Comment by zjeffer** [comment]
Please also include the latest log file, which can be found in `<user>/AppData/Local/JellyfinMediaPlayer/logs/`

**Comment by HrdCreCasual** [comment]
Log attached
[JellyfinMediaPlayer.log](https://github.com/jellyfin/jellyfin-media-player/files/9395269/JellyfinMediaPlayer.log)

**Comment by zjeffer** [comment]
Strange how it just stops at "Begin getAvailableServers".

Try a complete uninstall, also remove any configuration files. I have two folders in AppData/Local/: "JellyfinMediaPlayer" & "Jellyfin Media Player", delete both. 

Reboot, then try reinstalling and see if the problem persists.

**Comment by HrdCreCasual** [comment]
That fixed it. Not sure if something in Windows 11 changed but i never noticed the second install path. Thank you

**Comment by Beck-919** [comment]
I am facing the same issue, it is on the latest version: 1.8.1.

@zjeffer, tried your solution (twice + tried installing 1.7.1), but doesn't seem to work for me. I did not have any issue a week back.

Please find attached logfor reference: 
[JellyfinMediaPlayer.log](https://github.com/jellyfin/jellyfin-media-player/files/10949591/JellyfinMediaPlayer.log)

**Comment by smeualex** [comment]
> Strange how it just stops at "Begin getAvailableServers".
> 
> Try a complete uninstall, also remove any configuration files. I have two folders in AppData/Local/: "JellyfinMediaPlayer" & "Jellyfin Media Player", delete both.
> 
> Reboot, then try reinstalling and see if the problem persists.

I'm facing a similar issue with v1.9.0 on Windows 11.
Initially it worked, after some time on starting it displays a black screen and than it shuts down.

Doing the reinstall and also deleting the 2 folders helped.

Thanks!

Here's the EvtLog error:

```
Faulting application name: JellyfinMediaPlayer.exe, version: 0.0.0.0, time stamp: 0x640e31db
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000026821fcd0c0
Faulting process id: 0x0x5944
Faulting application start time: 0x0x1D964BA89506A6F
Faulting application path: C:\Program Files\Jellyfin\Jellyfin Media Player\JellyfinMediaPlayer.exe
Faulting module path: unknown
Report Id: 2c8b4e28-ff3b-41aa-80ed-4c415bb57b79
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by lucassfank** [comment]
In my case, also Windows 11, it happened after switching from an NVIDIA graphics card to an AMD one.

I thought I already had uninstalled the NVIDIA drivers with DDU (Display Driver Uninstaller), but I guess I wasn't in safe mode to remove completely.

After restarting in safe mode and removing again the NVIDIA drivers and all additional configs, it worked.

The clue was in the Event viewer error "Faulting module path: C:\Windows\system32\DriverStore\FileRepository\nv_dispig.inf_amd64_fa77e19594721328\nvcuda64.dll"
