### ISSUE TITLE
Windows7 64bit   report an error 0xc000007b

### ISSUE THREAD

**Issue by isLaLa** [jellyfin/jellyfin-media-player#302]
![20220906153949](https://user-images.githubusercontent.com/20499807/188575691-e6eb6c02-ddf8-4613-a0c9-b452b8a76283.png)

**Comment by 1273294133** [comment]
windows7就放弃吧。最新版的调用了某些windows10特有接口。如果偏要用win7要下载1.5.0或者1.5.0之前的版本

**Comment by AnonymousWebHacker** [comment]
我不知道，现在我在 win7 中尝试 1.5 看看它是否有效:) tnks @1273294133

**Comment by iwalton3** [comment]
Windows 7 is unsupported.
