### ISSUE TITLE
Black screen when using wayland (plasma and nvidia)

### ISSUE THREAD

**Issue by thesnallygaster** [jellyfin/jellyfin-media-player#308]
**Describe the bug**
When launched in a Plasma wayland session all I get is a black screen (works fine in xwayland, by changing the environment variable QT_QPA_PLATFORM to xcb), it spits this over and over again to stderr
```
libpng warning: iCCP: known incorrect sRGB profile
Logging to /home/redacted/.local/share/jellyfinmediaplayer/logs/jellyfinmediaplayer.log
[4133:4196:0918/160141.393861:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[4133:4196:0918/160141.393897:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[4133:4196:0918/160141.393904:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[4133:4196:0918/160141.393912:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
```

**To Reproduce**
1. Have an nvidia GPU
2. Launch in a wayland session (I've used plasma, you can use QT_QPA_PLATFORM=wayland to force wayland)

**Expected behavior**
Works just fine

**Screenshots**
![Screenshot_20220918_155508](https://user-images.githubusercontent.com/92674455/190910744-7e7f1e9d-da10-4879-8127-505a7c0e6ab7.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: jellyfin-media-player 1.7.1
 - Installation Method: Installed from the AUR package

**Additional context**
I'm using KDE Plasma (wayland) on an nvidia gpu (proprietary driver, version 515.65.01), it works just fine using xwayland. It also works fine on my laptop on an Intel iGPU

**Log file**
[jellyfinmediaplayer.log](https://github.com/jellyfin/jellyfin-media-player/files/9594140/jellyfinmediaplayer.log)

**Comment by wieli99** [comment]
Reproducible on Fedora

**Comment by thesnallygaster** [comment]
So I managed to launch it by appending `--disable-gpu`, it's not a proper fix but at least it works on wayland and still uses hardware decoding as far as I can tell.

**Comment by MartenBE** [comment]
I am also seeing this problem in F37 using wayland on an nvidia platform with flatpak. Using `--disable-gpu` seems a working workaround.

**Comment by thesnallygaster** [comment]
I've since sold the nvidia gpu but this seems like a problem with qt5-webengine as any program utilising it displays a black screen (see qutebrowser for example; only affects wayland), probably still present in qt6-webengine too.

**Comment by Orhideous** [comment]
It works now in latest KDE Neon.

```
KDE neon 5.26
KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.100.0
Qt Version: 5.15.7
```

**Comment by thesnallygaster** [comment]
@Orhideous what nvidia driver version are you using? Sadly I can't test this myself anymore but if you provide us the driver version it should work with I'll just close this issue

**Comment by Orhideous** [comment]
@thesnallygaster NVIDIA Driver version:  `525.60.11-0ubuntu0.22.04.1`

**Comment by thesnallygaster** [comment]
So either Qt 5.15.7 or NVIDIA driver version 525.60.11 fixes the issue, closing this bug report.

**Comment by Orhideous** [comment]
@thesnallygaster It turns that error wasn't fixed _per se_ — only swept under the rug.

**Comment by sorrymint** [comment]
This needs to be reopened.

**Comment by DJZeroAction** [comment]
--disable-gpu nolonger works for me. nvidia drivers on wayland.
