### ISSUE TITLE
Remote control is broken

### ISSUE THREAD

**Issue by shemanaev** [jellyfin/jellyfin-media-player#31]
That how it looks like from user perspective
![изображение](https://user-images.githubusercontent.com/1058537/114701768-e79e5500-9d2b-11eb-93e4-88e3d67caf27.png)

Client creates two playback sessions and the correct one (looking into `LastPlaybackCheckIn`) isn't `SupportsRemoteControl`. 
Only "Jellyfin Web" session shown in the interface among clients (both dropdown and dashboard).

It's strange that session inherits device name and app version (from `appHost` as i understand), but not app name.
Not sure where to dig.

Json from websockets "session" message
![изображение](https://user-images.githubusercontent.com/1058537/114700534-495dbf80-9d2a-11eb-91a9-ae70f9396982.png)

**Comment by iwalton3** [comment]
Log out and log back in. This is a known transition problem to 1.3.0 from reporting the player name correctly.

**Comment by shemanaev** [comment]
Oh, silly me! Should've done this in the first place. Thanks!
