### ISSUE TITLE
Release Media Player on Brew

### ISSUE THREAD

**Issue by uvulpos** [jellyfin/jellyfin-media-player#312]
**Is your feature request related to a problem? Please describe.**
I like software that is up-to-date and for me, it's easier to execute `brew update && brew upgrade` instead of downloading the newest software version. 

**Describe the solution you'd like**
A pipeline stage / step to build and upload a brew package to https://brew.sh/. Personally, I have an M1 Chip so an arm version would also be very nice (if possible) 😄 

**Describe alternatives you've considered**
Installing it from source or using another player.

**Additional context**
I think that's it 🙂

**Comment by chasetb** [comment]
Like this one? https://formulae.brew.sh/cask/jellyfin-media-player

**Comment by iwalton3** [comment]
Looks like this can be closed.
