### ISSUE TITLE
Server cannot be reached after restarting the player

### ISSUE THREAD

**Issue by AArnott** [jellyfin/jellyfin-media-player#313]
**Describe the bug**

I set up a Jellyfin server at https://jellyfin.mydomain.com, which works over a web browser consistently. 
Using the Jellyfin Media Player for Windows, I can connect to the server and play videos as well. But after closing the app and re-opening, it cannot connect. It shows the name of the server as 'arnottyh' which is the hostname of the server, but not its DNS name. When I click it, it tells me it cannot connect.
When I delete that server from the media player and re-add it with the full URL, it once again works. But only until I restart the app.

**To Reproduce**
1. Add a jellyfin server to the media player by its https://jellyfin.FQDN.com URL.
2. Browse videos.
3. Restart app
4. Connection fails until the server is removed and re-added to the player.

[JellyfinMediaPlayer.log](https://github.com/jellyfin/jellyfin-media-player/files/9639656/JellyfinMediaPlayer.log)
[JellyfinMediaPlayer.log (2)](https://github.com/jellyfin/jellyfin-media-player/files/9639663/JellyfinMediaPlayer.log)

**Expected behavior**

The player should remember the URL and connect to the server each time.

**Screenshots**

Adding the server:
![image](https://user-images.githubusercontent.com/3548/192120263-cc3b7416-f8d8-4e2b-af28-bb4c2e6fd7aa.png)

Signed in. It works:
![image](https://user-images.githubusercontent.com/3548/192120269-12b9466e-693a-458e-a892-949fe7456220.png)

Upon restarting the app, or selecting Select Server, I see this:
![image](https://user-images.githubusercontent.com/3548/192120277-905e43b1-15f3-4875-bcb4-e485832323a6.png)
Note the 'arnottyh' is what became of the server.

Choosing that server again fails:
![image](https://user-images.githubusercontent.com/3548/192120280-772f858e-77a1-497b-bb66-f11d52df700d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 1.7.1
 - Installation Method: Windows Installer

**Comment by AnonymousWebHacker** [comment]
`http://127.0.0.1:8096|https://jellyfin.mysideoftheweb.com/ `

the server https://jellyfin.mysideoftheweb.com/ , is your pc local? or is it a remote pc?

**Comment by AArnott** [comment]
That URL is a remote server I have hosted in the cloud. 

What is the meaning of the 2 URL piped syntax you put on your first line?

**Comment by AnonymousWebHacker** [comment]
`2022-09-24 15:08:09 [ INFO  ] JS: Stored JSON credentials: {"Servers":[{"ManualAddress":"https://jellyfin.mysideoftheweb.com/","LastConnectionMode":2,"Name":"arnottyh","Id":"40235d13665c4bf4b1c01459cde83a6c","LocalAddress":"http://127.0.0.1:8096","DateLastAccessed"`

if you are using windows, it seems that you have in the hosts file the address
127.0.0.1 jellyfin.mysideoftheweb.com. Check your file C:\Windows\System32\drivers\etc\hosts

**Comment by AArnott** [comment]
Thanks for looking.
I have no such entry in my hosts file. Furthermore, this repros on every Windows device I try it on.

It seems more likely that I have a configuration on the server itself that is confusing the client. FWIW, my server is set up on `http://127.0.0.1:8096` with an nginx reverse proxy on the same machine that makes it appear publicly at `https://jellyfin.mysideoftheweb.com`. Is there some configuration I need to change on my server?

**Comment by AnonymousWebHacker** [comment]
Haa, that's the same problem, your nginx, pass me your full nginx config to see, you have something wrong with the reverse proxy

**Comment by AArnott** [comment]
Great. I'm very new to nginx so I appreciate your review:

nginx.conf:

```
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
        # multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings
        ##

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}
```

sites-enabled/jellyfin

```
server {
    server_name jellyfin.mysideoftheweb.com; # managed by Certbot

        location / {
                proxy_bind 10.3.0.4;
                proxy_pass http://localhost:8096/;
        }
    listen 10.3.0.4:443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/jellyfin.mysideoftheweb.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/jellyfin.mysideoftheweb.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = jellyfin.mysideoftheweb.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 10.3.0.4:80 ;
    server_name jellyfin.mysideoftheweb.com;
    return 404; # managed by Certbot
}
```

**Comment by AnonymousWebHacker** [comment]
Really, I don't tend to because you guys make things so disorganized.

If possible, write me DM, on telegram https://t.me/L3G10N_X

**Comment by AnonymousWebHacker** [comment]
It solves the problem, it is a basic configuration, you still need to optimize the nginx more, (this one solves the problem) 
```
server {
    listen 80;
    listen [::]:80;
    server_name jellyfin.mysideoftheweb.com;

    # Uncomment to redirect HTTP to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name jellyfin.mysideoftheweb.com;

   #Certificates
    ssl_certificate /etc/letsencrypt/live/jellyfin.mysideoftheweb.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/jellyfin.mysideoftheweb.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    location / {
        # Proxy main Jellyfin traffic
        proxy_pass http://jellyfin.mysideoftheweb.com:8090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;

        # Disable buffering when the nginx proxy gets very resource heavy upon streaming
        proxy_buffering off;
    }
    
    # location block for /web - This is purely for aesthetics so /web/#!/ works instead of having to go to /web/index.html/#!/
    location = /web/ {
        # Proxy main Jellyfin traffic
        proxy_pass http://jellyfin.mysideoftheweb.com:8090/web/index.html;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
    }
    
        location /socket {
        # Proxy Jellyfin Websockets traffic
        proxy_pass http://jellyfin.mysideoftheweb.com:8090;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
    }
    
    

}
```

**Comment by AArnott** [comment]
Thank you!
