### ISSUE TITLE
Resuming H265 MKV on another windows device causes video not to load

### ISSUE THREAD

**Issue by ItsOnlyBinary** [jellyfin/jellyfin-media-player#316]
**Describe the bug**
When resuming a H265 mkv on a second windows device the video does not load and it stays on a frozen home view.

Attempting to close JF Media Player does not fully exit all processes and a subsequent attempt to open JFMP just results in it opening with default config (I assume the config is locked by the instance that did not fully exit). Killing the processes with task manager resolves this.

The issue does not seem to occur with H264 mkv's

**To Reproduce**
On first windows device (maybe does not need to be windows) part watch a H265 mkv video
Go back on that video so it shows as part watched
Now try to continue watching that video on a different windows device (resume will work fine on the same device)

**Expected behavior**
It is expected that the video will start playing from the point it was left on the other device

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Version: 21H2
 - Installation Method: windows installer x64
 - Jellyfin Media Player version: 1.7.1

**Additional context**
I have attached a log although I don't think it contains any useful information. In the log i have replaced all potentially identifiable information with strings of the same length and chars, this incudes device id, user id etc

[JellyfinMediaPlayer.log](https://github.com/jellyfin/jellyfin-media-player/files/9685113/JellyfinMediaPlayer.log)

**Comment by etrigan63** [comment]
This same issue (not resuming H.265 MKV playback from stop point) also happens with Mac and Linux JMP clients. Web interface works as expected.

**Comment by sevenrats** [comment]
@etrigan63 you are describing a distinct issue. please open a new report if you are still having this problem.

**Comment by sevenrats** [comment]
@ItsOnlyBinary do you still experience this issue on a modern version of JMP?

**Comment by ItsOnlyBinary** [comment]
I've not had this happen for a while. So it maybe solved.

**Comment by sevenrats** [comment]
between your not experiencing it in awhile and my inability to reproduce, I'm going to go ahead and close.  please open a new issue if this happens on release.
Thank you!

**Comment by rickparrish** [comment]
I just ran into this problem, and found that either of these changes in JMP's Client Settings allowed playback to resume:

1. Set Video Hardware Decoding to decode.disabled, or
2. Check Always_force_transcode

I realize this thread has been closed, but figured this may be helpful if someone else has the same problem and comes across this thread like I did.

**Comment by ItsOnlyBinary** [comment]
I've had this happen again and indeed disabling Hardware Decode solved the issue (it was set to `Copy") also tested with `Enabled` but that still caused the issue.
