### ISSUE TITLE
Question about book format for fastest load 

### ISSUE THREAD

**Issue by userobvixus** [jellyfin/jellyfin-media-player#33]
(primary sorry for my english i hope you can understand me)
Is it possible to add JPG, PNG, CBR, CBZ, and PDF format to jellyfin media player to load faster every book ?
because i can load movie with subtitle instantly with you media because no transcoding needed is it possible to do the same with book ?
Thanks for reading me and for your work !
Have a good day !

**Comment by iwalton3** [comment]
Right now any ebook support is handled entirely by the web client and not by any native support.

**Comment by userobvixus** [comment]
alright thanks for your answer !

**Comment by iwalton3** [comment]
There aren’t currently plans to implement native book support in JMP, as the web features are likely good enough. Take for instance that Firefox renders PDFs using pdf.js and the experience is fine. I would encourage opening an issue with jellyfin-web to improve support if it is needed.
