### ISSUE TITLE
Player (Arch Linux) fails to playback .mkv files (serverbuild 10.8.7, only directplay allowed)

### ISSUE THREAD

**Issue by gordon848** [jellyfin/jellyfin-media-player#332]
Im not sure if this is a player related problem or a server problem. If I play a typical .mkv file I get a Playbackerror (Tries to transcode which is disabled for all users). Somehow this has something to do with the serverbuild. Using 10.7.7 I can direct play all of my files. But using latest (10.8.7) I cant play most of my .mkv files (AC3 audio).

Log:
`[2022-11-01 21:47:39.092 +01:00] [INF] [18] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "test". EnablePlaybackRemuxing: False EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: False
[2022-11-01 21:47:39.111 +01:00] [INF] [18] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Jellyfin Media Player", Path="/data/some.mkv", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=ContainerBitrateExceedsLimit ) "media:/videos/45183281-52cb-1f65-556e-16bb7cccc896/stream?MediaSourceId=4518328152cb1f65556e16bb7cccc896&AudioStreamIndex=1&api_key=<token>&RequireAvc=false&Tag=d1acc283c96ae0440e9dd4d9f005abe7&TranscodeReasons=ContainerBitrateExceedsLimit"
[2022-11-01 21:47:41.082 +01:00] [INF] [8] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Media Player" "1.7.1" playing "Ciao". Stopped at "0" ms% `

Using kodi" or jellyfin-mpv-shim as a client plays all files  even in build 10.8.7. So I guess JMP has problems with the 10.8.x builds?

![1](https://user-images.githubusercontent.com/91946909/199343103-0bdcdb52-07bf-4519-ad48-1d0a618e004b.jpg)
![2](https://user-images.githubusercontent.com/91946909/199343106-f35ff5f5-ffa1-423e-95b3-5c36e5fc0ee5.jpg)
![3](https://user-images.githubusercontent.com/91946909/199343107-07992d9d-df04-4625-9221-55c24b9e9091.jpg)
![4](https://user-images.githubusercontent.com/91946909/199343110-ef3cd9ea-ce6c-4876-a122-e27474f04f7c.jpg)

**Comment by kaypoush** [comment]
You should also enable _Allow video playback that requires conversion without re-encoding_ and try again.

**Comment by gordon848** [comment]
Thats not my point. If I enable it, it does remuxing which I dont want. Like shown in my last screenshot it is possible to just check "Allow media playback" in build 10.7.7 and watch all .mkvs and other file formats in direct play mode.
My point is that its not working with the 10.8.x builds which seems to be a bug?!

**Comment by zeretrelle** [comment]
I'm having exactly the same issue on y Macbok Pro (intel) 

Jellyfin Version 10.8.7 
Jellyfin Media Player v1.7.1

This is the relevant info from the logs:

_Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Jellyfin Media Player", Path="/data/TV/zzz/Season 01/zzz - s01e03 - zz.mkv", AudioStreamIndex=1, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=**ContainerBitrateExceedsLimit** )_

Trancscoding and conversion is disabled on the server.

I have no issues playing these files on Windows or android

**Comment by gordon848** [comment]
I forgot to mention that the failure occurs not on windows or android devices. Only on my main system which runs Arch Linux.

**Comment by iwalton3** [comment]
If you set the log level of your Jellyfin server to Debug it may provide more information as to why the bitrate check is failing. I would also suggest checking the bitrate settings in the JMP playback preferences section.
