### ISSUE TITLE
Arch linux: crashing on start

### ISSUE THREAD

**Issue by yagarea** [jellyfin/jellyfin-media-player#336]
**Describe the bug**
Jellyfin imidietly crashes on lauch with this error:
```
jellyfinmediaplayer: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory
```

**To Reproduce**
1. Install jellyfinmediaplayer on arch linux
2. start it

**Expected behavior**
not crashing

**Desktop (please complete the following information):**
 - OS: Arch Linux  6.0.8-arch1-1
 - Version: 1.7.1-1
 - Installation Method: AUR

**Additional context**
There are no logs since this error occurred.

**Comment by Zebradil** [comment]
As a workaround, jellyfin-media-player can be replaced by [jellyfin-media-player-git](https://aur.archlinux.org/packages/jellyfin-media-player-git).

**Comment by gordon848** [comment]
Another workaround would be to downgrade the "mpv-package".

`pacman -U /var/cache/pacman/pkg/mpv-1:0.34.1-5-x86_64.pkg.tar.zst`

**Comment by HamletDuFromage** [comment]
Error is as follows `jellyfinmediaplayer: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory`

An easy fix that doesn't seem to break anything is to symlink the now gone library with the new one

$ `sudo ln -s /usr/lib/libmpv.so.2.0.0 /usr/lib/libmpv.so.1`

**Comment by akyag** [comment]
I had the same problem, I rebuilt the jellyfin-media-player and it works now.

**Comment by DevPGSV** [comment]
I have just `yay -S jellyfin-media-player` on Arch x86_64 6.0.8-arch1-1, and it worked flawlessly

**Comment by mcarlton00** [comment]
This isn't an issue with jellyfin media player.  It's that a library that JMP depends on has been updated on your system, so you need to rebuild the package against your local libraries

**Comment by yagarea** [comment]
> This likely isn't an issue with jellyfin media player. It's that a library that JMP depends on has been updated on your system, so you need to rebuild the package against your local libraries

In that case I am closing this issue.Thank you everyone involved for their support.
