### ISSUE TITLE
Taskbar Progress

### ISSUE THREAD

**Issue by Ponkhy** [jellyfin/jellyfin-media-player#342]
**Is your feature request related to a problem? Please describe.**
I'm getting easily distracted by the green progress bar of the media player icon.
![image](https://user-images.githubusercontent.com/43121732/205415795-ebb07cde-0f49-4d5a-be52-0d6dfd0dcc67.png)

**Describe the solution you'd like**
Be able to disable/toggle it

**Additional context**
It might be something small and picky, but it would be great to decide if you want to enable or disable it.

**Comment by iwalton3** [comment]
There will be a client setting in the next release called "enableWindowsTaskbarIntegration" to disable this.
