### ISSUE TITLE
Build instructions for other linux system. (Fedora)

### ISSUE THREAD

**Issue by tr1p0p** [jellyfin/jellyfin-media-player#343]
So, because [this issue](https://github.com/jellyfin/jellyfin-media-player/issues/191#issue-1093322608) around 5.1 pass-through will not be solved quite soon, i need to actually build jellyfin media player for my fedora 37.

But the requirements are only for debian-based distribution. I tried to transform some reqs into fedora packages.

Here what i tried : 

`sudo dnf in autoconf automake libtool freetype-devel libXrandr-devel libvdpau-devel libva-devel  mesa-libGL-devel libdrm-devel libX11-devel  mesa-libEGL-devel yasm  alsa-lib pulseaudio-libs-devel zlib-devel fribidi-devel git gnutls-devel mesa-libGLU-devel  SDL2-devel cmake wget python g++  qt-devel libcec-devel qt5-qtbase-devel curl unzip qt5-qtwebchannel-devel
qt5-qtwebengine-devel qt5-qtx11extras-devel`

It kind of worked, it build and install but show a error at launch 

`QSocketNotifier: Can only be used with threads started with QThread`

So i guess it miss some stuffs.

Can someone help me on this ? Why there's absolutely no support for other distro than debian, at least for build ?

Thanks.

**Comment by rifkles** [comment]
You can install jellyfin media player on fedora by using flatpak and grabbing JMP from flathub.

[Link to flathub taken from jellyfin website](https://flathub.org/apps/details/com.github.iwalton3.jellyfin-media-player)

They have setup instructions for flatpak on their website.

**Comment by lbrunkho** [comment]
I'm trying to build for Fedora 37 as well and I've run into this error in the last make command...
```
~/jmp/jellyfin-media-player-1.8.1/src/player/PlayerQuickItem.cpp:29:10: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
   29 | #include <qpa/qplatformnativeinterface.h>
```
It does not seem like a dependency problem. I've attempted building this by pulling directly from the git and also by pulling the source tarball from the latest release. Any advice is greatly appreciated. 
I'm unable to use the flatpak image due to the packaged instance of ffmpeg not accepting custom ca certs in the system store. #301

**Comment by SirFritz** [comment]
Try installing the ````qt5-qtbase-private-devel```` package.  That worked for me.

**Comment by lbrunkho** [comment]
Thanks @SirFritz that did the trick! Summary of the commands used to build JMP on Fedora 37.

Some dependencies may be unneeded here, I've just appended all the packages that I've installed during this process.
`
sudo dnf install autoconf automake libtool freetype-devel libXrandr-devel libvdpau-devel libva-devel  mesa-libGL-devel libdrm-devel libX11-devel  mesa-libEGL-devel yasm  alsa-lib pulseaudio-libs-devel zlib-devel fribidi-devel git gnutls-devel mesa-libGLU-devel  SDL2-devel cmake wget python g++  qt-devel libcec-devel qt5-qtbase-devel curl unzip qt5-qtwebchannel-devel qt5-qtwebengine-devel qt5-qtx11extras-devel mpv.x86_64 qwt-qt5-devel.x86_64 qt5-qtbase.x86_64 meson.noarch ninja-build.x86_64 qt5-qtbase-private-devel`

```
mkdir ~/jmp; cd ~/jmp
git clone https://github.com/mpv-player/mpv-build.git
cd mpv-build/
echo -Dlibmpv=true > mpv_options
echo -Dpipewire=disabled >> mpv_options # hopefully temporary
./rebuild -j4
sudo ./install
sudo mkdir /usr/local/lib/x86_64-linux-gnu
sudo ln -s /usr/local/lib64/libmpv.so /usr/local/lib/x86_64-linux-gnu/libmpv.so.1
sudo ln -s /usr/local/lib64/libmpv.so /usr/local/lib/x86_64-linux-gnu/libmpv.so
sudo ldconfig
cd ~/jmp/
git clone https://github.com/jellyfin/jellyfin-media-player.git
cd jellyfin-media-player/
./download_webclient.sh 
cd build/
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr/local/ ..
make -j4
sudo make install
```

I am able to launch JMP and playback video! 

Note that the launcher icon is broken on GNOME.
![image](https://user-images.githubusercontent.com/24943712/219228379-7e3038e7-5476-4c7b-adf4-4e8d53f462da.png)

**Comment by tr1p0p** [comment]
Yeah it was working before, but for last update it seem it's not properly work no more weirdly.. it crash and don't play video

**Comment by iwalton3** [comment]
You may need to compile MPV from source without pipe wire support. It is causing an issue where searching devices segfaults the player.
