### ISSUE TITLE
Volume boost through mpv.conf is not respected in UI

### ISSUE THREAD

**Issue by vegedb** [jellyfin/jellyfin-media-player#348]
**Describe the bug**
Volume boost through mpv.conf is not respected in UI since its maxed at 100%

**To Reproduce**
add volume-max=200
Scroll wheel UI maxes at 100% 
There's no keyboard shortcut like default mpv to change it too!

**Expected behavior**
DEFAULT Keyboard shortcut for volume is 
`/ and * Decrease/increase volume.`

**Screenshot = Default MPV**
![image](https://user-images.githubusercontent.com/72070424/209445226-9790b407-9c36-4dd3-9182-9e7b0117473d.png)

**Screenshot = Jellyfin MPV**
![image](https://user-images.githubusercontent.com/72070424/209445280-656b1418-17f3-4455-9623-ad057fcc7541.png)

**Additional context**
LOGS,
`[ DEBUG ] PlayerComponent.cpp @ 588 - cplayer: Reading config file E:/Users/AppData/Local/JellyfinMediaPlayer/mpv.conf `
`[ DEBUG ] PlayerComponent.cpp @ 588 - cplayer: Setting option 'volume-max' = '300' (flags = 4) `

**Comment by zombiehoffa** [comment]
This is probably the same bug as playback speed is also not respected in  mpv.conf

I see 2023-01-28 10:10:25 [ DEBUG ] PlayerComponent.cpp @ 588 - cplayer: Setting option 'speed' = '2' (flags = 4)

but then 3 seconds later when I start a video play I get this:
2023-01-28 10:10:28 [ DEBUG ] PlayerComponent.cpp @ 588 - cplayer: Set property: speed=1.000000 -> 1

So you are probably getting the same thing and if you look further down in the log I bet you see the same thing when you st art playbacka nd the volume is just forced to 100%

**Comment by sevenrats** [comment]
#543
