### ISSUE TITLE
Mute does not persist beyond 1 episode played

### ISSUE THREAD

**Issue by yslupdates** [jellyfin/jellyfin-media-player#349]
**Describe the bug**
I want to keep Jellyfin Media Player muted and continue playing episodes. But the setting does not stick once it moves on to the next episode. The mute sign still shows, but audio plays.

**To Reproduce**
1. Play any tv series
2. Click sound button to mute, confirm slash mute icon showing
3. Finish playing video, go to next episode
4. Hear error

**Expected behavior**
Mute should persist until I unclick the sound/mute button

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.7.1 media player, latest jellyfin 10.8.8
 - Installation Method  windows installer

**Comment by iwalton3** [comment]
This will be fixed in the next release.
