### ISSUE TITLE
Error in Windows 7

### ISSUE THREAD

**Issue by GiganteX** [jellyfin/jellyfin-media-player#356]
I tried to run the 1,7,1 version in Windows 7 and got an unfriendly error message about a missing DLL: api-ms-win-core-winnt-string etc etc.dll

There are three problems here:
* That DLL is a Win10 DLL, which means this program does not run in Windows 7
* Inform the user of OS requirements before downloading
* Unfriendly error message, please check if you're in the correct OS before starting the install process, and notify the user in a friendly way.

**Comment by rifkles** [comment]
You can try version 1.5.0. Windows 7 isn't officially supported after integration of On Screen DIsplay into JMP

**Comment by iwalton3** [comment]
Windows 7 is unsupported.

**Comment by Temik007** [comment]
It is working on windows 7 with dll:
api-ms-win-core-winrt-l1-1-0.dll
api-ms-win-core-winrt-string-l1-1-0.dll

Dlls is here: https://github.com/PowerShell/PowerShell/issues/19816

And this config:
jellyfinmediaplayer.conf
`{
    "sections": {
        "appleremote": {
            "emulatepht": false
        },
        "audio": {
            "channels": "2.0",
            "device": "auto",
            "devicetype": "basic",
            "exclusive": false,
            "normalize": true,
            "passthrough.ac3": false,
            "passthrough.dts": false,
            "passthrough.dts-hd": false,
            "passthrough.eac3": false,
            "passthrough.truehd": false
        },
        "cec": {
            "activatesource": false,
            "enable": false,
            "hdmiport": 0,
            "poweroffonstandby": false,
            "suspendonstandby": false,
            "usekeyupdown": false,
            "verbose_logging": false
        },
        "main": {
            "alwaysOnTop": false,
            "autodetectCertBundle": false,
            "checkForUpdates": false,
            "disablemouse": false,
            "enableInputRepeat": false,
            "enableWindowsMediaIntegration": false,
            "enableWindowsTaskbarIntegration": false,
            "forceAlwaysFS": false,
            "forceExternalWebclient": false,
            "forceFSScreen": "",
            "fullscreen": false,
            "hdmi_poweron": false,
            "ignoreSSLErrors": true,
            "layout": "desktop",
            "logLevel": "debug",
            "minimizeOnDefocus": false,
            "sdlEnabled": false,
            "showPowerOptions": false,
            "useOpenGL": false,
            "useSystemVideoCodecs": false,
            "userWebClient": "",
            "webMode": "desktop"
        },
        "path": {
            "startupurl_desktop": "bundled",
            "startupurl_extension": "bundled"
        },
        "plugins": {
            "jellyscrub": false,
            "skipintro": false
        },
        "subtitles": {
            "color": "#EEEEEE,#000000",
            "placement": "center,bottom",
            "size": 32
        },
        "system": {
            "lircd_enabled": false,
            "smbd_enabled": false,
            "sshd_enabled": false,
            "systemname": "JellyfinMediaPlayer"
        },
        "video": {
            "allow_transcode_to_hevc": false,
            "always_force_transcode": false,
            "aspect": "normal",
            "audio_delay.24hz": 0,
            "audio_delay.25hz": 0,
            "audio_delay.50hz": 0,
            "audio_delay.normal": 0,
            "cache": 75,
            "debug.force_vo": "",
            "deinterlace": false,
            "force_transcode_4k": false,
            "force_transcode_av1": false,
            "force_transcode_dovi": false,
            "force_transcode_hdr": false,
            "force_transcode_hevc": false,
            "force_transcode_hi10p": false,
            "hardwareDecoding": "copy",
            "prefer_transcode_to_h265": false,
            "refreshrate.auto_switch": false,
            "refreshrate.avoid_25hz_30hz": false,
            "refreshrate.delay": 3,
            "sync_mode": "audio"
        }
    },
    "version": 6
}
`
