### ISSUE TITLE
Seekbar black background too large

### ISSUE THREAD

**Issue by gggirlgeek** [jellyfin/jellyfin-media-player#36]
Hello,

The seekbar black background is very large, vertically, and it covers the subtitles and credits while I'm seeking. See screenshot.  This is not the case in Jellyfin MPV or Jellyfin Web. Can this be fixed in a future release?

![JellyfinMediaPlayer_yZLzaalFPT](https://user-images.githubusercontent.com/2652614/115068173-24df2000-9eaf-11eb-95da-5d4047038f2b.jpg)

Win10pro v2004
JMP v1.2.1 Desktop/Auto mode
Jellyfin Server v10.6.x on Ubuntu 18.6 managed seedbox

**Comment by iwalton3** [comment]
The background for the seek bar by default is transparent and the seek bar is blue. Are you using custom css? I cannot do anything about any custom CSS themes, instead you must have the author of the CSS fix it.

**Comment by gggirlgeek** [comment]
What? No. I have not customized any CSS. My server does have the theme plugin installed though, and I have installed the Netflix theme so that might be why the seekbar is red. However, Jellyfin Web and Jellyfin Mpv desktop don't have this large black area. It's smaller. Wouldn't the server's theme be the same on all clients?
