### ISSUE TITLE
mpv.conf speed setting overwritten by jellyfindmediaplayer when media starts playing

### ISSUE THREAD

**Issue by zombiehoffa** [jellyfin/jellyfin-media-player#361]
Four considerations:
 - Please do not open bug reports to ask questions. Use the Discussions feature instead.
 - Please make sure the issue only pertains to Jellyfin Media Player. If it also occurs in the web client, send the issue to jellyfin-web instead.
 - Please make sure that your issue is not being caused by errors in custom CSS or note that you are using custom CSS.
     - Notably, there have been instances of custom CSS breaking TV mode.
     - You can disable custom CSS under Display in the user settings.
 - Please provide logs. You can drag the log file into the issue to attach it.
     - Windows: `%LOCALAPPDATA%\JellyfinMediaPlayer\logs`
     - Linux: `~/.local/share/jellyfinmediaplayer/logs/`
     - Linux (Flatpak): `~/.var/app/com.github.iwalton3.jellyfin-media-player/data/jellyfinmediaplayer/logs/`
     - macOS: `~/Library/Logs/Jellyfin Media Player/`

**Describe the bug**
I set mpv.conf with speed=2. I see in my logs that JMP see this and sets speed=2
2023-01-28 14:46:22 [ DEBUG ] PlayerComponent.cpp @ 588 - cplayer: Setting option 'speed' = '2' (flags = 4)

but when I start media playing JMP then overwrites this and sets speed=1
2023-01-28 14:46:26 [ DEBUG ] PlayerComponent.cpp @ 588 - cplayer: Set property: speed=1.000000 -> 1

I can then go into the interface and manually change the play speed to 2 and that works, it just isn't playing default the way it should.
**To Reproduce**
create mpv.conf and put option speed=2 in it

**Expected behavior**
I expect JMP to respect the options I have set in the mpv.conf file and play my media at default speed 2

**Screenshots**

**Desktop (please complete the following information):**
 - Installation Method [e.g. windows installer]

**Additional context**
[jellyfinmediaplayer.log](https://github.com/jellyfin/jellyfin-media-player/files/10528363/jellyfinmediaplayer.log)

**Comment by sevenrats** [comment]
moved to #543
