### ISSUE TITLE
Not running M1 Linux Flatpak

### ISSUE THREAD

**Issue by Radiicall** [jellyfin/jellyfin-media-player#368]
- Please make sure the issue only pertains to Jellyfin Media Player. If it also occurs in the web client, send the issue to jellyfin-web instead.
yup
 - Please provide logs. You can drag the log file into the issue to attach it.
 [jellyfinmediaplayer.log](https://github.com/jellyfin/jellyfin-media-player/files/10673059/jellyfinmediaplayer.log)

**Describe the bug**
Jellyfin Media Player is not loading, however it does load when compiling from source, this leads me to believe its a problem with how its packaged for aarch64. The M1 runs a 16k kernel and i don't think the package is being compiled in a way to make it compatible.

**To Reproduce**
1. Open Jellyfin Media Player flatpak on an M1 Mac

**Expected behavior**
App loading

**Screenshots**
![image](https://user-images.githubusercontent.com/66682497/217194894-136e3993-a016-4fa3-8ffa-b26971f2f14f.png)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 37 for M1
 - Version: 1.7.1
 - Installation Method: Flatpak

**Comment by sevenrats** [comment]
There is pretty much no reason to expect any JMP release to work on  Apple Silicon.  We don't have the CI for it.  Building from source works, there is even a Qt6 branch with native support (tho there is minor ux bug in it that we are waiting on Qt to fix).
