### ISSUE TITLE
Gives update notice for JMP 1.7.1 flatpak when using 1.8.0

### ISSUE THREAD

**Issue by coreybruce** [jellyfin/jellyfin-media-player#369]
**Describe the bug**
When I open up JMP I get a notice saying to update to 1.7.1 on the flatpak version even tho I am using the latest 1.8.0 version

**To Reproduce**
1. open up JMP

**Expected behavior**
Should be telling me to update when I am using a newer version

**Screenshots**
![image](https://user-images.githubusercontent.com/8393780/218379866-eaf5db05-58de-47f8-b148-b80960ead9d8.png)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Version 1.8.0
 - Installation Method Flatpak

**Additional context**

**Comment by iwalton3** [comment]
Yeah I'm aware of this. I'm just going to publish the 10.8.0 version since Mac OS is having issues being notarized. (Flathub _used_ to delay releases by 24 hours but evidently this changed and I never found out.)
