### ISSUE TITLE
Tooltip timeout too short in library interface (mouse hover)

### ISSUE THREAD

**Issue by gggirlgeek** [jellyfin/jellyfin-media-player#37]
Hello,

Small gripe: On the home page, when hovering over the Title below the thumbnails the tooltip times out too fast for me to read to name of the file. This is not the case in Jellyfin-web or MVP. This is a problem if the file cannot be identified, or the title is not shown in the thumbnail. See screenshot as an example of the filename tooltip. It needs to be 5-7 seconds maybe.

![JellyfinMediaPlayer_WMbduryrJb (2)](https://user-images.githubusercontent.com/2652614/115070651-776e0b80-9eb2-11eb-9c0c-f0427b35126b.jpg)

Thanks a lot.

Win10pro v2004
JMP v1.2.1 Desktop/Auto mode
Jellyfin Server v10.6.x on Ubuntu 18.6 managed seedbox

**Comment by iwalton3** [comment]
This looks like a bug in QT WebEngine. I have not found any references though for what might be causing the issue.

**Comment by gggirlgeek** [comment]
Upgraded to v1.6.0 and the tooltip stays visible indefinitely. So it's fixed. Thank you.
