### ISSUE TITLE
Jellyscrub plugins cannot be enabled separately

### ISSUE THREAD

**Issue by heunghingwan** [jellyfin/jellyfin-media-player#371]
Four considerations:
 - Please do not open bug reports to ask questions. Use the Discussions feature instead.
 - Please make sure the issue only pertains to Jellyfin Media Player. If it also occurs in the web client, send the issue to jellyfin-web instead.
 - Please make sure that your issue is not being caused by errors in custom CSS or note that you are using custom CSS.
     - Notably, there have been instances of custom CSS breaking TV mode.
     - You can disable custom CSS under Display in the user settings.
 - Please provide logs. You can drag the log file into the issue to attach it.
     - Windows: `%LOCALAPPDATA%\JellyfinMediaPlayer\logs`
     - Linux: `~/.local/share/jellyfinmediaplayer/logs/`
     - Linux (Flatpak): `~/.var/app/com.github.iwalton3.jellyfin-media-player/data/jellyfinmediaplayer/logs/`
     - macOS: `~/Library/Logs/Jellyfin Media Player/`

**Describe the bug**
In the Client Settings tab, if you only enable Jellyscrub it won't work, even if the server doesn't have Skipintro installed, Skipintro needs to be enabled for it to work.

**To Reproduce**
1. Go to 'Client Settings'
2. Enable 'Jellyscrub'
3. Restart

**Expected behavior**
Plugins can be enabled individually

**Screenshots**
![image](https://user-images.githubusercontent.com/11424817/218430675-3302b313-9f16-47a3-8428-28297a1501d4.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 1.8.0
 - Installation Method: windows installer

**Additional context**

**Comment by iwalton3** [comment]
Sigh... guess I need to do a point release

**Comment by iwalton3** [comment]
Fixed in https://github.com/jellyfin/jellyfin-media-player/releases/tag/v1.8.1.
