### ISSUE TITLE
[Installer] Update from 1.8.0 to 1.8.1 forced a reboot

### ISSUE THREAD

**Issue by Pingger** [jellyfin/jellyfin-media-player#378]
**Describe the bug**
Upon updating the Media Player using WinGET (`winget upgrade Jellyfin.JellyfinMediaPlayer`), the installer initiates a reboot without warning or prompt.

**To Reproduce**
1. Install 1.8.0
2. Upgrade using `winget upgrade Jellyfin.JellyfinMediaPlayer`
3. Be kicked out of your session, because your fucking media player installer initiates a reboot

**Expected behavior**
No reboot at all, or at the very least a prompt

**Screenshots**
\-

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10.0.19045.2251
 - Installation Method [e.g. windows installer]: winget upgrade

**Additional context**
\-

**Comment by iwalton3** [comment]
I don't maintain the winget package. It looks like it was updated here: https://github.com/microsoft/winget-pkgs/pull/96715

**Comment by Pingger** [comment]
Which just downloads the github release and starts the silent Installation with Progress.

https://github.com/Scavy/winget-pkgs/blob/c600c7af131c55ba2e8dac4f5f9b2e008a9bceb3/manifests/j/Jellyfin/JellyfinMediaPlayer/1.8.1/Jellyfin.JellyfinMediaPlayer.installer.yaml#L17

**Comment by iwalton3** [comment]
Looks like the installer needs the norestart argument to install without surprise reboots. File an issue here: https://github.com/microsoft/winget-pkgs/issues/new?assignees=&labels=Issue-Bug&template=package_issue.yml&title=%5BPackage+Issue%5D%3A+Package.Identifer

**Comment by p0358** [comment]
Why does it even ask for a reboot at all in the first place? The app seems to work just fine after being installed without any reboots, 99% programs out there don't need a reboot pretty much ever apart from some special cases.

**Comment by iwalton3** [comment]
Because the dotnet framework it uses sometimes asks for a reboot and it gets passed up the chain despite not actually needing it.

**Comment by sevenrats** [comment]
Thanks for your report!
