### ISSUE TITLE
openssl certificate and my android 9 device

### ISSUE THREAD

**Issue by RSerejo** [jellyfin/jellyfin-media-player#379]
its not exactly a bug but a problem what i'm having, i already spend a loot time trying to understand why android app is not working, then after i tried to import the p12 cert to my phone i saw my Android 9 is incompatibility and  it's working on waydroid.

openssl req -x509 -newkey rsa:4096 -keyout ./privkey.pem -out cert.pem -days 365 -nodes -subj '/CN=jellyfin.lan' (it's how i did to make the certificate.)

i tried rsa:2048 too but don't work too

i need help with it

**Comment by RSerejo** [comment]
I achieved install to install certificate on my phone with it https://stackoverflow.com/questions/71872900/installing-pcks12-certificate-in-android-wrong-password-bug
but i'm still with the some problem, now i don't know what is happening.

**Comment by iwalton3** [comment]
This does not seem related to the desktop client.
