### ISSUE TITLE
Font size too big in thumbnails

### ISSUE THREAD

**Issue by gggirlgeek** [jellyfin/jellyfin-media-player#38]
Hello,

Small gripe:  The font size on the thumbnails of unidentified files is too large to see the filename. This is not the case in Jellyfin Web. See screenshots for comparison. I don't know if there is a way to change this myself. I didn't find any font settings in the JellyfinMediaPlayer.config file.

Jellyfin Media Player thumbnails on home screen
![JellyfinMediaPlayer_WMbduryrJb (2)](https://user-images.githubusercontent.com/2652614/115071694-ce281500-9eb3-11eb-9024-fcff55f3e65e.jpg)

Jellyfin Web thumbnails on home screen
![firefox_h9qBjLkm4f](https://user-images.githubusercontent.com/2652614/115071723-d54f2300-9eb3-11eb-8972-4fe64ad73862.png)

Win10pro v2004
JMP v1.2.1 Desktop/Auto mode
Jellyfin Server v10.6.x on Ubuntu 18.6 managed seedbox

**Comment by iwalton3** [comment]
This looks like a bug in QT WebEngine. I have not found any references though for what might be causing the issue.

**Comment by iwalton3** [comment]
For this one I am not sure but it looks like another case of custom CSS.

**Comment by gggirlgeek** [comment]
I am now using version 1.6.0 but it still looks the same. However, now Jellyfin MPV Desktop looks this way after their latest update too. I believe the only reason Jellyfin Web has smaller text is because I can control it in the browser. So you're right. It's probably a CSS issue.

Can anyone help me find the specific line in the CSS that I need to change or add? I know just enough CSS to copy and paste what I'm told. :-)

Also, would this be on the server or Jellyfin Media Player client? (I am using a remote server on a seedbox.) I suppose I could edit either one.

**Comment by iwalton3** [comment]
Closing as stale. I don't see any CSS provided and troubleshooting these types of issues are low priority. If you want to disable the CSS causing the issue, there is a setting specific to your user that allows you to disable custom CSS provided by the server.
