### ISSUE TITLE
Doesn't run on Macos High Sierra 

### ISSUE THREAD

**Issue by satmandu** [jellyfin/jellyfin-media-player#380]
As I understand it GitHub only supports the last two versions of operating systems for building binaries. 

Could we have some external builders setup to build for older Macos versions?

(There are people I know with older machines that for instance cannot update past Macos High Sierra, which came out in 2017.)

**Comment by iwalton3** [comment]
I'm sorry but I don't have the resources to accomplish this. If someone else wants to maintain community builds for older operating systems that GutHub Actions does not support, feel free to.

**Comment by satmandu** [comment]
Would you be willing to accept builds for older versions of Macos?

**Comment by fcmonteiro** [comment]
I've been trying to compile with macOS 11.6.1 but I always have problems with the DQTROOT.
It's always complaining it can't find Qt5Core or other cmake files.
Any tips?

**Comment by iwalton3** [comment]
Read the CI flow here for specific commands: https://github.com/jellyfin/jellyfin-media-player/blob/884a2804e19a1102974240a39931366f2c73b5e0/.github/workflows/main.yml#L11

For installing QT, you can use this installer to avoid needing to create an account: https://github.com/miurahr/aqtinstall#install

**Comment by fcmonteiro** [comment]
Thanks!
With aqt was quite easy to build it.
If you want the dmg, I can share it.

This was what I used,
- Create a folder at: /Users/fcmonteiro/Documents/Qt/ and run the next command from that folder.
- aqt install-qt mac desktop 5.15.2 clang_64 -m qtwebengine

Then at the jellyfin folder,
cmake -GNinja -DQTROOT=/Users/fcmonteiro/Documents/Qt/5.15.2/clang_64/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=output ..

**Comment by satmandu** [comment]
@xeeeeeeeee Would you be willing to share the build dmg you made for older macos versions?

**Comment by xeeeeeeeee** [comment]
Sure, check this link.
https://mega.nz/file/oCAA2LjY#pkknS3boqtDYpckjnzSLSBSaN2moWzSGpb7v_EQGiWo

**Comment by satmandu** [comment]
Thanks!

Alas, I need a version for High Sierra (10.13)...

I guess I'll have to spin up a 10.13 VM to make that happen.

**Comment by sevenrats** [comment]
High Sierra has been EOL for more than 3 years, as such we will not be implementing support for it. Feel free to fork for this purpose.
