### ISSUE TITLE
Links to media in text

### ISSUE THREAD

**Issue by georgeeboy** [jellyfin/jellyfin-media-player#381]
In 'Suggestions' tab, "Becuase you like..." is shown
Make the text/name a clickable link to the media

(ᵔᴥᵔ)

**Comment by sevenrats** [comment]
hey thanks for your request! because you are actually asking for a feature to be implemented in  jellyfin-web (the UI component inside JMP) you will want to open this request at https://github.com/jellyfin/jellyfin-web or at features.jellyfin.org
As is, it can't be implemented here.
