### ISSUE TITLE
Don't consider libmpv a requirement for Qt6

### ISSUE THREAD

**Issue by fristhon** [jellyfin/jellyfin-media-player#386]
As you know Qt6 supports two different Multimedia backends and after Qt6.5 ffmpeg is the default backend.
So I think it's good to remove libmpv as a third party library when we want to port jellyfin to Qt6. it makes code base cleaner, more maintainable and also easier to build. is this possible from your POV ?

**Comment by iwalton3** [comment]
No MPV is a requirement. I highly doubt the Qt6 builtin framework even comes close to offering the same level of support for features that people have come to rely on.

**Comment by iwalton3** [comment]
To justify the above claim, here are some notable things that it _must_ support to maintain feature parity:
 - HEVC
 - Advanced Substation Subtitles
 - PGS Subtitles
 - Tone Mapping
 - Surround Sound (including downmixing and HDMI/Optical passthrough)
