### ISSUE TITLE
Skipintro causes player progress to be stuck

### ISSUE THREAD

**Issue by MarcelBochtler** [jellyfin/jellyfin-media-player#387]
**Describe the bug**
When Skipintro is enabled, the seekbar doesn't show playback time anymore, and playback progress is no longer persisted.
A restart of the application fixes the issue. Basically the first video always works fine, but the second one and all after that show this bug.
When Skipintro is disabled, I cannot reproduce this anymore.

**To Reproduce**
1. Enable Skipintro
2. Restart Jellyfin Media Player
3. Start a video (I guess one that has been progressed by skipintro before)
4. Stop the video by clicking the back button on the top left
5. Start the same video again. Now the seek bar only shows `--:--` on mouse over, the playback progress is no longer stored / reported to the server, the seek bar doesn't even move anymore.

**Expected behavior**
The seek bar should show the current progress of the video and store the progress on the server.

**Screenshots**
![SCR-20230303-vzp](https://user-images.githubusercontent.com/4022103/222839449-83d2a280-7f5d-4413-80d5-5773ba2fa107.png)

**Desktop (please complete the following information):**
 - Device: MacBook M1 Max 2021 14"
 - OS: macOS 13.2.1 arm 64
 - Version: Jellyfin Media Player 1.8.1
 - Installation Method: macOS installer

**Comment by iwalton3** [comment]
This will be fixed in the next release. You can download the fixed plugin and place it in your extension folder now to test the fix: https://raw.githubusercontent.com/jellyfin/jellyfin-media-player/b963836c18cf6d440979319bdb50d301158829ae/native/skipIntroPlugin.js

**Comment by iwalton3** [comment]
You can also download a test build here: https://github.com/jellyfin/jellyfin-media-player/actions/runs/4329606956

**Comment by MarcelBochtler** [comment]
Yes, that test build fixes the issue. Thanks for fast fix.
