### ISSUE TITLE
Aspect Ratio Controls are not showing up unlike with the Jellyfin web client

### ISSUE THREAD

**Issue by yuckdevchan** [jellyfin/jellyfin-media-player#388]
[jellyfinmediaplayer.log](https://github.com/jellyfin/jellyfin-media-player/files/10892096/jellyfinmediaplayer.log)

**Describe the bug**
Aspect Ratio Controls are not showing up even though they are in the web version. This is critical when viewing media recorded from TV for example.

**To Reproduce**
1. Watch something
2. Click on the cog icon
3. No aspect ratio controls! :(

**Expected behavior**
Aspect ratio controls in the QAM to let the user stretch or cover or fill the screen

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Jellyfin Media Player Flatpak 1.8.1
 - Installation Method: As a Flatpak through the Discover storefront

**Comment by iwalton3** [comment]
There are aspect ratio controls in client settings under the user menu. Let me know if those work for your use case. (I *may* be able to expose those into the cog menu if they work for you.)

**Comment by iwalton3** [comment]
This will be in the next release.
