### ISSUE TITLE
Support Apple Airplay option on audio and books player

### ISSUE THREAD

**Issue by stamatovg** [jellyfin/jellyfin-media-player#396]
Hello,
Expected button Airplay to be included on audio and books player
https://imgur.com/a/u3o4wdg

Actual button is available only for video player
https://imgur.com/7v695FB

**Comment by iwalton3** [comment]
Looks like a jellyfin-web issue. https://github.com/jellyfin/jellyfin-web/issues/3557

**Comment by stamatovg** [comment]
https://github.com/jellyfin/jellyfin-web/pull/4480
