### ISSUE TITLE
No titlebars on Gnome Wayland

### ISSUE THREAD

**Issue by ilya-zlobintsev** [jellyfin/jellyfin-media-player#40]
Gnome on Wayland requires applications to draw client-side decorations. Currently, running wayland-native on a gnome wayland session looks like this:
![image](https://user-images.githubusercontent.com/22796665/115103385-231e6680-9f5a-11eb-8469-7a3dfcf3316d.png)
I know this is a controversial decision from GNOME, but you can look at [Telegram](https://github.com/telegramdesktop/tdesktop) as an example of a QT app that implements CSD on wayland.

**Comment by iwalton3** [comment]
Wow I usually don't like to raise opinions on these things but that's really unfriendly to application developers. No other platform does this. Naturally anyone is free to PR something to resolve this as long as it doesn't affect platforms that draw decorations normally.

**Comment by DMouse10462** [comment]
I'm actually seeing decorations on my side running it from the .desktop file shipping with this application in the focal .deb package. Note in the terminal window that I'm running GNOME in a wayland session (though I can't vouch that the program is running as a Wayland app). The Qt Wayland platform plugin also appears to be supporting a fallback UI from as far back as this blog post from 2018:


![Screenshot from 2021-04-18 00-22-46](https://user-images.githubusercontent.com/2002606/115134271-b00a0400-9fdc-11eb-93ed-088be9f0cf18.png)

**Comment by tydog98** [comment]
Did you install with the Flatpak? The Flatpak doesn't give titlebars for me but the AUR package does.

**Comment by iwalton3** [comment]
I'm using the most recent SDK with Flatpak, but I have not even the slightest idea what might be happening.

**Comment by ilyazzz** [comment]
You can use `xprop` and try clicking on the window, if it doesn't show info after clicking on the window that means it's running on native wayland. You can also launch the app with `QT_QPA_PLATFORM=wayland` to force wayland, I've seen some QT apps fall back to xwayland when it's not specified. I've only tried the flatpak version on gnome (and also, flatpak forces wayland due to the `x11-fallback` permission being set, so without altering the permissions the app can't fall back to xwayland even if it wants to).

**Comment by a1ad** [comment]
So we cant have full screen when using the flatpak version in wayland?

**Comment by strugee** [comment]
The docs weren't very helpful on this so I filed a bug upstream: flatpak/flatpak-docs#250

**Comment by TingPing** [comment]
Just to be clear about this behavior:

- Wayland, the protocol, has no requirement that compositors render window decorations
- There are optional extensions to *request* the compositor render window decorations
  - GNOME does not and will not, at least in the short term, support this
- Flatpak isn't relevant here, except for the fact it defaults to the Wayland backend, when Qt normally defaults to X11
  - This can be changed in the package if so desired, at least for now

The solution is likely just the application rendering its own titlebar, I'm not familiar with Qt but I assume thats just another widget?

**Comment by freshgum-bubbles** [comment]
>  - Flatpak isn't relevant here, except for the fact it defaults to the Wayland backend, when Qt normally defaults to X11
>    - This can be changed in the package if so desired, at least for now

@TingPing, It seems strange to suggest the use of X11 to work around the lack of SSD's in GNOME Wayland. 
Perhaps there's a middle ground here that wouldn't meaningfully impact performance of JMP, while also requiring 
the least implementation work on Jellyfin's part.  After all, window decorations have been provided by the WM for well over 50 years now.

For the record, JMP also works totally fine on KDE, Sway, etc.: it's got the title bar, window decorations, the works. Would there maybe be something GNOME-specific to apply here as a patch?

**Comment by TingPing** [comment]
You implement CSD. That is all you can do. Again Qt surely has wigetry for this.

**Comment by techtino** [comment]
Qt supports client side decorations for sure. 

See here:
https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications#Qt_apps_run_on_GNOME_Wayland_have_a_non-matching_window_decoration_look,_even_after_setting_a_Qt_theme

Can even get it to match adwaita's title bar if you want.

For some reason the QT in flatpak doesn't do this at all. AUR package obeys the system QT ofc so it works.

**Comment by TingPing** [comment]
Again, I think Qt defaults to X11, but you could verify that.

The flatpak just defaults it to Wayland. I do not believe it has other meaningful changes.

**Comment by sourpatched** [comment]
Another comment from someone was to use sudo flatpak override --nosocket=wayland com.github.iwalton3.jellyfin-media-player command. Worked for me

**Comment by TingPing** [comment]
I've simply disabled Wayland support on the flathub package. If upstream ever wants to support it let me know to re-enable it.

**Comment by julianschacher** [comment]
I think this issue can be closed.
After updating the Jellyfin Media Player Flatpak yesterday, I noticed that I now get a titlebar while running natively under Gnome Wayland (not XWayland).

**Comment by iwalton3** [comment]
Nice. If this issue pops up again please comment.
