### ISSUE TITLE
Updating Flatpak to 1.9.0 prevents videos from playing

### ISSUE THREAD

**Issue by Zoarial94** [jellyfin/jellyfin-media-player#401]
**Describe the bug**
Updating the Flatpak version to 1.9.0 on linux prevents any videos from being streamed. The loading animation spins forever after clicking play. This does not happen on the web client. Downgrading to 1.8.1 resolves the issue. 

![jellyfin-uncaught-exception-in-promise](https://user-images.githubusercontent.com/20785870/225383417-a0be3e38-75b9-46df-bde2-195b18d1d770.png)
[jellyfinmediaplayer.log](https://github.com/jellyfin/jellyfin-media-player/files/10982336/jellyfinmediaplayer.log)

**To Reproduce**
1. Update from 1.8.1 to 1.9.0
2. Start any video

**Expected behavior**
The video starts playing nearly immediately. This is the behavior on the android player and when downgrading to 1.8.1. 

**Desktop (please complete the following information):**
 - OS: Fedora 36 and SteamOS on the Steam Deck
 - Version 1.9.0
 - Installation Method Flatpak

**Additional context**
I run my Jellyfin traffic through Nginx with a Let's Encrypt cert, but it appears the linux client uses the local address and 8096 port.

**Comment by iwalton3** [comment]
I have been having issues with Jellyfin giving 400 errors for valid profiles at times while debugging. (I thought I made it so it didn't happen with default settings.) What is the media info for the video? Did you enable any of the "force transcode" options that are new in this release?

Also try sending your Jellyfin Server log.

**Comment by cegli** [comment]
I also have the same issue.  Reverting to 1.8.1 fixes it.  Uninstalling and reinstalling 1.9.0 did not.

**Desktop (please complete the following information):**

    OS: Windows 10
    Version: 1.9.0
    Installation Method: x64 installer

**Comment by iwalton3** [comment]
One thing the people having this issue can try is editing nativeshell.js to remove:
```
        {
            'Type': 'Video',
            'Conditions': [
                {
                    'Condition': 'NotEquals',
                    'Property': 'VideoRangeType',
                    'Value': 'DOVI'
                }
            ]
        }
```

I would also greatly benefit from Jellyfin server logs if you are also having the 400 error on PlaybackInfo issue.

**Comment by Zoarial94** [comment]
Here's the media file I tried. I have not touched any the new transcoding options. Unfortunately I am on a trip out of town and I won't have much time at all to troubleshoot for now. 

![Screenshot_20230315_234517](https://user-images.githubusercontent.com/20785870/225509077-1bc37845-d521-4493-88f2-8af79dfd464e.png)

**Comment by theg721** [comment]
I'm having the same issue on 1.9.0 on Windows 11 via the x64 installer.

**Comment by iwalton3** [comment]
Let me know if this test build fixes anything: https://github.com/jellyfin/jellyfin-media-player/actions/runs/4457772698

**Comment by aznanimekid** [comment]
> Let me know if this test build fixes anything: https://github.com/jellyfin/jellyfin-media-player/actions/runs/4457772698

This fixed my issue after I updated to 1.9.0 and googled my way here. No idea if my error was the same as I have no logs but the problem (infinite loading symbol) was as described. I am on Windows 10 using the x64 installer.

**Comment by aznanimekid** [comment]
> Let me know if this test build fixes anything: https://github.com/jellyfin/jellyfin-media-player/actions/runs/4457772698

This fixed my issue after I updated to 1.9.0 and googled my way here. No idea if my error was the same as I have no logs but the problem (infinite loading symbol) was as described. I am on Windows 10 using the x64 installer.

**Comment by iwalton3** [comment]
So it is probably the Dolby vision transcode rule. I wonder if the people running into this problem have outdated servers or if the transcoder rule just randomly causes it to fail. (But of course in a way that evaded all of my tests.)

**Comment by Mengine** [comment]
running 10.8.9 on the server. flatpak clients have this issue after updating to 1.9.0, but also with older clients actually

**Comment by Zoarial94** [comment]
Here's a short log from the latest Docker image. I stopped and started my container, waited for the server to start up, viewed the log in the web interface, and then started an episode from the Flatpak application with version 1.9.0. It doesn't appear to have added anything notable to the log after clicking play. Am I looking at the right log?

[jellyfin.log](https://github.com/jellyfin/jellyfin-media-player/files/11045201/jellyfin.log)

**Comment by iwalton3** [comment]
Yeah I don't see anything. There might be something in devtools or you could try a higher log level.

**Comment by iwalton3** [comment]
Since you have devtools working maybe see if you can send me the request and response pair for the PlaybackInfo request?

**Comment by Zoarial94** [comment]
Set logging to debug, but it doesn't seem to have added anything useful either. Let me look at devtools again.

I added the following marker in the file:
`============== STARTED VIDEO HERE ==============`

[jellyfin.log](https://github.com/jellyfin/jellyfin-media-player/files/11045388/jellyfin.log)

**Comment by iwalton3** [comment]
Wow yeah that log is useless.

**Comment by Zoarial94** [comment]
Here's a section of the HAR file Chrome provided. It is the only real quest that went through when clicking start. This probably has the answer you're looking for. 

[jellyfin-failed-request.txt](https://github.com/jellyfin/jellyfin-media-player/files/11045429/jellyfin-failed-request.txt)

**Comment by iwalton3** [comment]
The log file says that the property VideoRangeType could not be processed in the CodecProfile. I know for a fact that is supported because I tested it against my server.

Are you on an outdated version of the Jellyfin server?

**Comment by Zoarial94** [comment]
I am up to date with jellyfin/jellyfin:latest

**Comment by Zoarial94** [comment]
I see now that the docker version is a fair amount behind the true latest of 10.8.9.

**Comment by Zoarial94** [comment]
Actually, the problem was I don't know how to use docker. I ran a new container and it is now at 10.8.9. Issue has been resolved.
