### ISSUE TITLE
Raspberry pi4b Raspbian custom build error (because 1.7.1 version stopped working)

### ISSUE THREAD

**Issue by mpegyna** [jellyfin/jellyfin-media-player#408]
I sucessfully build JMP v 1.7.1 and used it about half a year with very good performance and user satisfaction on Raspberry pi4b with GUI Raspbian. Today I wanted to play some movie again, but got stuck with a window _"There's new 1.9.0 version of JMP"_. Clicking on _"Ignore"_ or _"Download"_ doesn't work. Can't execute it with TV remote nor with mouse and keyboard.

I managed to bypass this update window with reloading and pressin Esc. But I can't access almost any link in JMP GUI, can't access movies nor play them.

So I tried to build the new version. Unfortunately it doesn't work like the 1.7.1 did. When I got to the line `sudo ./install` line (after `./rebuild -j4`) I got this error message: `scripts/mvp-install: 8: meson: not found`.

I installed meson and ninja, searched the scripts if I could run the command separtately but with no luck. How to overcome this error? Do you know what is wrong? 

_I would go back to the 1.7.1, but I don't know how to build it when it's archived and I'm not also sure if it wouldn't bug again with the autoupdate to 1.9.0. Now I'm stucked with quarter-built 1.9.0, but can only run still the bugged 1.7.1. Would be glad for suggestions for some solution._

**Comment by iwalton3** [comment]
Make sure the meson tool is runnable from the command line. It should be available in the PATH. You could also probably skip that step and keep the existing libmpv you have installed.

**Comment by iwalton3** [comment]
Also you can disable the update notifier in the config  see the readme for the config location. It has been fixed in 1.9.0 so you shouldn't have the problem if you do update in the future.

**Comment by mpegyna** [comment]
Thanks for quick response. Meson is runnable from command line, I added it to PATH. I tried to run it in command line, but I'm not acustomed with the "$@" parameter notation from script.

I surely will disable the autoupdate when/if I manage to compile the new version.

If I were to skip that step, shouldn't I skip some more lines? Where should I continue with the commands?

**Comment by iwalton3** [comment]
Resume at the second `cd ~/jmp/`

**Comment by mpegyna** [comment]
Got it. Version 1.9.0 sucessfully installed and running. Thanks a lot!
I saw disabling autoupdate in JMP GUI in _device settings_. I assume that is what you meant and I don't need to edit some config files?

**Comment by iwalton3** [comment]
Yes although the lockup issue with the update notifier is fixed in 1.9.0.
