### ISSUE TITLE
Can't start JellyfinMediaPlayer 1.9.0

### ISSUE THREAD

**Issue by Ch4m311eom** [jellyfin/jellyfin-media-player#410]
I can't start JMP since I updated to 1.9.0. Now even if I downgrade it to 1.8 it's not working. I was trying to clean registry, remove all Jellyfin catalogs etc. but still when I open JMP it shows blank window with JMP tittle and disappears. 
[JellyfinMediaPlayer.log](https://github.com/jellyfin/jellyfin-media-player/files/11071969/JellyfinMediaPlayer.log)

**Comment by Ch4m311eom** [comment]
Ok, I found the problem. For some unknown reason it's caused by CUDA dll in nVidia Geforce driver.
After I uninstalled GeForce driver it works but it's not a perfect solution. :D
Below Windows log but it's translated from Polish so keep in mind that it might be translated wrong.

Faulting application name: JellyfinMediaPlayer.exe, version: 0.0.0.0, time stamp: 0x640e31db Faulting module name: nvcuda64.dll, version: 31.0.15.3129, time stamp: 0x640826be Exception code: 0xc0000409 Error offset: 0x000000000053c834 Faulting process ID: 0x281c Faulting application start time: 0x01d96009f1f228d5 Faulting Application Path: D:\Program Files\Jellyfin\Jellyfin Media Player\JellyfinMediaPlayer.exe Faulting module path: C:\Windows\system32\DriverStore\FileRepository\nv_dispig.inf_amd64_059948e396d205d5\nvcuda64.dll Report ID: 51d12662-3b5c-44fe-b0ce-5d62b4811112 Full name of the faulting package: Application ID relative to the faulting package:

**Comment by Beck-919** [comment]
Please check #395 for a temporary workaround. If it works for you, take note that the fix gets undone by even a small chenge to the software stack (eg: version update or even Windows update).

I believe a permanent fix lies in figuring out Windows default behaviour for picking the correct display driver for applications (case in point: JellyfinMediaPlayer) based on the current power profile.

**Comment by nyhjw** [comment]
- My computer has not been shut down for a long time, and after an automatic restart yesterday, I encountered the following problem: when I open an application, it starts to load but then freezes and crashes a few seconds later. It's possible that Windows automatically installed a patch or update that caused the issue.
- Here is my system information.
  - Operating System: Windows 10 Enterprise 22H2 with Windows Feature Experience Pack 120.2212.4190.0.
  - Hardware Information:
    - CPU:AMD Ryzen 7 2700X Eight-Core Processor            3.70 GHz
    - GPU:AMD 5700XT

**Comment by ne7erland** [comment]
The same problem bothered me for half a month. Until I manually delete AppData\Local\Jellyfin Media Player after uninstalling. Then reinstall it just fine.

**Comment by theIsaia** [comment]
Same problem for me, didnt have it until I switched to an AMD 7900 XT, uninstalled all Nvidia drivers (there is no trace of nvidia under installed apps in crontrol panel) and installed the approriate AMD once, but judging from event viewer its still trying to use the Nvidia cuda dll.
Tried deleting appdata files, uninstall -> restart pc -> reinstall 1.7.1, still same issue.
Tried power saving setting I saw suggested in another thread.

AMD Radeon RX 7900 XT
Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz   3.80 GHz
Windows 11 Education, 22H2, build 22621.1555, experience: Windows Feature Experience Pack 1000.22640.1000.0

![image](https://user-images.githubusercontent.com/59561870/235515029-d1b46b3b-11de-467c-b3fd-4bdb0f018a21.png)

**Comment by ovingiv** [comment]
> uninstalled all Nvidia drivers

Please use Display Driver Uninstaller and try again. [DL Here](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html#:~:text=maximum%20cleaning%20options.-,Download%20Locations,-Download%20Mirror%20EU)

**Comment by Zuuushiiihokkiii** [comment]
I had this problem too. My system has an integrated AMD GPU, an Intel ARC GPU and occasionally an additional Nvidia GPU when I need to use software that requires CUDA. When the Nvidia GPU is not present, then Jellyfin Media Player does not work unless I uninstall the Nvidia driver.

**Comment by Tubscart** [comment]
Having the same problem, system has intergrated AMD GPU and an NVIDIA GPU, whenever not using the dGPU, Jellyfin will crash. All workarounds presented haven't worked.

**Comment by alexandrezhang** [comment]
I solved this in my Laptop,if you have an intergrated AMD GPU and a NVIDIA GPU,try modify"\Users\XXXX\AppData\Local\JellyfinMediaPlayer\jellyfinmediaplayer.conf"
like this:
"useOpenGL": false,

Hope it will be helpful to you.

**Comment by Beck-919** [comment]
@Ch4m311eom, could you check if the latest version fixes this issue for you? (It fixed for me: #395)
If not, try @alexandrezhang's fix.

Either way, please update on the status. If any of the above works, please close the issue.

**Comment by ZummiGummi** [comment]
The fix for me was to remove old graphics card entries.
Right click Start, Device Manager
View, Show Hidden Devices
Expand Display Adapters, Right click the grey Nvidia cards, Uninstall Device, tick the box for removing drivers.
**Don't uninstall the Display Adapters that aren't grey**

**Comment by sevenrats** [comment]
Closing this. Please open a new report if this issue persists in the current version.
