### ISSUE TITLE
Can't play any video on version 1.9

### ISSUE THREAD

**Issue by eliasrk** [jellyfin/jellyfin-media-player#417]
i cant play any videos after installing 1.9 . i can open the app but every time i click on a video i just get that spinning wheel in the middle. i have tried multiple media types i have uninstalled and reinstalled but nothing fixes it i have tried 1.8.1 again but it now breaks after a few uses. I am running windows 10 and currently using the web version but cant run all types of media through it. oh and my server is 10.8.0

FIXED : just required a update of my jellyfin server

**Comment by SCArnoldos** [comment]
Same issue here. No longer being able to play any video.

**Comment by iwalton3** [comment]
Make sure your server is on the latest version available. There was an issue with profile support. See https://github.com/jellyfin/jellyfin-media-player/issues/401

**Comment by Jessicawyml** [comment]
Same issue here. No longer being able to play any video.

**Comment by eliasrk** [comment]
Just required my server to be updated then worked like a charm thanks @iwalton3
