### ISSUE TITLE
Jellyfin Windows Client no audio when original audio codec was FLAC and when the video is transcoded

### ISSUE THREAD

**Issue by SandboChang** [jellyfin/jellyfin-media-player#423]
Log file:
[JellyfinMediaPlayer.log](https://github.com/jellyfin/jellyfin-media-player/files/11253161/JellyfinMediaPlayer.log)

Description:
When a video with an audio codec being FLAC, and when the video is transcoded (due to a lower set bitrate by the client),
there is no audio output in the client.

This does not happen if:
- The video is direct play
- The original audio codec of the video is not FLAC, e.g. an AAC video can be transcoded while keeping audio working
- Web client does not have the same issue, only Windows client so far shows the issue

**To Reproduce**
Play a video with original audio codec being FLAC under Windows Jellyfin client 1.9.0 x64 on Windows 11.
Make sure there is audio to begin with.
Try to lower the bit rate such that it must transcode the video.
No audio is heard from the video when watching the video with transcoding.

**Expected behavior**
The audio of the video should work with video transcoding in the Windows Jellyfin client.

**Desktop (please complete the following information):**
 - OS: Windows 11 x64
 - Version 22621.1555, 2H22
 - Installation Method : windows installer using client downloaded from official Jellyfin github
 - Client version is 1.9.0 x64

**Additional context**
I also tried different settings in the Client setting --> Audio, changing device type and device did not do anything to solve this problem.

**Comment by live4ever** [comment]
Also FLAC isn’t working on Jellyfin for Kodi for me. Both force transcode and direct play. Kodi gets an “undefined” audio stream.

**Comment by iwalton3** [comment]
I removed `flac` from allowed codecs for video transcoding. Let me know if there are still issues. Honestly even if we could direct stream flac while transcoding, since the main reason to transcode is to reduce bitrate, that seems silly.

**Comment by SandboChang** [comment]
> I removed `flac` from allowed codecs for video transcoding. Let me know if there are still issues. Honestly even if we could direct stream flac while transcoding, since the main reason to transcode is to reduce bitrate, that seems silly.

Thanks for the follow-up, it sounds like this change mostly just avoid the problem? Was there any reason transcoding flac will disable audio (just for Windows client)?

**Comment by iwalton3** [comment]
I don't think HLS supports FLAC. That's likely why it is broken.
