### ISSUE TITLE
Typing automatically brings out search

### ISSUE THREAD

**Issue by genefyx** [jellyfin/jellyfin-media-player#429]
**Is your feature request related to a problem? Please describe.**
Typing for media does not auto search without manually clicking first.

**Describe the solution you'd like**
When browsing for media on the desktop, It would be nice for typing to bring out autosearch.
If not then possibly a command like ctrl + enter.
- A general keyboard management & keyboard shortcuts setting would also be useful

**Comment by iwalton3** [comment]
You should log this against jellyfin-web, as JMP uses the upstream webclient unmodified.
