### ISSUE TITLE
Adding chapters to the seek bar and the ability to skip backwards and forwards.

### ISSUE THREAD

**Issue by PterahNova** [jellyfin/jellyfin-media-player#43]
As above, like in the mpv media player used in Jellyfin Desktop adding this functionality would be a great addition.

**Comment by iwalton3** [comment]
This is more of a feature request for jellyfin-web.

**Comment by PterahNova** [comment]
Understood :) I will request there, thank you.

**Comment by fixel99** [comment]
As far as I'm aware, this functionality was added to jellyfin-web, but not to the media player?

**Comment by AArnott** [comment]
I don't see chapter marks or chapter navigation options in Jellyfin Media Player (Windows app) or the web player. :(

**Comment by fixel99** [comment]
> I don't see chapter marks or chapter navigation options in Jellyfin Media Player (Windows app) or the web player. :(

Ah my mistake then. I saw a merged pull request for the feature on the web app repo so had assumed. I'm actually using Emby and not jellyfin so couldn't check.
