### ISSUE TITLE
Add setting for custom options for mpv

### ISSUE THREAD

**Issue by dharmik2319** [jellyfin/jellyfin-media-player#441]
**Is your feature request related to a problem? Please describe.**
Recently, when starting an h264 8-bit video on my AMD iGPU with `mpv`, I faced a black screen with only subtitles and audio. See [https://github.com/mpv-player/mpv/issues/3714](https://github.com/mpv-player/mpv/issues/3714). I noticed that i faced the same problem with Jellyfin Media Player as well and was getting the same error message. I was able to solve the mpv issue by commenting out the `mpv.conf` file, which had just one line: `hwdec=vaapi`. Another workaround was using `--no-config` in the cli.

I copied the `mpv.conf` file to the directory containing `jellyfinmediaplayer.conf` but the problem persisted and the `mpv.conf` file was getting overridden.

**Describe the solution you'd like**
Give the user an option for custom mpv options, or even better, an option to select another player.

**Describe alternatives you've considered**
As stated before, the `mpv.conf` got overridden

**Comment by kradear** [comment]
mpv.conf ignores most if not all commands I use on MPV for JMP.

I've read of users being able to use settings as sub-pos or volume-max to modify JMP, but it's current version doesn't seem to take any them.

I've looked around but found no way of setting these or adding/modifying input settings for JMP. The keyboard.json options don't seem to take effect if not using the "TV mode" of JMP.

I couldn't find talks about adding these features to the app, but it would a first step on replacing external players for good.

**Comment by satmandu** [comment]
The `mpv.conf` settings appear to be read here: https://github.com/jellyfin/jellyfin-media-player/blob/bc0ec5a099a7d78c467211ce438e0165a1de71c1/src/player/PlayerComponent.cpp#L90

```c++
  // Configuration properties defined in the mpv.conf will override our
  // hardcoded properties below.
  mpv::qt::set_property(m_mpv, "config", "yes");
  mpv::qt::set_property(m_mpv, "config-dir", Paths::dataDir());
```

If that's not working, maybe you could try some debug code to make sure the right dir for the mpv.conf file is being used?

**Comment by sevenrats** [comment]
this functionality works. some items like subposition and size are overruled by client settings. that discussion is happening here:
#474

**Comment by sevenrats** [comment]
#543
