### ISSUE TITLE
Support mDNS

### ISSUE THREAD

**Issue by WoxWik** [jellyfin/jellyfin-media-player#447]
**Is your feature request related to a problem? Please describe.**
When I try to hit my jellyfin server's 'example.local' domain name in the web browser it works fine. However, it does not work in the linux app, or on the ipad etc. Therefore I have to manually set host file records, which I'm not always able to do.

**Describe the solution you'd like**
The apps should support mdns, like the web browser does.

**Describe alternatives you've considered**
hosts file

**Comment by sevenrats** [comment]
it works normally for me, ubuntu on server and client.

**Comment by sevenrats** [comment]
I've been unable to produce any examples of mDNS not working.
The only caveat is that sometimes its disabled on windows. just turn it back on.

**Comment by ensingerphilipp** [comment]
This happens to me as well but sometimes works and then doesnt anymore - something is wonky here but im not sure its even inside jellyfin-media-player where the probelms lie

**Comment by sevenrats** [comment]
that is just the nature of mdns. sometimes you have to try twice, that has nothing to do with JMP.
