### ISSUE TITLE
frame dropping after the pc upgrade the new version of graphics card.

### ISSUE THREAD

**Issue by SSrFreak** [jellyfin/jellyfin-media-player#483]
After i upgraded the NVIDIA graphics card to the newest version (537.13) on both my laptop and my desktop. i have a big frame dropping on the jellyfin media player when i minimize the window, happened  on both of my laptop and desktop. Please help me.It's really mind boggling.

**Comment by sevenrats** [comment]
537 is an obsolete GameReady release which there is no way for us to test support for.
Try using an official driver version like 535 or 545 and open a new issue if this does not work.
