### ISSUE TITLE
JellyginMP is not being recognized as a media player by the OS.

### ISSUE THREAD

**Issue by AlperShal** [jellyfin/jellyfin-media-player#485]
**Is your feature request related to a problem? Please describe.**
Keyboard/mouse events like "play, pause, stop, next, prev..." do not work. This is because Jellyfin doesn't register itself as a media player to the OS/doesn't use proper APIs or calls while playing or something like that.

**Describe the solution you'd like**
I don't have any idea how OS determines this so not sure of the solution.

**Describe alternatives you've considered**
There isn't really an alternative to this.

**Additional context**
OS: Linux/Arch/EndeavourOS | Kernel 6.4.12-arch1-1 | KDE 5.27.7 | Qt 5.15.10
![image](https://github.com/jellyfin/jellyfin-media-player/assets/34231577/d9cb70e1-cbf3-4116-a3b1-7e9172e6295e)

**Comment by natperron** [comment]
To my understanding (which may be incorrect), it needs to support the MPRIS D-BUS Interface. Here's the specification in  case anyone needs it: https://specifications.freedesktop.org/mpris-spec/latest/
(Not sure if this is very helpful, sorry for my lack of knowledge :stuck_out_tongue: )

**Comment by AlperShal** [comment]
Yeah this looks like it. Interesting how it didn't get any updates since
2012.

**Comment by natperron** [comment]
@AlperShal You can look at https://github.com/jellyfin/jellyfin-media-player/issues/3 for a workaround.
This seems to be a duplicate issue, so you can probably close it?

**Comment by AlperShal** [comment]
> @AlperShal You can look at https://github.com/jellyfin/jellyfin-media-player/issues/3 for a workaround.
> This seems to be a duplicate issue, so you can probably close it?

Oh yeah looks like this is duplicate missed that one. Thanks for mentioning!
