### ISSUE TITLE
Keyboard short to stop playing and go Back

### ISSUE THREAD

**Issue by valankar** [jellyfin/jellyfin-media-player#494]
**Is your feature request related to a problem? Please describe.**
There should be a keyboard shortcut to go 'Back', i.e. the left arrow at the top left of the media player.

![image](https://github.com/jellyfin/jellyfin-media-player/assets/31250800/8f47a5e7-cad5-428a-93f4-baef22f1715c)

**Describe the solution you'd like**
ESC or B to go back and exit playing the current video.

**Comment by Fdmt3ch** [comment]
Left ALT+Left / Right arrow works for me on Windows and Linux 🧐 @valankar 
(Works the same in web browsers, what JFM basically is).

**Comment by valankar** [comment]
Ah great, thanks!
