### ISSUE TITLE
Server saved twice with local ip and domain

### ISSUE THREAD

**Issue by alSeveR** [jellyfin/jellyfin-media-player#50]
When I am connected to my local network I prefer to connect with the ip and port of the server and use the domain with https when I am outside. The problem is that it recognizes the server with the same name and I have to add it again with every change.

Isn't it possible to have the same server saved twice with local ip and domain?

Thanks in advance.

**Comment by iwalton3** [comment]
I am pretty sure it'll automatically connect using the local IP if you use the https address when you are on the local network.

Adding the same server multiple times would be a feature request for jellyfin-web.

**Comment by alSeveR** [comment]
> I am pretty sure it'll automatically connect using the local IP if you use the https address when you are on the local network.

If so, that's perfect. Thank you.
