### ISSUE TITLE
Flatpak - how to make server service auto start with the OS?

### ISSUE THREAD

**Issue by RDKRACZ** [jellyfin/jellyfin-media-player#512]
And is it possible to do it without opening the GUI or should I instead install the "regular" package for this functionality?

**Comment by thornbill** [comment]
This repo is for the Jellyfin Media Player desktop application. The server flatpak is a community maintained project. I believe the correct place to file issues for it would be here: https://github.com/flathub/org.jellyfin.JellyfinServer
