### ISSUE TITLE
List of mpv.conf options honoured by JMP

### ISSUE THREAD

**Issue by Rivers47** [jellyfin/jellyfin-media-player#527]
There are a lot of options ignored by JMP, and testing one by one which ones are honoured  is difficult, analyzing the source code is also hard for the average user.

For example, I realized that tscale is not recognized by JMP, (on that regard I am not sure if interpolation is supported at all).

Can we have a list of mpv.conf options supported by JMP?

While mpv-shim works, it is quite an overkill if JMP can support the common options.

**Comment by sevenrats** [comment]
Hi! thank for this report. JMP does not actually intercede with this file at all. Whatever options are supported by the packaged version of mpv will be supported.  If you want more recent options while you wait for a new release, you can build JMP from source with whatever version of MPV you want.
