### ISSUE TITLE
control

### ISSUE THREAD

**Issue by Itachi0833** [jellyfin/jellyfin-media-player#530]
hello，May I ask why I opened the game controller on the desktop in Win11, but the controller on the Xbox360 protocol is invalid? What should I do, thank you!

**Comment by Rainbowlemon** [comment]
Not entirely sure if it's related, but I'm also trying to use a game controller (but on Linux) using Jellyfin Media Player and it just doesn't respond. The controller definitely works with Linux since I can use it on RetroArch and Kodi without issue.

**Comment by sevenrats** [comment]
this issue is a bit ambiguous.  @Itachi0833 can you please elaborate on your setup, your goal, and what your issue is. @Rainbowlemon i would open a new issue for your experience if you have not done so already.

**Comment by Itachi0833** [comment]
In version 10.20, when playing a game preview video, the background sound will stop playing. When I stop playing the game preview video, the background sound will continue to play from the stopped time. In version 10.30, the background sound starts playing from 0:00, which is important to me because my background sound starts playing at the 15th second




---Original---
From: "Seven ***@***.***&gt;
Date: Fri, Jan 5, 2024 14:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jellyfin/jellyfin-media-player] control (Issue #530)




 
this issue is a bit ambiguous.  @Itachi0833 can you please elaborate on your setup, your goal, and what your issue is. @Rainbowlemon i would open a new issue for your experience if you have not done so already.

**Comment by Itachi0833** [comment]
I want to use a controller to control Jellyfin, but the option for the controller is turned on in the options, but it doesn't work

**Comment by sevenrats** [comment]
@Itachi0833 It's not super clear whether or not this is a bug.  can you stop by our chat spaces to troubleshoot this?

**Comment by Itachi0833** [comment]
Sorry, English is not my native language, so it's not possible

**Comment by Itachi0833** [comment]
If possible, please make it like Kodi, with the handle perfectly controlled

**Comment by sevenrats** [comment]
try switching your client into TV Mode and restarting the software.

**Comment by Itachi0833** [comment]
Excuse me, is it the TV mode on the desktop? Where is the TV mode set up?

**Comment by mark-monteiro** [comment]
@Itachi0833 You can switch the display mode from the settings:  Settings >> Display >> Display Mode >> TV 

I also had this same issue and was able to resolve it by switching the display mode to TV. 

I'm not sure if it's intended behaviour for controller to only work for the TV display mode. If that is the intended behaviour then I think the help text here should be updated to indicate that. Something like this

```diff
-Listen for input from any connected controllers.
+Listen for input from any connected controllers when the 'Display Mode' is set to 'TV'.
```

![image](https://github.com/jellyfin/jellyfin-media-player/assets/2626103/e4f690d5-34d5-4a17-b511-c0f1c6207ee3)

**Comment by Itachi0833** [comment]
@mark-monteiro，thank you very much！

**Comment by mark-monteiro** [comment]
@sevenrats Looks like this can be closed 👍
