### ISSUE TITLE
Some UI and Chinese translation issues

### ISSUE THREAD

**Issue by ahaoboy** [jellyfin/jellyfin-media-player#531]
**Describe the bug**
After setting both the language and timezone to Chinese, the UI isn't fully adapted.

- Right-clicking in the blank space on the homepage remains in English. Additionally, on my dual-screen computer, only the main screen displays the right-click menu. When dragging the player to the secondary screen, clicking has no response.
![image](https://github.com/jellyfin/jellyfin-media-player/assets/19884146/bafdc52d-2d93-4da4-9766-4a85bbbe0df0)
main screen
![动画](https://github.com/jellyfin/jellyfin-media-player/assets/19884146/b843b812-b093-462b-9683-c72c436ce02d)
secondary screen
![动画1](https://github.com/jellyfin/jellyfin-media-player/assets/19884146/0bb28b21-0e3b-4578-a5a9-7bd579bc1097)

- When playing videos, the translations for 'Next Video' and 'Previous Video' are not accurate, and the prompt messages should be in a single line. In Chinese, 'Next Video' is commonly translated as '下一集,' while 'Next Audio' is translated as '下一首' or '下一曲'.
This translation issue also exists in the Jellyfin web, possibly due to the use of the same translation database.
It should be translated as '下一集'
![image](https://github.com/jellyfin/jellyfin-media-player/assets/19884146/0a729177-083d-4d6d-936a-e519d1b1b4da)
The prompt should be displayed in a single line.
![image](https://github.com/jellyfin/jellyfin-media-player/assets/19884146/0b075762-5052-4d4b-bf9b-a2bf1bd89194)

- When I am playing only one video, or when I use 'Play All from Here' and I am on the first or last video, the 'Previous Episode' and 'Next Episode' buttons should be disabled accordingly. Otherwise, having an active button that doesn't respond to clicks can confuse users and make them uncertain about where the issue lies, this issue also occurs in Jellyfin web.

Jellyfin Web & jellyfin-media-player
![image](https://github.com/jellyfin/jellyfin-media-player/assets/19884146/212344fa-876e-48bb-a0f6-0a27f91742d6)
Jellyfin Vue
![image](https://github.com/jellyfin/jellyfin-media-player/assets/19884146/ffc399d2-f77b-4267-9e60-aef730abe1d6)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Win 11
 - Version [e.g. 22]: 23H2
 - Installation Method [e.g. windows installer] github windows installer

**Comment by sevenrats** [comment]
should already be fixed in weblate, pending release.
