### ISSUE TITLE
Scroll bar 

### ISSUE THREAD

**Issue by MRDJellyfin** [jellyfin/jellyfin-media-player#54]
First of all, thank you for the excellent work on this new version of "Jellyfin Media Player", I know that there is a great way ahead and that the missing things or the things that need to be corrected will come out little by little so that every day it works better.  For which I want to point out that in my case:

The scroll bar that appears on the right when you want to use it to scroll to search for a collection does not work in any sense (neither up or down) in Windows 10

**Comment by iwalton3** [comment]
Does this also occur on the web client or just on Jellyfin Media Player?

**Comment by MRDJellyfin** [comment]
Only in Jellyfin Media Player

**Comment by MRDJellyfin** [comment]
Thanks for your quick response

**Comment by MRDJellyfin** [comment]
Sorry I'm wrong,  you move the vertical bar if you select the arrows that are up and down and also if you select a space between these arrows, the error is (rather better) in that, if you try to move the bar Directly, it does not move, in the SHIM version if the bar moves (I have a bad habit of always selecting the bar because it is bigger than the arrows and faster when doing it, an apology again).

**Comment by sevenrats** [comment]
I can't reproduce this stale issue on any platform. Please open a new report if you still experience this issue on a modern version of JMP.
