### ISSUE TITLE
Movie title filter "#" does not work

### ISSUE THREAD

**Issue by kbrannen** [jellyfin/jellyfin-media-player#545]
**Describe the bug**
If you select movies from the main screen, on the right are title filters by first letter. The very first "button" is "#" for the movies beginning with a number. If you select that, then you get a blank screen, even though I have movies like "2001", "2010", etc.

This is from the Linux flatpak install and version 1.9.1. Not sure what version of server, but it was installed within the last month so it should be recent. The server is the app/module on a Synology box. I'd check logs for jellyfinmediaplayer, but I don't see them in either of the places listed.

I also use the Roku app client and find that it has the same problem, if that helps; so maybe it's the jellyfin server with the issue. (OK, the Roku client really says "This CollectionFolder contains no items", but the point is that it doesn't show any titles/moves either.)

**Expected behavior**
I expect clicking on the "#" to show the moves that begin with a number.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 22.04
 - Version: 1.9.1
 - Installation Method: flatpak

**Comment by sevenrats** [comment]
Hi, thanks for your report.!  This is not a bug. Please stop by the chat spaces and we will help you with your support request.
