### ISSUE TITLE
Ability to change subtitle font on Windows

### ISSUE THREAD

**Issue by coolpringles** [jellyfin/jellyfin-media-player#548]
I really like Jellyfin and I think it's a great way to keep track of what I'm watching but I really prefer the default subtitle font in VLC and am wondering how to change them to look like that in the Jellyfin Media Player app. I tried with a build of the current master branch and while it did give me more subtitle customization option, it's not entirely what I'm looking for. All I know about the default font VLC uses is that it's Arial with a drop shadow but I'm not sure about the size.

Any response is appreciated, thanks!

**Comment by sevenrats** [comment]
Hi the supported way to do this is using an mpv.conf file according to the documentation. You will need to find the font file in your system, and use the appropriate mpv setting to set subtitle fonts to that file.

**Comment by coolpringles** [comment]
I may be doing something wrong but it doesn't seem to work for me.

![image](https://github.com/jellyfin/jellyfin-media-player/assets/52508616/a4731f61-5a13-4e06-a587-257da9f646e6)
(also tried ``--sub-font='C:\Windows\Fonts\arial.ttf'``)
