### ISSUE TITLE
strip from # to the Z

### ISSUE THREAD

**Issue by MRDJellyfin** [jellyfin/jellyfin-media-player#55]
I have a TV as a monitor of the PC with Windows 10, with a resolution of 1920 x 1080 at 150% both in Jellyfin App and in Jellyfin Desktop (Shim) in the movies menu, it shows me 6 per line and the strip from # to the Z (which appears to the right of the movie covers) while in Jellyfin Media Player it only shows me 5 movie covers and the strip on the right starts from the middle of the letter B to Z so it doesn't show # and the letter A. At 100% resolution, all show the same information.

**Comment by iwalton3** [comment]
Try passing a `--scale-factor` into the application through the command line with various amounts and see if that makes the scaling better.

**Comment by MRDJellyfin** [comment]
The truth in the end I loved this circumstance, because it lowered it to 149% directly in Windows (the truth is, I do not know how to do it by commands, a 67-year-old old man tells you that hardly understands certain technical things or that It looks for how to do it to a certain point) and it turned out that Jellyfin Media Player drops it to 100% which allows me to have everything else to 149% (so I don't have to change the result every time I exit Jellyfin Media Player) and so So much so I can have more covers per screen (movies) and the description of the movie add <H1> </H1> (I look for it on the internet it is not that I have the technical knowledge) at the beginning and at the end respectively, to increase the font size to be able to read it without problems since the original is too small and it costs a lot of work to read. I have a lot of work to do (more than 3,000 films) to make these changes but it is well worth it and I cannot compare it with what you have done and continue to climb. Thanks again.
