### ISSUE TITLE
[Flatpak] please enable cropdetect filter

### ISSUE THREAD

**Issue by Tracenji** [jellyfin/jellyfin-media-player#551]
**Is your feature request related to a problem? Please describe.**
the flatpak build does not include the cropdetect filter, this makes certain MPV scripts people might want to run not work

**Describe the solution you'd like**
build the flatpak with the cropdetect filter enabled

**Describe alternatives you've considered**
the alternative is to have black bars around videos that have black bars encoded in when using the flatpak

**Additional context**
i was trying to switch from the deb package to the flatpak and noticed that my dynamic autocrop MPV script was not working on the Flatpak build, i did some digging at it appears this is because the flatpak does not include the cropdetect filter while the deb package does

**Comment by sevenrats** [comment]
We will evaluate a PR to this effect on it's merits, but unfortunately the project does not currently have the resources to go down this rabbit hole.  Everybody and their friend has a package manager or build-time config they want supported -- this is why the project is open source.  Package it however you want. While we are very grateful for your suggestion and the insight it provides, we have to decline at this time. Thank you for understanding.
