### ISSUE TITLE
Playing video doesn't keep the device awake on Linux

### ISSUE THREAD

**Issue by mario-g98** [jellyfin/jellyfin-media-player#552]
While playing a video, jmp doesn't keep the device awake, which leads to screen off / sleep.

[jellyfinmediaplayer.log](https://github.com/jellyfin/jellyfin-media-player/files/14030480/jellyfinmediaplayer.log)

**Comment by sevenrats** [comment]
we need way more info than this because both the developer and myself use the app on linux and I haven't heard of this at all.

**Comment by mario-g98** [comment]
> we need way more info than this because both the developer and myself use the app on linux and I haven't heard of this at all.

Can you tell me what info will be helpful?

**Comment by sevenrats** [comment]
pretty much everything. distro, installation method, versions of everything.

**Comment by sevenrats** [comment]
Hey thanks for your report. As a heads up, I'm going to close this in the next week if we can't get enough info to reproduce.

**Comment by mario-g98** [comment]
Sorry, I was busy. 

So I decided to do a fresh install just to be sure I didn't do something wrong in my setup. 

I discovered that the bug happens in Gnome but not in KDE.  So the bug can be reproduced by installing EndeavourOS with Gnome. It happens both on Wayland and X11. I have installed [this](https://aur.archlinux.org/packages/jellyfin-media-player) version.

**Comment by mario-g98** [comment]
My apologies, today I noticed that the problem happens on MPV as well. I tested it on 2 different laptops with a fresh install of EndeavourOS. I guess I can try it on some other distro, but for now, the problem is definitely not JMP-related.

**Comment by mario-g98** [comment]
Apparently this is a [known problem](https://wiki.archlinux.org/title/Mpv#GNOME_Blank_screen_(Wayland)) in Gnome, which can be fixed by placing [this script](https://github.com/Guldoman/mpv_inhibit_gnome) inside `mpv/scripts/`
