### ISSUE TITLE
Jellyfin fullscreen aspect ratio (zoom etc)

### ISSUE THREAD

**Issue by Kev1n121** [jellyfin/jellyfin-media-player#553]
I want to zoom in on a video that have blackbars. I only have the option in the Jellyfin (auto cover and fill). On the jellyfinmediaplayer I can choose more options, but I still have the blackbars. Because these are inside the video converted somehow. I have many times a video with blackbars. But in Kodi i didnt have the problem I can zoom with it. that Ive used for a long time, I want something new. And I like Jellyfin now. But I can not get the videos in full screen (blackbars removed) on Jellyfin. Is there a way to get working?  Or is the only solution to just convert all of these videos, And do someone know how do this?

**Comment by sevenrats** [comment]
This is a feature request for "crop" aspect ratio which is not possible without black border detection.
this can be implemented using custom mpv scripts (provided you are not using the flatpak version which lacks the cropdetect filter),  but will not be supported directly in JMP or jellyfin-web.
It is possible to create this result for yourself using custom mpv scripts, which you can install to your preferences directory.

**Comment by Kev1n121** [comment]
Thank you for your comment, But how Is this also possible with a raspberrypi? and with jellyfin tizen?
