### ISSUE TITLE
闪退，附WINDOWS日志

### ISSUE THREAD

**Issue by feiver** [jellyfin/jellyfin-media-player#557]
错误应用程序名称: JellyfinMediaPlayer.exe，版本: 0.0.0.0，时间戳: 0x64456915
错误模块名称: unknown，版本: 0.0.0.0，时间戳: 0x00000000
异常代码: 0xc0000005
错误偏移量: 0x0000021083ae70b0
错误进程 ID: 0x0x14C8
错误应用程序启动时间: 0x0x1DA599512022A68
错误应用程序路径: D:\Apps\Jellyfin\Jellyfin Media Player\JellyfinMediaPlayer.exe
错误模块路径: unknown
报告 ID: e256612a-2a5d-40fc-b457-26201976e94c
错误程序包全名: 
错误程序包相对应用程序 ID:

**Comment by sevenrats** [comment]
this repo currently only has english support. We are not able to handle this report, sorry.
