### ISSUE TITLE
Add images from hard drive

### ISSUE THREAD

**Issue by MRDJellyfin** [jellyfin/jellyfin-media-player#56]
There is no + sign when wanting to edit images of the film (that is, there is no option to be able to select directly from the hard disk, example: from the directory of images downloaded from the internet). Windows 10
![Signo mas](https://user-images.githubusercontent.com/82923908/115825553-35235d80-a3cf-11eb-955e-0d7fa9aec570.jpg)

**Comment by iwalton3** [comment]
This will be partially fixed in the next release. You'll be able to add images but only by drag-drop into the add dialog.
