### ISSUE TITLE
Support mpv keyboard shortcut

### ISSUE THREAD

**Issue by tony1016** [jellyfin/jellyfin-media-player#567]
**Is your feature request related to a problem? Please describe.**
I can't use keyboard i to show media information like mpv do.

**Describe the solution you'd like**
Support mpv keyboard shortcut

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by sevenrats** [comment]
you will want to open this feature request against the web app inside JMP.  this repo is just C++ and QML shell that hosts the web app.  jellyfin-web tracks features at features.jellyfin.org

Thanks again!

**Comment by tony1016** [comment]
> you will want to open this feature request against the web app inside JMP. this repo is just C++ and QML shell that hosts the web app. jellyfin-web tracks features at features.jellyfin.org
> 
> Thanks again!

Sorry but I don't quite understand.Isn't is app using mpv to play the video?

**Comment by sevenrats** [comment]
yes jmp is a c++ app that hosts a video player powered by mpv-as-a-library behind a webview, and plays video by forcing the contents of the webview to be transparent. you are literally looking through the webapp to see the mpv frame.  tmk keys don't make it into mpv ever. keys are bound by the webapp according to its own principles and then manipulate mpv using its api. this is additionally complicated by our support of controllers.
having said all that tho there is no reason you can't port your favorite keybinds to the webapp, or, alternatively, launch a mpv-as-an-app using the playback URL.

**Comment by tony1016** [comment]
OK,Thx

Seven Rats ***@***.***> 于2024年3月4日周一 01:48写道：
