### ISSUE TITLE
Add option to have a background for subtitles

### ISSUE THREAD

**Issue by randomoOCoder** [jellyfin/jellyfin-media-player#584]
**Is your feature request related to a problem? Please describe.**
There is currently very limited options to customize subtitles appearance, one of the options I miss is one to add a transparent box around subtitles.

**Describe the solution you'd like**
Add an option to define the background color.

**Describe alternatives you've considered**
Alternative clients, but most of them don't have this option.

**Additional context**
This is what it would look like
![image](https://github.com/jellyfin/jellyfin-media-player/assets/79910412/f29d4303-8cbc-4797-bfc8-9e0586b20a7a)

**Comment by sevenrats** [comment]
You can add this styling using mpv.conf as per the docs.
