### ISSUE TITLE
Allow application icon to be themed on Linux

### ISSUE THREAD

**Issue by viggy96** [jellyfin/jellyfin-media-player#59]
**Is your feature request related to a problem? Please describe.**
Jellyfin Media Player uses its own icon for the taskbar/dock on Linux instead of specifying a generic icon that can be themed.

**Describe the solution you'd like**
Use generic icons

**Describe alternatives you've considered**
I have tried editing the *.desktop file associated with Jellyfin Media Player, but it only changes the icon in the application list, but not the taskbar/dock.

**Additional context**
Papirus provides icons for Jellyfin. I haven't checked, but I would imagine that other icon themes have icons for it as well.

**Comment by iwalton3** [comment]
The icon is already set to `com.github.iwalton3.jellyfin-media-player` which is not an absolute file path. It has to be named like that for Flatpak. Is there something I can do to make it able to be themed?

**Comment by viggy96** [comment]
Hmmm, you're right. Instead I'll submit a request to the icon theme to have them put in another link for Jellyfin Media Player.

**Comment by viggy96** [comment]
It appears this is in progress on this issue: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/2007

**Comment by viggy96** [comment]
Actually I just realised that the window icon is set here: 
```
#if defined(Q_OS_WIN) || defined(Q_OS_LINUX)
    // Setting window icon on OSX will break user ability to change it
    app.setWindowIcon(QIcon(":/images/icon.png"));
#endif
```

**Comment by viggy96** [comment]
Icon themes change the icon in the application list for the user, but once the application is opened, the taskbar/dock button shows this icon no matter which icon theme the user has selected.
