### ISSUE TITLE
can you ignore mouse clicks under the progress bar

### ISSUE THREAD

**Issue by siparker** [jellyfin/jellyfin-media-player#595]
**Is your feature request related to a problem? Please describe.**
when i click under the progress bar. i want it to just focus the window. not pause the video.
**Describe the solution you'd like**
i want it to work like every other player/platform that i ever use. which is that under the playback bar clicking does not pause it. 

**Describe alternatives you've considered**
stickign with how it is. which is only mildy irritating but i thought i would mention it as its been on my mind for a while

**Additional context**
nope thats all.

**Comment by sevenrats** [comment]
@siparker hey mate thanks for your request!  This repo is for the C++/Qt/Qml shell that hosts the webapp.  Your feature request has to be done in jellyfin-web, which tracks feature requests at features.jellyfin.org
