### ISSUE TITLE
[Qt6] Top+bottom OSD backgrounds visible when next episode starts playing

### ISSUE THREAD

**Issue by nvllsvm** [jellyfin/jellyfin-media-player#602]
**Describe the bug**
Both the the top+bottom OSD backgrounds become visible when the next episode of a show starts playing. The video is then shrunk to fit between them.

![top_bottom_visible](https://github.com/jellyfin/jellyfin-media-player/assets/6550543/e64b929d-8a8c-45d9-8ad6-e827df114182)

**To Reproduce**
1. Watch TV show
2. Wait until next episode starts

**Expected behavior**
The next episode starts without these becoming visible.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: https://github.com/jellyfin/jellyfin-media-player/commit/9bdd19b28cc1184ae0475596fde6ae02ee3534b8

**Comment by sevenrats** [comment]
this is not a bug this is the workaround for https://bugreports.qt.io/browse/QTBUG-111739 as noted in #537 
Please consider consolidating this issue there.

**Comment by nvllsvm** [comment]
Ahh, thanks for the context. I was wondering why the OSD was changed in the qt6 branch.

However, this is still a bug in the workaround and seems like it should be fixable without too much effort.

![out](https://github.com/jellyfin/jellyfin-media-player/assets/6550543/081e237f-dcb5-4259-81ec-093072982c06)

**Comment by sevenrats** [comment]
nice.  there is no way around *all* the bugs associated with this workaround tho except for building the QML osd, tmk.  even after you solve this problem, what about the channel menus? what about playback info? all these get covered by the video no matter what.

**Comment by nvllsvm** [comment]
I hadn't considered those other issues. I updated the description of #537 with a list of some of them. 

I now agree that #537 should be the blocker of the Qt6 migration.

**Comment by sevenrats** [comment]
thanks for the added detail. when I made that issue we had spelled most of the details out in #99 and we never got around to porting that context over mostly.

honestly if somebody write the osc then I could be convinced to release through the compat api. Im sure more important software than us is already doing it.
