### ISSUE TITLE
New official release

### ISSUE THREAD

**Issue by BuonHobo** [jellyfin/jellyfin-media-player#606]
Today marks a year since the last jellyfin-media-player release.
Making a new one would let most users benefit from a year's worth of extra development, without having to build the whole thing themselves.

**Comment by thornbill** [comment]
Release happen [when they are ready](https://jellyfin.org/docs/general/faq#when-will-release-x-happen-when-will-feature-x-be-available) and not because some arbitrary amount of time has passed.
