### ISSUE TITLE
Flatpak doesn't open on Linux Mint 21.3

### ISSUE THREAD

**Issue by DRWAUN** [jellyfin/jellyfin-media-player#607]
**Describe the bug**
I installed the Jellyfin Media Player flatpak through the software manager on Linux Mint and am unable to open it. It doesn't launch at all. When installed with the deb, it launches fine.

**To Reproduce**
1. Install Media Player flatpak
2. Click on launch from the software center or run it from the terminal
3. No launch happens
4. No error when trying to launch from software center, but when trying to launch from terminal I get this error:
`$ flatpak run com.github.iwalton3.jellyfin-media-player` 

`error: runtime/org.kde.Platform/x86_64/5.15-22.08 not installed
`

**Expected behavior**
Media Player flatpak launches

**Desktop (please complete the following information):**
 - OS: Linux Mint Cinnamon
 - Version 21.3
 - Installation Method: Flatpak from Mint's software manager

**Additional context**
I tried looking for the logs, but I couldn't even find the Jellyfin Media Player folder:
`~/.var/app$ ls` 

`com.spotify.Client  com.usebottles.bottles  io.bassi.Amberol
`
System info:
![image](https://github.com/jellyfin/jellyfin-media-player/assets/101024515/68c88b5e-ef2a-4c5e-9c3f-862f8bd1af60)

**Comment by hush2** [comment]
try `flatpak update`

**Comment by DRWAUN** [comment]
That seems to have worked. How come the software manager didn't provide the latest version?

**Comment by tadghh** [comment]
Make sure to close this issue

**Comment by DRWAUN** [comment]
Ah, my bad. Will close
