### ISSUE TITLE
Won't run on Ubuntu 24.04 (Noble)

### ISSUE THREAD

**Issue by prascher** [jellyfin/jellyfin-media-player#611]
**Describe the bug**
The Bug is that it won't run on Ubuntu 24.04, it appears to be because libmpv.so.1 doesn't seem to be in Ubuntu 24.04 or at least it can't find it.

**To Reproduce**
1. Either click Jellyfin icon, or use the command line which helps debug the issue
2. See error `jellyfinmediaplayer: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory`

**Expected behavior**
Application Launches and is able to be used.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 24.04
 - Installation Method deb from releases page

**Additional context**
I did not see the error being logged which is why no log attached.

**Comment by satmandu** [comment]
FYI building master from source (with minor changes to handle the different packages of noble, such as no `python` package) appears to create binaries for `noble` that work just fine.
