### ISSUE TITLE
Add a .deb in github releases for Ubuntu 24.04 (Noble)

### ISSUE THREAD

**Issue by accforgithubtest** [jellyfin/jellyfin-media-player#615]
**Is your feature request related to a problem? Please describe.**
Ubuntu 24.04 (Noble) is the new LTS version, and it will be good to have a deb package available to install on the latest LTS version. 

**Describe the solution you'd like**
Add a deb in github releases for Ubuntu 24.04 (Noble), similar to the deb packages available for other versions.

**Describe alternatives you've considered**
I really prefer installing from the github releases, as it means having the ability to get the latest updates directly from the jellyfn team. The project teams making available a installable build is the best approach.

**Additional context**
Somewhat related to #611. Users will appreciate a pre-made package available for the latest LTS versions.

Thanks & Cheers !

**Comment by iwalton3** [comment]
Fixed in latest release
