### ISSUE TITLE
[flatpak] runtime org.kde.Platform branch 5.15-22.08 is end-of-life

### ISSUE THREAD

**Issue by MartenBE** [jellyfin/jellyfin-media-player#620]
**Describe the bug**

```text
Info: runtime org.kde.Platform branch 5.15-22.08 is end-of-life, with reason:
   We strongly recommend moving to the latest Qt 5.15-based stable version of the Platform and SDK
Info: applications using this runtime:
   com.github.iwalton3.jellyfin-media-player
```

**To Reproduce**

1. Install or upgrade the flatpak through CLI using `flatpak update`.
2. Warning is displayed in the output.

**Expected behavior**
The warning is resolved and fixed.

**Screenshots**

![image](https://github.com/jellyfin/jellyfin-media-player/assets/1958780/a266daf1-3d92-4171-8704-f133b756ac4f)

**Desktop:**
 - OS: Fedora
 - Version: 40 (KDE spin)
 - Installation Method: Flatpak from flathub

**Additional context**
/

**Comment by iwalton3** [comment]
Fixed in latest release.
