### ISSUE TITLE
[macOS] 1.10 release doesn't work

### ISSUE THREAD

**Issue by kambala-decapitator** [jellyfin/jellyfin-media-player#623]
**Describe the bug**
Client doesn't load, crash dialog appears:
```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /usr/local/Cellar/qt@5/5.15.13_1/lib/QtGui.framework/Versions/5/QtGui
Referenced from: <FC0F6FB1-9B65-363C-9F53-9DE00118EA61> /Applications/Jellyfin Media Player.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
Reason: tried: '/usr/local/Cellar/qt@5/5.15.13_1/lib/QtGui.framework/Versions/5/QtGui' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/qt@5/5.15.13_1/lib/QtGui.framework/Versions/5/QtGui' (no such file), '/usr/local/Cellar/qt@5/5.15.13_1/lib/QtGui.framework/Versions/5/QtGui' (no such file), '/Library/Frameworks/QtGui.framework/Versions/5/QtGui' (no such file), '/System/Library/Frameworks/QtGui.framework/Versions/5/QtGui' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)
```

**To Reproduce**

Simply launch the player

**Expected behavior**
Players opens withour errors

**Desktop (please complete the following information):**
 - OS: macOS 14.4.1
 - Version 1.10 Intel

**Additional context**
QtGui.framework is present in `/Applications/Jellyfin Media Player.app/Contents/Frameworks` but still QtWebEngineCore tries to load it from homebrew path

**Comment by poulpor** [comment]
Same here, Jellyfin Server 10.9.1 latest is used.

**Comment by thoja21** [comment]
Same here with latest client and server 10.9.1 on MacOS 12.7.5.
I get the following but the log file link doesn't do anything so I don't know where to look for it.

<img width="1440" alt="Screenshot 2024-05-15 at 10 02 27 am" src="https://github.com/jellyfin/jellyfin-media-player/assets/18580089/cadf2727-e528-4f2e-901d-66184fc13644">

**Comment by iwalton3** [comment]
Sounds like a bad release. I checked the build logs and it did bundle a web client so I am unsure exactly what is happening, but it looks like QT Web engine is broken and not it didn't bundle the web client?

Help is very appreciated since I don't have the ability to thoroughly test or troubleshoot the Mac version.

**Comment by szethh** [comment]
> Same here with latest client (1.10.0) and server 10.9.1 on MacOS 12.7.5. I get the following but the log file link doesn't do anything. The log in `~/Library/Logs/Jellyfin Media Player` doesn't seem to suggest anything is going wrong, although I might be missing something:
> 
> [Jellyfin Media Player.log](https://github.com/jellyfin/jellyfin-media-player/files/15319531/Jellyfin.Media.Player.log)
> 
> <img alt="Screenshot 2024-05-15 at 10 02 27 am" width="1440" src="https://private-user-images.githubusercontent.com/18580089/330739992-cadf2727-e528-4f2e-901d-66184fc13644.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjY4MTUsIm5iZiI6MTcxNTc2NjUxNSwicGF0aCI6Ii8xODU4MDA4OS8zMzA3Mzk5OTItY2FkZjI3MjctZTUyOC00ZjJlLTkwMWQtNjYxODRmYzEzNjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA5NDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxNWUxZGQ4MzJlYjc5OTA2NWM5NDY0ZDlkOWYxZDhiNmQyMzU2MjhiZjdkY2Q2YjIyMmMxYjQxYWYwYzA4M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xY_ms_OkiiqEwt6YgAh8Y34maD0K35_J2b2tgoTsrjc">

I have the same issue, also latest jellyfin on macos

**Comment by kambala-decapitator** [comment]
@iwaltonI the issue is that rpath on QtWebEngineCore wasn't adjusted to point inside the app bundle (or maybe it simply uses absolute path, can't check atm)

**Comment by kambala-decapitator** [comment]
sorry, I was wrong a bit. The issue is not with QtWebEngineCore itself but rather with its embedded app QtWebEngineProcess (QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess). Running `otool -L` on it does show absolute paths to Homebrew for a number of Qt frameworks.

another strange things I noticed:
- all Qt dylibs (the binaries I mean) are also copied to the Frameworks dir, which doesn't make sense as you already have those binaries inside respective frameworks
- version of QtWebEngineCore is reported as 5.15.16 which indicates that it was built from commercial Qt version while e.g. QtGui reports 5.15.13 (the latest open-source Qt 5 version)

**Comment by jakobzudrell** [comment]
Any eta when the new builds with this fix are released?
I've seen that at least within the pre-release branch pipeline they were built..
