### ISSUE TITLE
Homepage Display A Large Blank area with ‘Carousel Disabled’ Custom CSS

### ISSUE THREAD

**Issue by ChowDPa02k** [jellyfin/jellyfin-media-player#625]
**Screenshots**
![image](https://github.com/jellyfin/jellyfin-media-player/assets/16922893/5a899d28-8f1e-4dd6-9239-4f9c51e7ecf6)

It looks like JMP ignore system scale and keeps 100% default.

Behaviour in Web Browser (Chrome below):

![image](https://github.com/jellyfin/jellyfin-media-player/assets/16922893/1181c204-52dc-4d6e-9649-1f95ae3fd1cc)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10.9.1
 - Installation Method windows installer
 - Server: 10.9.1 LinuxServer Docker Image

**Additional context**
Screen Resolution: 1920x1080
System Scale: 125%
Custom CSS: [Disable Image Carousel for Librarie](https://jellyfin.org/docs/general/clients/css-customization/#disable-image-carousel-for-libraries)

**Comment by gummykage** [comment]
Not working for me either... Annoying
![image](https://github.com/jellyfin/jellyfin-media-player/assets/9695713/ed01f625-5445-4c1d-9ddf-7e37b4d54b85)

**Comment by ChowDPa02k** [comment]
> Not working for me either... Annoying ![image](https://private-user-images.githubusercontent.com/9695713/334864436-ed01f625-5445-4c1d-9ddf-7e37b4d54b85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3Nzg0MzQsIm5iZiI6MTcxNzc3ODEzNCwicGF0aCI6Ii85Njk1NzEzLzMzNDg2NDQzNi1lZDAxZjYyNS01NDQ1LTRjMWQtOWRkZi03ZTM3YjRkNTRiODUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMTYzNTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWJkODg5ZTgxOTdmZjhjMGIxNmM2MzViYmFmODBmNTMyNTU5M2NlMDAxOGVmOTc3NjM4NGU5MTRkZDgyZGY3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AMluDoTHwtP66mjVXP2Mag1544b0FJGvKGTEJsQNtaA)

It might be some calculation related problem of jellyfin-web, I found an workaround by adding css cods as follows:

```css
@media (min-width: 100em) {
    .overflowBackdropCard, .overflowSmallBackdropCard {
        width: 18.5vw;
    }
}
```

It seems that at large desktop, the width of library card was slightly larger than it's parent DOM, making it wrap earlier.

**Comment by gummykage** [comment]
Thank you! It is working!
