### ISSUE TITLE
Blank page on homepage

### ISSUE THREAD

**Issue by Tian-MC** [jellyfin/jellyfin-media-player#626]
When I try to have access on my jellyfin, it doesn't appear anything on the homepage.

![JellyfinMediaPlayer_RFMCeeIPfD](https://github.com/jellyfin/jellyfin-media-player/assets/66381488/d9d72260-5ca3-410d-87c2-c1c98e6dd942)

I have to do something?

**Comment by bastouf** [comment]
> You need to use the latest Jellyfin server with the newest JMP release. It isn't backwards compatible.

After upgrade my desktop client, I had the same problem.
Update my Jellyfin server to the last version worked for me ! Thanks @iwalton3

**Comment by bermudev** [comment]
I can also confirm that after having the same problem it has been fixed by upgrading the server to the latest version as suggested by @iwalton3.

I invite others who have the same problem to try this solution!

**Comment by tone-milazzo** [comment]
I've updated the desktop client (Windows 10) and Jellyfin in the docker container. Some of the views work some don't, like under Music: Suggestions, Genres, and Songs display results. Albums, Album Artists and Artist do not.

**Comment by curtwagner1984** [comment]
> You need to use the latest Jellyfin server with the newest JMP release. It isn't backwards compatible.

Gee, maybe this is something the installer should warn you about...

**Comment by akyag** [comment]
Arch hasn't updated to 10.9 yet, I am waiting for that now... because now I have a broken installation of JMP.

**Comment by stpnwf** [comment]
> Gee, maybe this is something the installer should warn you about...

Exactly. I opened Jellyfin and it warned me there was an update available, that is why I updated it. The same warning could have mentioned that it wasn't backwards compatible...

**Comment by iwalton3** [comment]
JMP v1.10.0 requires a Jellyfin server version of v10.9.1 or later to work. Older server versions will result in an empty home screen.

I added a very large warning to the download page to hopefully prevent people from having this issue.

**Comment by Cifer9516** [comment]
![Screenshot_20240601_181626](https://github.com/jellyfin/jellyfin-media-player/assets/93731714/652ef654-3a75-419d-9e8b-8cd3932df0ea)
Still blank on every media player except web.
