### ISSUE TITLE
No home screen after update

### ISSUE THREAD

**Issue by Mrpuppyz** [jellyfin/jellyfin-media-player#630]
After updating my jelly in media player to v1.10.0 the home screen is blank. At the top of the screen I can still click the favorites button and play something directly from there however but when I switch back over to go home page it remains blank. 
Having this issue on both arch linux and Windows 11. If I open jelly fan in a web browser the homepage appears correctly.

**Comment by PerssonP** [comment]
Have you made sure to update your jellyfin server to version 10.9.1? As noted in the release notes it's a requirement for the latest version of jellyfin-media-player.
I ask because I updated media-player before I updated my server and had a blank home screen until I fixed that.

**Comment by Mrpuppyz** [comment]
I think you may be correct. I didn't realize that my arch linux pacman is still running the older version. Thanks.

**Comment by Lancaban** [comment]
I came here with the same problem, also running Arch Linux, Unfortunately, several days later, the media player is on 1.10, the version in Arch repository is still 10.8.13, there is a jellyfin-server-bin in the AUR, but it's still only 10.9.1-1 plus it fails to download, so I'm a little stuck. 

Not sure if I have the technical acumen for compiling from source myself, I have no clue how to sue docker (plus I'm afraid of loosing my current settings, played status etc.) Does anyone know how long it might be until the Arch Repo gets updated? Or have any other solution or advice?

**Comment by Mrpuppyz** [comment]
I do not know when the archlinux repo is going to have the latest jellyfin-server update. For now I just used timeshift to go back to a previous snapshot before I updated the jellyfin-media-player. I could have just used the a web browser that was still working for me aswell.
