### ISSUE TITLE
Syncplay Session "undefined"

### ISSUE THREAD

**Issue by EmreDogann** [jellyfin/jellyfin-media-player#64]
Hey,

I am trying out the jellyfin-media-player for the first time and was testing it out on both Windows 10 and macOS Catalina. When I start a syncplay session in the client, it shows itself as "undefined" and no one else can join the session. However, when I go to the jellyfin server through a web browser, I can join the syncplay session just fine.

On the reverse, if I start a syncplay session through the web browser, users on the client can see it but it displays as unfined and cannot join it. However, if those same users login through the browser they can join it. Based on this, it seems to be an issue on the client side, do you know what the problem might be? Am I doing anything wrong?

![image](https://user-images.githubusercontent.com/48212096/115969060-f60e1d00-a532-11eb-90f1-3e1ec1f0a049.png)

Thanks

**Comment by iwalton3** [comment]
What Jellyfin server version are you using? Jellyfin Media Player only supports SyncPlay for Jellyfin 10.7.0 and newer.

**Comment by EmreDogann** [comment]
Hey, I am running on 10.6.4, will try it with 10.7.2 now and let you know how it goes.
