### ISSUE TITLE
Icons and movies don't show up on mac

### ISSUE THREAD

**Issue by legoraft** [jellyfin/jellyfin-media-player#658]
**Describe the bug**
When opening the most recent version of jellyfin media player, nothing shows up in the app on mac

**To Reproduce**
1. Download the latest macos intel build
2. move the app to your applications
3. Open the app
4. See nothing

**Expected behavior**
I'd expect that the jellyfin client works as it does in the browser, where it does work.

**Screenshots**
<img width="1641" alt="Screenshot 2024-05-19 at 17 47 10" src="https://github.com/jellyfin/jellyfin-media-player/assets/50689727/5f1ee58a-64b4-4223-b4aa-c08d0c177184">

**Desktop (please complete the following information):**
 - OS: MacOS 13.5.2
 - Version 1.10.1
 - Installation Method MacOS intel build 1.10.1

**Additional context**
I've tried the maximizing and unmaximizing as mentioned in #221. I'm on an M2 Macbook air.

**Comment by legoraft** [comment]
The server used is running the jellyfin 1.9.1 release.

**Comment by Suzaru** [comment]
I have the same issue and tried installing, uninstalling and everything. Nothing works :( Please help!

**Comment by Suzaru** [comment]
> The server used is running the jellyfin 1.9.1 release.

I had the same issues and fixed it. There most likely are some leftover user config files that won't be deleted with a standard deinstall. There is an App called "AppleCleaner" for free online. Download that, let it deinstall jellyfin fully and re-install Jellyfin. Should work and hope it helps

**Comment by legoraft** [comment]
Yes, I followed a tutorial to remove cache and other files from the app and it works now. Thanks
