### ISSUE TITLE
Chapter markers flickering during play.

### ISSUE THREAD

**Issue by ChaoticWyrme** [jellyfin/jellyfin-media-player#660]
**Describe the bug**
When a video is playing and the controls are showing the chapter markings flicker periodically. It doesn't happen when the video is paused, and it doesn't happen on the web client.

**To Reproduce**
1. Play any content with chapter markings.
2. Look at playbar
3. See flickering

**Expected behavior**
No flickering of chapter markers

**Screenshots**
[A short screen recording showing the issue happening](https://youtu.be/_-VAtMYyB6I)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v1.10.1
 - Windows Installer

**Additional context**

**Comment by thornbill** [comment]
Should be fixed in the next release by https://github.com/jellyfin/jellyfin-web/pull/5593

**Comment by ChaoticWyrme** [comment]
Alright, thanks :)
