### ISSUE TITLE
Dashboard shows incorrect versioning

### ISSUE THREAD

**Issue by cohortcw179** [jellyfin/jellyfin-media-player#678]
- Jellyfin log. 
     - Windows: `%LOCALAPPDATA%\JellyfinMediaPlayer\logs`
[JellyfinMediaPlayer.log](https://github.com/user-attachments/files/15532229/JellyfinMediaPlayer.log)

**Describe the bug**
After updating to Jellyfin 10.9.4. The versioning shown in Dashboard is different. 

**To Reproduce**
1. Just run Jellyfin Media Player liked normal Windows App.
2. Click on Dashboard
3. See error under "Server"

**Expected behavior**
All versions should be similar. e.g. Server version, Web version, Build version should show same version numbering.

**Screenshots**
![jellyfinmedia](https://github.com/jellyfin/jellyfin-media-player/assets/143590473/7470dc1f-fe5c-4e0e-be71-b440b6c74c2c)

**Desktop (please complete the following information):**
 - OS: Windows 23H2

**Comment by thornbill** [comment]
This is showing the version of web that JMP was built with which was 10.9.2.

**Comment by Pigney** [comment]
This continues to be an issue in v1.11.0 which was supposed to separate the web client entirely, causing media to not display when played.
![JellyfinMediaPlayer_xoTb4qZTTG](https://github.com/jellyfin/jellyfin-media-player/assets/34039700/91d13c3d-b860-4aba-8d6c-dc97fba53ce1)
