### ISSUE TITLE
Unable to connect to Jellyfin server when Base URL is defined after updating to JMP 1.11.0

### ISSUE THREAD

**Issue by mercindustries** [jellyfin/jellyfin-media-player#683]
**Describe the bug**
Unable to connect to Jellyfin server when Base URL is defined after updating to JMP 1.11.0

**To Reproduce**
1. After updating JMP will ask to connect to Server
2. Enter the host that has a Base URL defined http://subdomain.domain.com/jellyfin
3. JMP will throw out error:

Connection Failure
We're unable to connect to the selected server right now. Please ensure it is running and try again.

**Expected behavior**
JMP should be able to connect to servers with Base URL defined.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Version [14.5]
 - Installation Method [DMG]

**Additional context**
Nothing useful can be seen from Jellyfin logs. Jellyfin server is confirmed to be working via browser and after downgrading back to JMP 1.10.1

**Comment by EisFrei** [comment]
I can confirm this exact behaviour.

In addition I have basic auth active on the root directory, but not the jellyfin subdirectory. Yet I get prompted to enter the basic auth credentials. This wasn't the case with earlier JMP versions.

Downgraded to 1.10.1

**Comment by michaelcresswell** [comment]
I saw this behavior at first when I tried to connect to my main Jellyfin instance (10.9.4) with a base URL defined.

I have a test instance (unstable) without a base URL and JMP 1.11.0 connects to it.

Interestingly, after connecting to an instance without a base URL I can now connect to my Jellyfin instance with a base URL.

macOS / 14.3 / Apple Silicon DMG

**Comment by iwalton3** [comment]
Try this dev build: https://github.com/jellyfin/jellyfin-media-player/actions/runs/9417664965

**Comment by mercindustries** [comment]
It appears that the dev build has resolved the issue for me on Apple Silicon M1

**Comment by vincejv** [comment]
Thanks for the quick turn around, working for me as well..

**Comment by Maltahl** [comment]
The Dev client fixed it for me as well on Windows 11.

**Comment by erictbar** [comment]
Dev build fixed it for me on Windows 11

**Comment by iwalton3** [comment]
Fixed in latest release
