### ISSUE TITLE
Can't Connect to Server on 1.11.1 macOS

### ISSUE THREAD

**Issue by timcole** [jellyfin/jellyfin-media-player#690]
**Describe the bug**
Updating from 1.11.0 to 1.11.1 reprompted the connect to server screen I put the url `https://jellyfin.local.tim.rip` in my case I can't press enter, I can't click connect nothing happens.

**To Reproduce**
1. Download 1.11.1 on macOS
2. Good luck

**Expected behavior**
To get sent to the login screen

**Screenshots**
![](https://t.pics/KgrMayTXec.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: Sonoma 14.4.1 (SIlicon)

**Additional context**
This worked completely fine for me in yesterday's 1.11.0, I closed Jellyfin because it prompted there was an update, updated now can't do anything.

Downgrading to 1.11.0 works fine

**Comment by Jonas-Degn** [comment]
Exact same behavior for me on Windows 1.11.1 cleanly installed.
It appears completely irrelevant what is placed in the `Host` text field, I have tried IPs, DNS names, HTTP, HTTPS, the `Connect` button does not leave the disabled state and so leaves you stuck.

Unlike OP, it appears to me that on Windows the bug was introduced in 1.11.0, and requires downgrade to 1.10.1.

**Comment by ihabeid33** [comment]
I have the same the same issue too running on Linux and installed with flatpak (1.11.1). 

Also for some reason, the "Connect" button turns blue whenever I connect to my VPN, but I can't actually connect with the VPN tunnel on because my jellyfin server is not hosted on the internet.

**Comment by DrTinyFace** [comment]
Same here, both Jellyfin 1.11.1 and 1.11.0 as fresh installs had this issue on Windows 11, rolling back to 1.10.1 fixes issue

**Comment by CMHarris14** [comment]
I'm having a similar, but slightly different problem with 1.11.1 on windows. If I input an invalid address I get the response that would be expected. If I input my actual server the window just goes completely blank and requires I clear the cache to get back to the login screen. It is connecting to my server according to the server log, but nothing is ever being rendered in the player window after connecting. 1.10.1 still works fine for me.

**Comment by akash-258** [comment]
The version 1.11.1 shows a completely blank white screen from the start. Version 1.11.0 doesnt lets me login. 1.10.1 works completely fine.

**Comment by ThinkChaos** [comment]
Workaround on Linux: `r m -r ${XDG_CACHE_HOME:-~/.cache}/'Jellyfin Media Player'` (delete the space in between r and m once you've checked the path is correct)
