### ISSUE TITLE
Intro Skip not working in Windows since v1.11.1

### ISSUE THREAD

**Issue by Don-Chris** [jellyfin/jellyfin-media-player#701]
### Describe the bug
Since the update of JMP from **v1.10.1** to **v.11.1**, the Skip Intro Button is only shown in the first video stream after starting JMP. After stopping the stream and restarting the same video, the Skip Intro Button is not shown. 
Additionally, the skip Intro Button is always shown correctly in the browser.
Since not a lot changed between these versions, the bug is probably located in commit 1976274.

### To Reproduce
1. Use version v1.11.1 on windows
2. Start JMP and click instantly on a video. Wait or skip to a part of the video that got flagged as an intro/outro.
3. You can see the "Skip Intro" or "Next" Button.
4. Stop the Video (Click on the arrow in the top left)
5. Click on the same video or another one with a part of the video that got flagged as an intro/outro.
6. The "Skip Intro" or "Next" Button will not be displayed.

### Expected behavior
The Skip Intro Button should be shown everytime a new video stream is started.

### Desktop
 - OS: Windows 11 and Windows 10 (tested both)
 - Version: v1.11.1; I can't test v1.11.0 since I use a subfolder-type-path
 - Installation Method: windows installer

### Additional context
Log of the program with v1.10.1 : https://pastebin.com/A1eyec5R
Log of the program with v1.11.1: https://pastebin.com/TdfF7K59
Log while debugging with edge/chrome in v1.11.1: https://pastebin.com/eD6du7e8

### Error in web-debug:
```
3skipIntroPlugin.js:174  
  Uncaught (in promise) TypeError: Cannot read property 'SkipButtonIntroText' of undefined
    at mpvVideoPlayer.onTimeUpdate (skipIntroPlugin.js:174:110)
  onTimeUpdate @ skipIntroPlugin.js:174
  await in onTimeUpdate (asynchron)
  onTimeUpdate @ skipIntroPlugin.js:155
  (anonym) @ main.jellyfin.bundle.js?cdb0dd9873705de79052:2
  trigger @ main.jellyfin.bundle.js?cdb0dd9873705de79052:2
  onTimeUpdate @ mpvVideoPlayer.js:130
  (anonym) @ qwebchannel.js:303
  invokeSignalCallbacks @ qwebchannel.js:302
  QObject.signalEmitted @ qwebchannel.js:325
  QWebChannel.handleSignal @ qwebchannel.js:125
  QWebChannel.transport.onmessage @ qwebchannel.js:83
```
The first time a video stream is started the code in `skipIntroPlugin.js` in line 174 results in an undefined "skipIntroConfig" object. However, this time, the skip intro button can be seen. The next time, when a video stream is started, this object is valid, however the skip intro button can't be seen. It looks like the function `injectSkipIntroHtml()` returns an undefined `skipIntroConfig` object the first time it is called, and is defined after the second time.

line 173-174:
```
case "Introduction":
       skipIntro.querySelector("#btnSkipSegmentText").textContent = skipIntroConfig.SkipButtonIntroText;
```

line 126 somehow returns an undefined object the first time the function `injectSkipIntroHtml()` is called:
```
skipIntroConfig = await secureFetch("/Intros/UserInterfaceConfiguration");
```

### Temporary Fix
Manually overriding the lines 174 and 177 fixes the issue:

```
case "Introduction":
       skipIntro.querySelector("#btnSkipSegmentText").textContent = "Skip Intro";
       break;
case "Credits":
       skipIntro.querySelector("#btnSkipSegmentText").textContent = "Next";
       break;
```

**Comment by FizzyRust** [comment]
The temporary fix didn't have any effect for me, the bug is still there.

**Comment by Uncle-Tio** [comment]
Temporary fix didn't have any effect for me either.

The bug is probably located in commit 0c57c6d2eac9a806e7aa6be95d99a260f23adb98 not 1976274513795f0c6ac6bee50ebb9d8982af57bc. I already used an external web-client before 1.10, so I don't think that's the problem. Unless the problem didn't occur in version 1.10? I haven't tested it.

Also the skip intro (in 1.9.1) already worked with the [jumoog](https://github.com/jumoog/intro-skipper/) version. Of course, using the fix from commit bc0ec5a099a7d78c467211ce438e0165a1de71c1 which was never officially "released".

**Comment by FizzyRust** [comment]
I tested it out, and unfortunately the issue still persists.

**Comment by Uncle-Tio** [comment]
It's still working for me and a friend, can you check if the file `C:\Program Files\Jellyfin\Jellyfin Media Player\web-client\extension\skipIntroPlugin.js` has actually changed? should be 244-245 lines, if you want to compare or replace manually: https://github.com/Uncle-Tio/jmp-fork/blob/fix-skipintro/native/skipIntroPlugin.js

I'm running Jellyfin 10.9.7 + Intro Skipper 0.2.0.9

**Comment by FizzyRust** [comment]
I'm running Jellyfin 10.9.7 + Intro Skipper 0.2.0.11, although in the client of your build its displaying the web and build version as 10.9.6
I redownloaded your build and compared the skipIntroPlugin.js, they are exactly the same.

This is how it behaves for me:
Start playbay -> Skip intro works -> Stop playback -> Start playback again -> Skip intro doesnt work -> Start playback -> intro skip occasionally works...
This is about the same as it was on the official release. (Very inconsistant)

Also, for some reason on your build almost none of the ui works, I can start playback, but trying to open a library fully bricks it, so that I cant start playback either. Im assuming its because of the web version, on the official release its properly displaying server, web and build version as 10.9.7.

The only things I can think of, that we have different are: 
I have a newer version of intro skipper  (0.2.0.11)
I installed jmp on a separate drive instead of the default install location so the skipIntroPlugin.js is located at 
`G:\Software\Jellyfin Media Player\web-client\extension`

**Comment by Uncle-Tio** [comment]
I updated my intro skipper to 0.2.0.11, it's still ok. You could try using [skipIntroPlugin.js](https://github.com/Uncle-Tio/jmp-fork/blob/fix-skipintro/native/skipIntroPlugin.js) in the official build (replace), that's the only thing I changed apart from the mpv rollback. Regarding the wrong web version, you could test by deleting the cache (delete the folder `C:\Users\%USERNAME%\AppData\Local\Jellyfin Media Player`, only the one with a space, there are two). I'd recommend deleting it even if you're going to try the official version, just to be sure.

I think these are the last things we can try...

**Comment by Don-Chris** [comment]
@Uncle-Tio I tried it myself and your version of the skipIntroPlugin.js didn't fix the issue I posted here. I still can only click on the "skip Intro" button on the first video that I watch, after trying the same video (or another one) the skip Intro button isn't shown.

**Comment by Uncle-Tio** [comment]
I had already made a pull request thinking that the fix had solved it, so I'll mention this issue there, but for now I have no more suggestions, I'll have to leave it to someone more qualified.

I'll describe the debugging steps I took, so you can see if we had the same problem or perhaps guide you in discovering the causes:

(Oficial release 1.11.1)
1. [Open in debug](https://github.com/jellyfin/jellyfin-media-player#web-debugger)
2. Start a video, click on the part with the intro, the button appears (leave it paused).
3. In the Elements tab: CTRL+F and search for `skipIntro` until you find: `<div class="skipIntro" style="style="opacity: 1;>`
4. Now you exit the video. The values remain the same, open a video, go to the intro again, and now:
`<div class="skipIntro hide" style="style="opacity: 1;>`
5. The button doesn't appear. 
6. Double click on "skipIntro hide" and leave only "skipIntro", the button appears and works.

There are a few more things that happen with "display" in the style but that should be enough.

**Comment by Uncle-Tio** [comment]
You guys should try sannidhyaroy's solution, here is his [skipIntroPlugin.js](https://github.com/jellyfin/jellyfin-media-player/blob/1696a38a420297577b167bbe7f1f4f642319c5b6/native/skipIntroPlugin.js). It worked correctly for me too. If it's working for you, I'll close my pull request.

**Comment by Don-Chris** [comment]
> You guys should try sannidhyaroy's solution, here is his [skipIntroPlugin.js](https://github.com/jellyfin/jellyfin-media-player/blob/1696a38a420297577b167bbe7f1f4f642319c5b6/native/skipIntroPlugin.js). It worked correctly for me too. If it's working for you, I'll close my pull request.

Looks like this version of the Plugin fixed it for me. Thanks for letting me know :)
