### ISSUE TITLE
Can't play anything (music or videos) only on jellyfinmediaplayer from AUR

### ISSUE THREAD

**Issue by AliceT50** [jellyfin/jellyfin-media-player#713]
Four considerations:
 - Please do not open bug reports to ask questions. Use the Discussions feature instead.
 - Please make sure the issue only pertains to Jellyfin Media Player. If it also occurs in the web client, send the issue to jellyfin-web instead.
 - Please make sure that your issue is not being caused by errors in custom CSS or note that you are using custom CSS.
     - Notably, there have been instances of custom CSS breaking TV mode.
     - You can disable custom CSS under Display in the user settings.
 - Please provide logs. You can drag the log file into the issue to attach it.
 - 
[Log-jellyfin.log](https://github.com/user-attachments/files/15944894/Log-jellyfin.log)

     - Windows: `%LOCALAPPDATA%\JellyfinMediaPlayer\logs`
     - Linux: `~/.local/share/jellyfinmediaplayer/logs/`
     - Linux (Flatpak): `~/.var/app/com.github.iwalton3.jellyfin-media-player/data/jellyfinmediaplayer/logs/`
     - macOS: `~/Library/Logs/Jellyfin Media Player/`

**Describe the bug**
Since update to jellyfinmediaplayer 1.11.1 on Arch Linux (from AUR), but when I try to play anything, it told me "Playback failed with error "loading failed". Retry with transcode? (Note this may hang the player.)" and after, this "PlaybackError.mediadecodeerror". 

**To Reproduce**
1. Just play any type of media.

**Expected behavior**
I want to play my music or my videos. On others clients and platforms, I have no issues...

**Screenshots**
![image](https://github.com/jellyfin/jellyfin-media-player/assets/154517534/9ff39a90-8402-40ef-be2a-d7d98f3cd139)
![image](https://github.com/jellyfin/jellyfin-media-player/assets/154517534/4e89badf-ce91-4525-8420-576b41880cdd)

**Desktop (please complete the following information):**
 - OS: Arch Linux 
 - Version rolling, kernel Linux 6.9.5-arch1-1, Gnome 46
 - Installation Method AUR

**Additional context**

**Comment by AliceT50** [comment]
Hi ! 
Thank you for your answer. I tried like you said, but mpv, vlc or ffplay works perfectly with stream URL. I don't get any crashes or errors. 
And I tried to understand what the issue is (from links)... Unfortunately , to be honest, I'm french, so my english makes me troubles to understand how to patch it... 
The really strange part is, it's only happen with JellyfinMediaPlayer.

**Comment by ExpatUK** [comment]
Same thing with the latest build installed via brew on macOS

**Comment by kstorbakken** [comment]
Can you try enabling the Auto-Detect Certificate Bundle client setting? This immediately fixed the issue on my end using the AUR package. You'll need to restart the client after enabling it.
![image](https://github.com/jellyfin/jellyfin-media-player/assets/74789296/c2dba90d-738b-4e59-a346-8dc4bfdd5de0)

**Comment by AliceT50** [comment]
Oh ! Thank you [kstorbakken](https://github.com/kstorbakken) ! The issue was only this... I tried with logs and get pretty the same error than you show on your captured image. 
So, if I really understand, it's just a certificate problem from JellyfinMediaPlayer that don't want to work with certificates from system... I hope this is going to be solved in future patches.
Thank you all for your help !
I close this issue

**Comment by leaty** [comment]
Leaving this for anyone else with a self-signed certificate and `ignoreSSLErrors` enabled, where the above solution doesn't work.

In my case it was because I previously only accepted TLS 1.3 in my reverse proxy, and apparently `mbedtls` hard *requires* certificate verification for TLS 1.3. `ffmpeg` has a [workaround](https://github.com/FFmpeg/FFmpeg/commit/c28e5b597ecc34188427347ad8d773bf9a0176cd) for this which downgrades to TLS 1.2.

**nginx**
```nginx
ssl_protocols TLSv1.2 TLSv1.3;
```

Solved!

**Comment by leaty** [comment]
> On arch this is resolved, reverting back to gnutls. Deepening on distro, maybe they should switch as well to support streams until this is resolved https://gitlab.archlinux.org/archlinux/packaging/packages/ffmpeg/-/merge_requests/6 (needs a rebuild of the JMP)

Just FYI that was never merged and it probably won't be.
