### ISSUE TITLE
Offer controls for track (subtitle) synchronization

### ISSUE THREAD

**Issue by rexendevar** [jellyfin/jellyfin-media-player#717]
**Is your feature request related to a problem? Please describe.**
I can't stand when the subtitles are seconds off the audio. Unofrtunately this is a constant occurrence. Would like to be able to make them happen earlier or later to compensate.

**Describe the solution you'd like**
Under the subtitles submenu in the player, I would like a little section at the top with a number field for seconds of offset and two radio buttons for "earlier" or "later." Offset would start at 0.00 seconds and the other two buttons would be grayed out until a value is entered (maybe could also use arrow keys or scroll wheel on the number field). You could implement the same feature under the audio selector submenu as well to offset the audio track from the video but this isn't something I've ever personally required. Also the UI I describe is just a concept to make it easier than VLC's system

**Describe alternatives you've considered**
VLC has this but it's a massive pain to set up. The number field is garbage, it takes ages to register the change and the program keeps crashing. Jellyfin is how I watch all my movies anyway & I don't enjoy switching programs.

**Additional context**
![image](https://github.com/jellyfin/jellyfin-media-player/assets/46948713/35dc6c88-f4ef-4419-bc4b-311ce48ad5b1)
this is what it looks like in VLC so u know what I'm talking about

**Comment by wouterx** [comment]
maybe i dont understand,   jellyfin media player already has the ability to adjust subtitle timing.

**Comment by rexendevar** [comment]
have i been switching programs for nothing??? how do i do that

**Comment by wouterx** [comment]
while playing, turn subtitles on, press settings, press subtitle timing (could be named differently, i am using another language), then you can adjust timing on the fly.

**Comment by rexendevar** [comment]
I have pressed every little button at the bottom of my screen and found
nothing of the sort. what settings? i pressed the cog icon and it only
gives me resolution options

**Comment by wouterx** [comment]
then maybe you are not using the  "jellyfin media player"  for windows, but another jellyfin client, like the google tv one..........?

**Comment by rexendevar** [comment]
I'm on the android one currently. i assumed there was more or less feature
parity between all fully updated platforms

**Comment by wouterx** [comment]
this is specifically for the desktop clients "Jellyfin media player",   so your request should go elsewhere

**Comment by Dangonizer** [comment]
I am on the desktop client and I cant find the setting either. Have been wishing for that for a long time. Can you specify how to get to the setting. My settings look like this.
![image](https://github.com/user-attachments/assets/13ae1483-7083-400f-92fc-550054d6684b)

**Comment by aaruni96** [comment]
I am on the desktop jellyfin client, and I don't see the option for subtitle delay either.

**Comment by wouterx** [comment]
weirdly the subtitle timing function only appears when using external subtiles.     I tested with a file that has an external srt and internal.   The option only appears when playing the external subtitles.   This while the web client has the option to adjust both.
