### ISSUE TITLE
新的版本不能添加多个emby服吗？

### ISSUE THREAD

**Issue by xlh8394** [jellyfin/jellyfin-media-player#730]
![屏幕截图 2024-07-12 125832](https://github.com/user-attachments/assets/66c24e22-922b-4296-bf38-a26c3fe0b843)

**Comment by xlh8394** [comment]
![屏幕截图 2024-07-12 130353](https://github.com/user-attachments/assets/5b33c174-e0eb-469e-ae99-2fd60f6d1710)

**Comment by thornbill** [comment]
**Jellyfin** Media Player does not support Emby
