### ISSUE TITLE
[bug] Client gets in a bad state and doesn't show new pages after clicking on tiles

### ISSUE THREAD

**Issue by utkashd** [jellyfin/jellyfin-media-player#733]
It seems like the most recent Jellyfin (server) update borked something in this client. As of today, my brother and I both have this issue with the client:

https://github.com/user-attachments/assets/ee208599-6178-46c0-a302-358349ddc909

Basically, after some clicking and navigating, clicking the tiles seems to (mostly) stop changing the main screen. I hear audio from movies after clicking the play button, and for music, the player on the bottom updates, but the main section will not change.

This seems exclusive to the desktop client. The client in the web browser does not have this issue, and @kddubey has this issue on his M2 Macbook as well.

> How you installed Jellyfin (upgrade or fresh install)

Upgraded Jellyfin to 10.9.8
```
Server version
10.9.8
Web version
10.9.8
Build version
10.9.8
```

> What platform and operating system you are using (Debian, Arch, Docker, etc.)

Jellyfin server is running in a docker container in a Synology NAS and the container image was updated last night

> What you were doing that caused the issue to appear

Click a library, click the Home icon, maybe repeat a few times, then try clicking a library or another tile. The main screen does not change, though scrolling and some other functions work.

> Any relevant log output

I didn't see anything that looked relevant, but here it is:
[Jellyfin Media Player.log](https://github.com/user-attachments/files/16327553/Jellyfin.Media.Player.log)

> Any non-standard configurations you use

None come to mind

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - Client Version: v1.11.1 (downloaded the `.dmg` and installed that way)

**Comment by utkashd** [comment]
To clarify: In the video, around 0:04 I am clicking the library tiles and nothing is changing. Then I demonstrate some of the functions that still work (clicking the vertical dots, the mini-player for songs) and then show that the hamburger nav also fails to change the main screen

**Comment by garvied1** [comment]
The same thing happens, I have version 10.9.8 of the server installed on Xubuntu 24.04 and version 1.11.1 of the player installed with the deb file downloaded from Github on Kubuntu 24.04.
When I enter the player I cannot access any of the libraries.
I have tried uninstalling the program and installing it via flatpak and it seems to work.

**Comment by mixtah** [comment]
Appears this is happening to me, running 10.9.9 using Windows and Docker. 
Was working well for the past month and worked half an hour ago, now as described above. Clicking any button on the homepage doesn't react. 

I can "play next" on a show, I'll get the audio from the show but the page doesn't update and I still see the menu while the shoes audio plays.

I haven't tried a reinstall, but restarting the docker container didn't help.

**Comment by polyzen** [comment]
Try running the `Clear Cache Directory` task:
https://github.com/jellyfin/jellyfin-media-player/issues/734#issuecomment-2247469932

**Comment by utkashd** [comment]
> Try running the `Clear Cache Directory` task: [#734 (comment)](https://github.com/jellyfin/jellyfin-media-player/issues/734#issuecomment-2247469932)

Seems to be resolved with this. I'm closing this issue, though manually removing the cache shouldn't be necessary
