### ISSUE TITLE
No window counter indicators in taskbar/dock on Linux

### ISSUE THREAD

**Issue by viggy96** [jellyfin/jellyfin-media-player#76]
**Describe the bug**
JMP doesn't show window counter indicators in the taskbar/dock on Linux

**To Reproduce**
1. Open JMP
2. Look at taskbar/dock
3. Profit

**Expected behavior**
Window counter indicator is shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/9837626/116766840-9912db00-a9fa-11eb-91a6-79ad82dfb8ab.png)

Line is shown under Google Chrome icon in the dock to indicate a Chrome window is open, however a line is not shown under the JMP icon even though its also open.

**Desktop (please complete the following information):**
 - OS: Manjaro GNOME
 - Installation Method: AUR

**Additional context**
Have only seen this on GNOME so far. Would be interesting to find out if users on other desktop environments see this issue.

**Comment by iwalton3** [comment]
This works in KDE. What are you using with GNOME as it doesn't have a task switcher by default? 
![image](https://user-images.githubusercontent.com/8078788/116790308-6c55d680-aa81-11eb-9e3e-d66c44fe6d36.png)

**Comment by viggy96** [comment]
Very strange. This appears to be a dash-to-dock bug. Not sure what's going on here. Just checked by disabling the dash-to-dock extension. JMP does properly show a window indicator in the dock under activities.
