### ISSUE TITLE
Opus Direct Codec Audio not playing

### ISSUE THREAD

**Issue by veerpandya** [jellyfin/jellyfin-media-player#764]
**Describe the bug**
Videos with opus audio do not have any sound when played through the media player client and when the audio is not transcoded.  Other videos work fine, and the same video will work as expected when the audio is transcoded (tested via web client and android client).  This same exact video file will also play properly when downloaded to the computer and played via VLC.

**To Reproduce**
1. Play video with audio using the opus codec
2. Allow video to direct play opus audio codec
3. Hear no audio being played

**Expected behavior**
The opus audio track should play properly through direct play, or it should be transcoded if direct play for opus is not supported.

**Screenshots**
<img width="458" alt="Screenshot 2024-09-16 at 9 22 03 AM" src="https://github.com/user-attachments/assets/061c9b6f-3291-43e2-b3ba-358c3883e07e">

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma 14.6.1
 - Version: 1.11.1
 - Installation Method: Intel Mac dmg installer

I checked that this same behavior is occurring on my Arch Linux computer.

**Additional context**
Logs attached here:
[jellyfin_client.log](https://github.com/user-attachments/files/17014014/jellyfin_client.log)

Something I'm unsure about is why complete direct play (for both video and audio) is not working.  The playback info just says there was an error starting  direct play.  I don't know if this is related to the main opus audio issue but I just wanted to point it out.

Also, I would love to help out as much as I can on this issue.  Please let me know where I can dig further to provide more information.

**Comment by hildeka** [comment]
I'm facing the same issue with OPUS, yet additionally videos with Dolby TrueHD codec also don't play any audio. Otherwise everything is the same.

I have encountered this in both native (NixOS, OpenSUSE and Arch Linux) and flatpak packages.

**Comment by hildeka** [comment]
It's embarrassing to admit, yet the issue got resolved after I updated jellyfin on the server (automatic updates stopped working and I didn't realize).

**Comment by veerpandya** [comment]
Yep, same thing for me.  I simply updated my server and now everything is fixed.  I'll close this issue out.  Thanks!
