### ISSUE TITLE
jellyfin media player immediately phones home to github without consent when connecting to a server

### ISSUE THREAD

**Issue by sneak** [jellyfin/jellyfin-media-player#767]
1.11.1 macos arm

**To Reproduce**
1. launch jellyfin, enter server address
2. jellyfin client contacts server entered
3. login screen appears

**Expected behavior**

Only the server entered is contacted. 

**Actual behavior**

Jellyfin Media Player contacts github.com

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.11.1
 - Installation Method: download from github

**Comment by iwalton3** [comment]
This is intentional to check for software updates. The behavior can be disabled in the config or settings page.

**Comment by sneak** [comment]
Obviously.  But it happens without consent and leaks my use of jellyfin and my IP address to Microsoft without consent.

It should ask before phoning home.

**Comment by sneak** [comment]
Furthermore, I think it's a reasonable assumption that selfhosted software used primarily for large scale piracy is used by people who don't want a default of it phoning home to a large rightsholding multinational letting them know they're using it.

Just a hunch.
