### ISSUE TITLE
Music volume resets across restarts, but volume slider does not

### ISSUE THREAD

**Issue by jacobrham** [jellyfin/jellyfin-media-player#78]
- Please provide logs:

[Log](https://paste.ee/p/hzzJn) (this log didn't get past Pastebin's filters for some reason)

**Describe the bug**
If you change the audio volume slider for music in the Jellyfin Media Player UI then restart the application and play music again, the music will play at full volume, but the slider will still look like it's in the same position as when you last closed JMP. I have tested the same functionality through the web UI in Firefox, and audio preferences persist across tab closes and browser restarts.

**To Reproduce**
1. Play a song from a music library
2. Change the volume slider in the lower left hand corner of the interface.
3. Exit Jellyfin Media Player
4. Start Jellyfin Media Player
5. Play a song from a music library
6. Listen to your song at full volume

**Expected behavior**
After restarting JMP, music should play at the same volume as it did when the application was closed.

 - OS: Manjaro Linux with KDE Plasma 5.21.4
 - Version: Jellyfin Media Player 1.5.0
 - Installation Method :Installed from the Arch User Repository

**Comment by iwalton3** [comment]
This will be fixed in the next release.
