### ISSUE TITLE
Search feature not working when searching live tv channels

### ISSUE THREAD

**Issue by candry7731** [jellyfin/jellyfin-media-player#80]
**Describe the bug**
- When searching for Live TV channels on the web player the channels are returned in the heading "Videos".
- When searching for live channels on the roku player, both beta and stable versions, no channels are retuned.

**To Reproduce**
1. Go to seach
2. Type channel name
3. Nothing is displayed in the roku app and on the web player channels are labeled as "Videos"

**Expected behavior**
*When searching for a live tv channel they should be under a section heading "TV Channels"
*Also, All channels with the characters should be returned. for instance if I search "ESPN", I would expect "USA ESPN" , "CA ESPN" , "ESPN +" , "ESPN 2"
*Also it would be great to add a loading icon on both the webpayer and th roku apps when the server is searching. Right now there is a blank screen and the user is not sure if the app is frozen or searching. 
  

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - browser: Google Chrome 
 - 
![Capture](https://user-images.githubusercontent.com/83685828/117095027-c88f5380-ad2a-11eb-8885-aa2f302b505c.PNG)
Version 90.0.4430.93 (Official Build) (64-bit)

**Comment by iwalton3** [comment]
This repo is for the desktop app only. Please open an issue in the correct repository.
