### ISSUE TITLE
Subtitles displayed as square on 1.60 mac

### ISSUE THREAD

**Issue by obeykarma** [jellyfin/jellyfin-media-player#82]
After upgraded to version 1.60
The subtitle displayed as square, sloved when rolling back to 1.50

**Comment by iwalton3** [comment]
Try the build here when it is completed: https://github.com/jellyfin/jellyfin-media-player/actions/runs/812277655

I suspect it is an MPV issue. Note you have to run it with the context menu. (https://mjtsai.com/blog/2020/08/19/cant-you-just-right-click/)

**Comment by iwalton3** [comment]
https://github.com/jellyfin/jellyfin-media-player/suites/2653804252/artifacts/58358491

**Comment by shanke0303** [comment]
> https://github.com/jellyfin/jellyfin-media-player/suites/2653804252/artifacts/58358491

Hi @iwalton3,
It is not work on my mac.So I use back to v1.5.0 witch is fine.
My sutitle of this movie is Chinese(Simplified).

**Comment by jaxwang** [comment]
the  same situation as you

**Comment by iwalton3** [comment]
Closing as stale. Please re-open if this issue is still applicable.
