### ISSUE TITLE
[Linux] `vo=gpu-next` cause video playback in detached MPV window

### ISSUE THREAD

**Issue by leo9800** [jellyfin/jellyfin-media-player#824]
**Describe the bug**
When `vo=gpu-next` or `vo=gpu` is set as custom MPV configuration, the media player window detached from main jellyfin window.

`vo=gpu-next` in MPV configuration is to-some-extend necessary for GPU-accelerated HDR tone mapping on client side.

**To Reproduce**
1. Install *jellyfin-media-player*
2. Run *jellyfin-media-player*
3. *Settings* -> *Client Settings*
4. Scroll to bottom, append following lines to *Manual MPV Configuration*

```
vo=gpu-next
tone-mapping=bt.2390
```

5. Save, restart
6. Play any media

**Expected behavior**
The media is played inside jellyfin window

**Screenshots**

Expected: video played back in jellyfin window

![Image](https://github.com/user-attachments/assets/5d8fe039-91d0-4a4a-b4dd-267bcaf6a7ff)

Actual: video played back in a detached MPV window, jellyfin window is blank

![Image](https://github.com/user-attachments/assets/621f6c7e-59e0-4b6c-9c89-341633fb594d)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 1.11.1
 - Installation Method: AUR (https://aur.archlinux.org/packages/jellyfin-media-player)

**Additional context**
N/A

**Comment by Puthus** [comment]
Same is happening on windows 11, 

Screenshot

![Image](https://github.com/user-attachments/assets/4c33bc92-afae-4256-909e-a71a38497352)

Desktop (please complete the following information):

OS: Windows 11 PRO 24H2 
Version: 1.11.1
Installation Method: Executable -> JellyfinMediaPlayer-1.11.1-windows-x64.exe

**Comment by GRFTSOL** [comment]
I don't think it's a bug, see mpv's manual: https://mpv.io/manual/stable/#video-output-drivers
> libmpv
> For use with libmpv direct embedding. As a special case, on macOS it is used like a normal VO within mpv (cocoa-cb). Otherwise useless in any other contexts. (See <mpv/render.h>.)
> This also supports many of the options the gpu VO has, depending on the backend.

AFAIK, JMP is using libmpv, so it should be `vo=libmpv` in JMP's applying.

**Comment by leo9800** [comment]
@GRFTSOL seems to be correct. when removing or commenting out the line `vo=gpu-next`, `vo=libmpv` is used by default, which could be confirmed by this line in the log file:

```
2024-12-16 11:25:32.561 [debug] unknown @ 0 - cplayer: Set property: vo="libmpv" -> 1
```

Since this seems not a bug of JMP, this issue would be closed.

**Comment by leo9800** [comment]
While unfortunately, client-side tone mapping may still unavailable for JMP, unless accepting a less-decent implementation. (`vo=gpu-next` or `vo=gpu` and 2 windows)

**Comment by sedago** [comment]
Looks like people have gotten it to work with libmpv, would be great to see this in jellyfin-desktop in the future: https://github.com/mpv-player/mpv/issues/6575
