### ISSUE TITLE
Windows media key PAUSE/PLAY resets albums/playlists on resume

### ISSUE THREAD

**Issue by joytrekker** [jellyfin/jellyfin-media-player#83]
Windows 10
Jellyfin Media Player v1.6.0

1. Start playing a music album from a library page by pressing the play button on the album cover art. (do not open the dedicated album/playlist page)
2. Use media keys to skip a few tracks
3. Press the play/pause media key (music will correctly pause)
4. Prese play/pause again to resume playing
Music will jump to the first track and start playing from the beginning.
If you open the dedicated page for an album or playlist and then start playback, PLAY/PAUSE works as expected. The bug only happens when starting playback with the album art button on a library page.
  
**Expected behavior**

The current playing track will resume playback on PLAY/PAUSE

**NOTE**
It may have to do with jellyfin web. I tried using media keys through the browser and PREVIOUS and NEXT work. However PLAY/PAUSE seems to pause for a milisecond but immediatly resumes.

**Comment by iwalton3** [comment]
Try this CI build when it completes: https://github.com/jellyfin/jellyfin-media-player/actions/runs/813273891

**Comment by joytrekker** [comment]
Just tested that build and PLAY/PAUSE is fixed. Nice work!
