### ISSUE TITLE
Higher Playback speed/Playback speed steps of 0.1

### ISSUE THREAD

**Issue by nigelwarning** [jellyfin/jellyfin-media-player#87]
**Is your feature request related to a problem? Please describe.**
It is no problem.

**Describe the solution you'd like**
I would love to have more options to change playback speed. In MPV you can do steps from 0.1 and go higher. Would love to have the option to start from 1 and go up 0.1 until a playback speed of 6.

**Describe alternatives you've considered**
Using MPV as main video player for videos. But I want the Jellyfin connections

**Comment by makuc** [comment]
Agreed. Lower adjustment steps than 0,25 would be greatly appreciated. Steps of 0,1 would be perfect.

**Comment by sevenrats** [comment]
Hey gang thanks for your feature request. Because you are asking for a change in jellyfin-web, the ui component inside JMP, you need to open this feature request at features.jellyfin.org
As is, it can't be implemented here.  Thanks again!
