### ISSUE TITLE
Flatpak fails to start on Wayland

### ISSUE THREAD

**Issue by KucharczykL** [jellyfin/jellyfin-media-player#90]
**Describe the bug**
If I run the Flatpak version, an error appears and the application doesn't start.

The error:
```
libpng warning: iCCP: known incorrect sRGB profile
Logging to /home/lukas/.var/app/com.github.iwalton3.jellyfin-media-player/data/jellyfinmediaplayer/logs/jellyfinmediaplayer.log
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
mesa: for the --structurizecfg-skip-uniform-regions option: may only occur zero or one times!
wl_drm@35: error 0: authenticate failed
VA error: wayland: Wayland roundtrip error: Protocol error (errno 71)
Cannot load libcuda.so.1
```

**To Reproduce**
1. Install the Flatpak version.
2. Run it.
3. See error

**Expected behavior**
Application should launch.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Installation Method: Flatpak

**Additional context**
The Flatpak version only stopped working recently though I can't identify when exactly.
Installing the AUR package (ie. compiling from source) works: https://aur.archlinux.org/packages/jellyfin-media-player-git/

**Error Logs**
Flatpak (non-working): 
[jellyfinmediaplayer.log](https://github.com/jellyfin/jellyfin-media-player/files/6480929/jellyfinmediaplayer.log)
AUR (working):
[jellyfinmediaplayer.log](https://github.com/jellyfin/jellyfin-media-player/files/6480932/jellyfinmediaplayer.log)

**Comment by mimed95** [comment]
I have exactly the same issue. I'm running Fedora 34 on Gnome Wayland.

**Comment by SlaterTh90** [comment]
Can confirm, I also have this issue with Fedora Silverblue 34 (Flatpak 1.10.2, Mesa 21.1.1). Starting using XWayland does also not help.

**Comment by sp1ritCS** [comment]
Same hare, openSUSE Tumbleweed both with GNOME/Mutter & swaywm/wlroots.

However running with
```sh
flatpak run --socket=x11 --nosocket=wayland --socket=fallback-x11 com.github.iwalton3.jellyfin-media-player
```

works for me.

**Comment by KucharczykL** [comment]
As mentioned in https://github.com/flatpak/flatpak/issues/4289, I just tested this again and it works.

**Comment by iwalton3** [comment]
Referenced here: https://github.com/flathub/com.github.iwalton3.jellyfin-media-player/issues/1

There is apparently still an issue with running on Wayland. If anyone is aware of how to fix this, please let me know. For now it is just disabled and will fall back to X11 automatically in Flatpak.

**Comment by jwillikers** [comment]
Strangely enough, I just switched the Flatpak to use Wayland instead of X11 and I'm having no issues starting it. Video playback works too. I'm running under Sway on Fedora 35.

**Comment by MayeulC** [comment]
Is that still an issue? The upstream mpv issue was solved back with org.freedesktop.Platform 20.08.13.

**Comment by KucharczykL** [comment]
When I try to run it now:
```
$ flatpak run com.github.iwalton3.jellyfin-media-player
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```
Is it just me?

**Comment by MayeulC** [comment]
@KucharczykL No, they disabled wayland support in the flatpak. To restore it, you can use `flatpak override` and restore access to the wayland socket, or do it with the flatseal GUI.

See https://github.com/flathub/com.github.iwalton3.jellyfin-media-player/issues/4

**Comment by KucharczykL** [comment]
@MayeulC Right, I completely forgot about that. Doing `flatpak override --socket=wayland com.github.iwalton3.jellyfin-media-player` makes it work for me on Wayland so I think the original error is gone.

**Comment by MayeulC** [comment]
Thank you for confirming this issue is gone on your side :)

Now there seems to just be the titlebar issue #40 preventing re-enabling it, but I don't use gnome, so I cannot test right away and see if it is already fixed. It would be interesting to try a newer runtime and see if the issue is fixed, as that's a use-case either Gnome or Qt should handle automatically.
