### ISSUE TITLE
scripts don't work or mpv.conf not used?

### ISSUE THREAD

**Issue by phob** [jellyfin/jellyfin-media-player#92]
Hi,

with mpv you can use scripts and I use autocrop. So I placed a scripts directory inside of %LOCALAPPDATA%\JellyfinMediaPlayer\ with the script and created a mpv.conf besides jellyfinmediaplayer.conf with `script=C:\Users\pho\AppData\Roaming\jellyfin-mpv-shim\scripts\autocrop.lua`. The script won't work.

I even tested setting the volume to 0 and that didn't work:
`volume=0`

I'm beginning to suspect that the config will not be used whatever I configure.

This is more of a question than a bug report because I think I misunderstand something here.
I was able to configure jellyfin-mpv-shim desktop to use mpv_ext and then configure the scripts there in the past.

**Comment by TheTyrius** [comment]
I observed something similar (tho in the context of another issue where I tried to work around using the `mpv.conf`): https://github.com/jellyfin/jellyfin-media-player/issues/35#issuecomment-877483800

Today I was able to confirm that the `mpv.conf` besides the jellyfinmediaplyer config-file is indeed being loaded (by setting `video-zoom=2`, resulting in a zoomed-in image as expected). I suspect both our attempts to set either `audio-delay` or `volume` there are simply overridden later.

**Comment by sevenrats** [comment]
mpv.conf definitely works. im not sure about script support. feel free to stop by the chat spaces if you want support with figuring out which jellyfin clients can use your scripts (for example, I think the mpv-shim can)
