### ISSUE TITLE
JF Media Player 1.6 not properly sending "watched" status to Trakt after episode end.

### ISSUE THREAD

**Issue by Jinxyface** [jellyfin/jellyfin-media-player#93]
**Describe the bug**
When watching an episode through Jellyfin Media Player (With Trakt plugin installed and scrobbling enabled), episode will properly scrobble through Trakt and show it as being played on Trakt profile. However, once the episode is done, it is not mark watched on Trakt (but is marked watched locally).

This does NOT happen when watching just through the browser. Once the episode is finished it will be marked watched on Trakt properly, so seems to be isolated to Jellyfin Media Player

**To Reproduce**
1. Launch episode through Jellyfin Media Player
2. Watch Episode
3. Episode Ends
4. Episode not marked watched in Trakt

**Expected behavior**
The episode will be marked watched in Trakt

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.6
 - Installation Method: Windows Installer

**Additional context**
Was working fine on Jellyfin 10.7.2, not working on 10.7.5

Let me know if there are any logs to provide.

**Comment by sevenrats** [comment]
this is a server issue which will not be marked for moving because it references a deprecated release which is missing many security patches. do not use the server version listed, and open a new report if you still experience this issue.
